// Code generated by protoc-gen-go. DO NOT EDIT.
// source: polaris/polaris.proto

package polaris // import "dsp-template/api/polaris/polaris"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import base "dsp-template/api/base"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// **************************** PolarisRequest 输入协议 ***************************
type PolarisRequest struct {
	// 1. 竞价请求的唯一ID。
	// [AS ]: 1) 请求ID
	// [DSP]: 1) RTB标准字段。bidRequest.id
	Baserequest *base.BaseRequest `protobuf:"bytes,1,opt,name=baserequest,proto3" json:"baserequest,omitempty"`
	// 2. 竞价请求的adx名称。
	// [AS ]: 1) 请求AdExchange Name，特指"mintegral"
	// [DSP]: 1) 非RTB字段。请求AdExchange Name
	Exchange string `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// 3. 广告展示类型，banner，native，video。
	// [DSP]: 1) 非RTB字段。判断bidRequest.imp中banner，native，video是否不为空
	ImpType string `protobuf:"bytes,3,opt,name=imp_type,json=impType,proto3" json:"imp_type,omitempty"`
	// 4. 细分的广告展示类型。
	// [AS ]: 1) 使用UnitID查询mongo数据得到，（参考enum_ad_type）
	// [DSP]: 1) 非RTB字段。判断Imp中的一系列字段得到，（b，i，n，vna，vre，vis，vin...）
	AdType int32 `protobuf:"varint,4,opt,name=ad_type,json=adType,proto3" json:"ad_type,omitempty"`
	// 5. 可投放的素材组id，目前腾讯、头条、爱奇艺使用。
	// [DSP]: 1) RTB非标字段。国内ADX投放审核素材组时使用, CreativeSpecSlice
	AdSeat []string `protobuf:"bytes,5,rep,name=ad_seat,json=adSeat,proto3" json:"ad_seat,omitempty"`
	// 6. 预检索的广告展示offer信息数组。
	// [AS ]: 1) 检索单子优先队列
	// [DSP]: 1) 非RTB字段。检索单子队列
	CampaignIdList []int64 `protobuf:"varint,6,rep,packed,name=campaign_id_list,json=campaignIdList,proto3" json:"campaign_id_list,omitempty"`
	// 7. 最大召回campaign数量，当检索到素材的单子数量达到max后，停止检索素材。默认检索完全部的单子队列
	// [AS ]: 1)
	// [DSP]: 1)
	CampaignMax int32 `protobuf:"varint,7,opt,name=campaign_max,json=campaignMax,proto3" json:"campaign_max,omitempty"`
	// 8. Banner对象，如果展示需要以banner的形式提供则需要填充。
	// [AS ]: 1) pioneer传递的信息
	// [DSP]: 1) RTB标准字段。imp.banner object
	Banner *RequestBanner `protobuf:"bytes,8,opt,name=banner,proto3" json:"banner,omitempty"`
	// 9. Native对象， 如果展示需要以Native广告的形式提供则需要填充。
	// [DSP]: 1) RTB标准字段。imp.native object
	Native *RequestNative `protobuf:"bytes,9,opt,name=native,proto3" json:"native,omitempty"`
	// 10. Video对象， 如果展示需要以视频的形式提供则需要填充。RTB标准字段。
	// [DSP]: 1) RTB标准字段。imp.video object
	Video *RequestVideo `protobuf:"bytes,10,opt,name=video,proto3" json:"video,omitempty"`
	// 11. Device对象， 表示展示将要被发送到的用户设备的信息。RTB标准字段。
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段。device object
	Device *RequestDevice `protobuf:"bytes,11,opt,name=device,proto3" json:"device,omitempty"`
	// 12. 用于在处理检索请求时避免超时的最大时间，以毫秒为单位。处理时间超出tmax则返回timeout-response
	// [AS ]: 1) As定义超时时间
	// [DSP]: 1) RTB标准字段。tmax
	Tmax int32 `protobuf:"varint,12,opt,name=tmax,proto3" json:"tmax,omitempty"`
	// 13. 标识测试模式， false表示实况（非测试）模式，true表示测试模式
	// [AS ]: 1) 上游协议参数，testmode
	// [DSP]: 1) RTB标准字段。test
	Test bool `protobuf:"varint,13,opt,name=test,proto3" json:"test,omitempty"`
	// 14. ext
	// [DSP]: 1) 国内ADX的扩展字段
	Ext *RequestExt `protobuf:"bytes,14,opt,name=ext,proto3" json:"ext,omitempty"`
	// 15.if_support_dco
	// [AS]: 1）该dco的请求切量开关，值为1表示需切量dco
	// [DSP]: 1)
	IfSupportDco int32 `protobuf:"varint,15,opt,name=if_support_dco,json=ifSupportDco,proto3" json:"if_support_dco,omitempty"`
	// 16.流量特定的需要召回的素材属性
	// [DSP]:
	CreativeFeatures []string `protobuf:"bytes,16,rep,name=creative_features,json=creativeFeatures,proto3" json:"creative_features,omitempty"`
	// 17.提供指定检索模版的定向
	// [DSP]: debug
	DebugTemplateList []int32 `protobuf:"varint,17,rep,packed,name=debug_template_list,json=debugTemplateList,proto3" json:"debug_template_list,omitempty"`
	// 18.多图召回，图片数量
	// [DSP]:
	MultiImageCount int32 `protobuf:"varint,18,opt,name=MultiImageCount,proto3" json:"MultiImageCount,omitempty"`
	// 19. 部分模版定向
	// [DSP]:
	// [RTDSP]:
	// [AS]:
	// [Pivot]:
	BusinessType string `protobuf:"bytes,19,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	// 20. adx指定模版
	// [DSP]
	// [RTDSP]
	TargetTemplate string `protobuf:"bytes,20,opt,name=target_template,json=targetTemplate,proto3" json:"target_template,omitempty"`
	// 21, abtest 代码侵入式标记，测试模版召回规则变动的影响
	// [DSP]
	// [RTDSP]
	// [Pivot]
	AbTest map[string]string `protobuf:"bytes,21,rep,name=ab_test,json=abTest,proto3" json:"ab_test,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 22,描述召回大模板的slot是否为固定slot数及变长slotNum的个数，slotNum为0，定长大模板，slotNum >0 变长大模板及大模板需要的slot数目。
	// [DSP]
	// [Pivot]
	AdNum int32 `protobuf:"varint,22,opt,name=adNum,proto3" json:"adNum,omitempty"`
	// 23请求类型： sdk,onlineApi,site等
	// [AS]请求来源
	RequestType int32 `protobuf:"varint,23,opt,name=requestType,proto3" json:"requestType,omitempty"`
	// 24.if_support_webgl
	// [AS]: 1）webgl的请求开关，为1时表明支持3d playable素材
	// [DSP]: 1)
	IfSupportWebgl int32 `protobuf:"varint,24,opt,name=if_support_webgl,json=ifSupportWebgl,proto3" json:"if_support_webgl,omitempty"`
	// 25.if_support_bigTemplate
	// [AS] 1）用以表示请求是素材三期还是大模板请求，素材三期只能召回101大模板
	BigTemplateSupport bool `protobuf:"varint,25,opt,name=bigTemplateSupport,proto3" json:"bigTemplateSupport,omitempty"`
	// 26.IfSupportRewardPlus
	// [AS] 1)是否支持401大模板
	IfSupportRewardplus bool `protobuf:"varint,26,opt,name=if_support_rewardplus,json=ifSupportRewardplus,proto3" json:"if_support_rewardplus,omitempty"`
	// 27.
	// [DSP] 1)仅召回playable素材
	OnlyPlayableCreative bool     `protobuf:"varint,27,opt,name=only_playable_creative,json=onlyPlayableCreative,proto3" json:"only_playable_creative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolarisRequest) Reset()         { *m = PolarisRequest{} }
func (m *PolarisRequest) String() string { return proto.CompactTextString(m) }
func (*PolarisRequest) ProtoMessage()    {}
func (*PolarisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{0}
}
func (m *PolarisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolarisRequest.Unmarshal(m, b)
}
func (m *PolarisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolarisRequest.Marshal(b, m, deterministic)
}
func (dst *PolarisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolarisRequest.Merge(dst, src)
}
func (m *PolarisRequest) XXX_Size() int {
	return xxx_messageInfo_PolarisRequest.Size(m)
}
func (m *PolarisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolarisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolarisRequest proto.InternalMessageInfo

func (m *PolarisRequest) GetBaserequest() *base.BaseRequest {
	if m != nil {
		return m.Baserequest
	}
	return nil
}

func (m *PolarisRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PolarisRequest) GetImpType() string {
	if m != nil {
		return m.ImpType
	}
	return ""
}

func (m *PolarisRequest) GetAdType() int32 {
	if m != nil {
		return m.AdType
	}
	return 0
}

func (m *PolarisRequest) GetAdSeat() []string {
	if m != nil {
		return m.AdSeat
	}
	return nil
}

func (m *PolarisRequest) GetCampaignIdList() []int64 {
	if m != nil {
		return m.CampaignIdList
	}
	return nil
}

func (m *PolarisRequest) GetCampaignMax() int32 {
	if m != nil {
		return m.CampaignMax
	}
	return 0
}

func (m *PolarisRequest) GetBanner() *RequestBanner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *PolarisRequest) GetNative() *RequestNative {
	if m != nil {
		return m.Native
	}
	return nil
}

func (m *PolarisRequest) GetVideo() *RequestVideo {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *PolarisRequest) GetDevice() *RequestDevice {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *PolarisRequest) GetTmax() int32 {
	if m != nil {
		return m.Tmax
	}
	return 0
}

func (m *PolarisRequest) GetTest() bool {
	if m != nil {
		return m.Test
	}
	return false
}

func (m *PolarisRequest) GetExt() *RequestExt {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *PolarisRequest) GetIfSupportDco() int32 {
	if m != nil {
		return m.IfSupportDco
	}
	return 0
}

func (m *PolarisRequest) GetCreativeFeatures() []string {
	if m != nil {
		return m.CreativeFeatures
	}
	return nil
}

func (m *PolarisRequest) GetDebugTemplateList() []int32 {
	if m != nil {
		return m.DebugTemplateList
	}
	return nil
}

func (m *PolarisRequest) GetMultiImageCount() int32 {
	if m != nil {
		return m.MultiImageCount
	}
	return 0
}

func (m *PolarisRequest) GetBusinessType() string {
	if m != nil {
		return m.BusinessType
	}
	return ""
}

func (m *PolarisRequest) GetTargetTemplate() string {
	if m != nil {
		return m.TargetTemplate
	}
	return ""
}

func (m *PolarisRequest) GetAbTest() map[string]string {
	if m != nil {
		return m.AbTest
	}
	return nil
}

func (m *PolarisRequest) GetAdNum() int32 {
	if m != nil {
		return m.AdNum
	}
	return 0
}

func (m *PolarisRequest) GetRequestType() int32 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

func (m *PolarisRequest) GetIfSupportWebgl() int32 {
	if m != nil {
		return m.IfSupportWebgl
	}
	return 0
}

func (m *PolarisRequest) GetBigTemplateSupport() bool {
	if m != nil {
		return m.BigTemplateSupport
	}
	return false
}

func (m *PolarisRequest) GetIfSupportRewardplus() bool {
	if m != nil {
		return m.IfSupportRewardplus
	}
	return false
}

func (m *PolarisRequest) GetOnlyPlayableCreative() bool {
	if m != nil {
		return m.OnlyPlayableCreative
	}
	return false
}

type RequestRatio struct {
	WRatio               int32    `protobuf:"varint,1,opt,name=w_ratio,json=wRatio,proto3" json:"w_ratio,omitempty"`
	HRatio               int32    `protobuf:"varint,2,opt,name=h_ratio,json=hRatio,proto3" json:"h_ratio,omitempty"`
	WMin                 int32    `protobuf:"varint,3,opt,name=w_min,json=wMin,proto3" json:"w_min,omitempty"`
	WMax                 int32    `protobuf:"varint,4,opt,name=w_max,json=wMax,proto3" json:"w_max,omitempty"`
	HMin                 int32    `protobuf:"varint,5,opt,name=h_min,json=hMin,proto3" json:"h_min,omitempty"`
	HMax                 int32    `protobuf:"varint,6,opt,name=h_max,json=hMax,proto3" json:"h_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestRatio) Reset()         { *m = RequestRatio{} }
func (m *RequestRatio) String() string { return proto.CompactTextString(m) }
func (*RequestRatio) ProtoMessage()    {}
func (*RequestRatio) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{1}
}
func (m *RequestRatio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRatio.Unmarshal(m, b)
}
func (m *RequestRatio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRatio.Marshal(b, m, deterministic)
}
func (dst *RequestRatio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRatio.Merge(dst, src)
}
func (m *RequestRatio) XXX_Size() int {
	return xxx_messageInfo_RequestRatio.Size(m)
}
func (m *RequestRatio) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRatio.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRatio proto.InternalMessageInfo

func (m *RequestRatio) GetWRatio() int32 {
	if m != nil {
		return m.WRatio
	}
	return 0
}

func (m *RequestRatio) GetHRatio() int32 {
	if m != nil {
		return m.HRatio
	}
	return 0
}

func (m *RequestRatio) GetWMin() int32 {
	if m != nil {
		return m.WMin
	}
	return 0
}

func (m *RequestRatio) GetWMax() int32 {
	if m != nil {
		return m.WMax
	}
	return 0
}

func (m *RequestRatio) GetHMin() int32 {
	if m != nil {
		return m.HMin
	}
	return 0
}

func (m *RequestRatio) GetHMax() int32 {
	if m != nil {
		return m.HMax
	}
	return 0
}

type DcoPart struct {
	// 1.dco坑位id
	// [AS ]: 1) rs.thrift - Part - 1 - partId
	// [DSP]: 1)
	PartId int64 `protobuf:"varint,1,opt,name=part_id,json=partId,proto3" json:"part_id,omitempty"`
	// 2.dco候选元素list
	// [AS ]: 1) rs.thrift - Part - 1 - resIds
	ResIdList            []int64  `protobuf:"varint,2,rep,packed,name=res_id_list,json=resIdList,proto3" json:"res_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DcoPart) Reset()         { *m = DcoPart{} }
func (m *DcoPart) String() string { return proto.CompactTextString(m) }
func (*DcoPart) ProtoMessage()    {}
func (*DcoPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{2}
}
func (m *DcoPart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DcoPart.Unmarshal(m, b)
}
func (m *DcoPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DcoPart.Marshal(b, m, deterministic)
}
func (dst *DcoPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DcoPart.Merge(dst, src)
}
func (m *DcoPart) XXX_Size() int {
	return xxx_messageInfo_DcoPart.Size(m)
}
func (m *DcoPart) XXX_DiscardUnknown() {
	xxx_messageInfo_DcoPart.DiscardUnknown(m)
}

var xxx_messageInfo_DcoPart proto.InternalMessageInfo

func (m *DcoPart) GetPartId() int64 {
	if m != nil {
		return m.PartId
	}
	return 0
}

func (m *DcoPart) GetResIdList() []int64 {
	if m != nil {
		return m.ResIdList
	}
	return nil
}

// 【1】sizes、format_sizes、banner_ratio
// （规则1）按照请求的banner.w/h或banner.format.w/h匹配同尺寸的素材，或按照banner.format.wratio/hratio/wmin匹配同比例的素材
// 【2】ratio
// （规则1）召回ratio与该字段的字段值匹配的素材
// 【3】mimes
// （规则1）根据banner.mimes字段值召回同mimes的素材
// 【4】battr
// （规则1）根据banner.battr字段值过滤同attribute的素材
type RequestBanner struct {
	// 1. 展示广告的尺寸，以像素为单位。[w]x[h],如320x50，rtbReq.Imp[0].Video/banner/native.w、h
	// [AS ]: 1) 上游协议参数，unit size
	// [DSP]: 1) RTB标准字段组合。size = [w]x[h]
	Sizes []string `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
	// 2. [w]x[h],如320x50，w=bidRequest.imp.banner.format.w, h=bidRequest.imp.banner.format.h
	// [DSP]: 1) RTB标准字段组合。size = [w]x[h]
	FormatSizes []string `protobuf:"bytes,2,rep,name=format_sizes,json=formatSizes,proto3" json:"format_sizes,omitempty"`
	// 3. rtbReq.Imp[0].banner.format.wratio/hratio/wmin
	// [DSP]: 1) RTB标准字段
	BannerRatio []*RequestRatio `protobuf:"bytes,3,rep,name=banner_ratio,json=bannerRatio,proto3" json:"banner_ratio,omitempty"`
	// 4. 非RTB字段。计算[w]/[h]
	// [AS ]: 1) [w]/[h], size = [w]x[h]
	// [DSP]: 1) 非RTB字段。[w]/[h]
	Ratio []float32 `protobuf:"fixed32,4,rep,packed,name=ratio,proto3" json:"ratio,omitempty"`
	// 5. 支持的内容mime-type. 常用的mime-type包括application/x-shockwave-flash, image/jpg以及 image/gif.
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	Mimes []string `protobuf:"bytes,5,rep,name=mimes,proto3" json:"mimes,omitempty"`
	// 6. 限制的物料属性，
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	BAttr []int32 `protobuf:"varint,6,rep,packed,name=b_attr,json=bAttr,proto3" json:"b_attr,omitempty"`
	// 7. 限制的banner类型
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	BType []int32 `protobuf:"varint,7,rep,packed,name=b_type,json=bType,proto3" json:"b_type,omitempty"`
	// 8. 本次展示支持的API框架列表，如果一个API没有被显式在列表中指明，则表示不支持
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	Api []int32 `protobuf:"varint,8,rep,packed,name=api,proto3" json:"api,omitempty"`
	// 9. 请求广告位 横竖屏
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) mintegral RTB扩展字段
	Orientation          int32    `protobuf:"varint,9,opt,name=orientation,proto3" json:"orientation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBanner) Reset()         { *m = RequestBanner{} }
func (m *RequestBanner) String() string { return proto.CompactTextString(m) }
func (*RequestBanner) ProtoMessage()    {}
func (*RequestBanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{3}
}
func (m *RequestBanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBanner.Unmarshal(m, b)
}
func (m *RequestBanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBanner.Marshal(b, m, deterministic)
}
func (dst *RequestBanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBanner.Merge(dst, src)
}
func (m *RequestBanner) XXX_Size() int {
	return xxx_messageInfo_RequestBanner.Size(m)
}
func (m *RequestBanner) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBanner.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBanner proto.InternalMessageInfo

func (m *RequestBanner) GetSizes() []string {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *RequestBanner) GetFormatSizes() []string {
	if m != nil {
		return m.FormatSizes
	}
	return nil
}

func (m *RequestBanner) GetBannerRatio() []*RequestRatio {
	if m != nil {
		return m.BannerRatio
	}
	return nil
}

func (m *RequestBanner) GetRatio() []float32 {
	if m != nil {
		return m.Ratio
	}
	return nil
}

func (m *RequestBanner) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

func (m *RequestBanner) GetBAttr() []int32 {
	if m != nil {
		return m.BAttr
	}
	return nil
}

func (m *RequestBanner) GetBType() []int32 {
	if m != nil {
		return m.BType
	}
	return nil
}

func (m *RequestBanner) GetApi() []int32 {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *RequestBanner) GetOrientation() int32 {
	if m != nil {
		return m.Orientation
	}
	return 0
}

// bidRequest.imp.native.request反序列化后的结构，较特殊，参考Native Ad规范
// 【1】image_size
// （规则1）图片按照请求的native object的 img.w/h严格匹配
// 【2】video_size、video_orientation
// （规则1）视频按照请求的native object的video.w/h严格匹配，或者按照orientation匹配同横竖屏视频
// 【3】image_mimes
// （规则1）图片根据imageMimes字段值召回同mimes的素材
// 【4】video_mimes
// （规则1）视频根据videoMimes字段值召回同mimes的素材
type RequestNative struct {
	// 1. bidRequest.imp.native.request反序列化后得到w,h。[w]x[h]
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	ImageSize []string `protobuf:"bytes,1,rep,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`
	// 2. 支持的内容mime-type. 常用的mime-type包括application/x-shockwave-flash, image/jpg以及 image/gif.
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	ImageMimes []string `protobuf:"bytes,2,rep,name=image_mimes,json=imageMimes,proto3" json:"image_mimes,omitempty"`
	// 3. bidRequest.imp.native.request反序列化后得到w,h。[w]x[h]
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	VideoSize []string `protobuf:"bytes,3,rep,name=video_size,json=videoSize,proto3" json:"video_size,omitempty"`
	// 4. 视频的方向要求。值为1是竖屏，值为2是横屏
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	VideoOrientation int32 `protobuf:"varint,4,opt,name=video_orientation,json=videoOrientation,proto3" json:"video_orientation,omitempty"`
	// 5. 支持的内容mime-type. 常用的mime-type包括application/x-shockwave-flash, image/jpg以及 image/gif.
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	VideoMimes []string `protobuf:"bytes,5,rep,name=video_mimes,json=videoMimes,proto3" json:"video_mimes,omitempty"`
	// 6. 本次展示支持的API框架列表，如果一个API没有被显式在列表中指明，则表示不支持
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	Api []int32 `protobuf:"varint,6,rep,packed,name=api,proto3" json:"api,omitempty"`
	// 7. 限制的物料属性，
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	BAttr []int32 `protobuf:"varint,7,rep,packed,name=b_attr,json=bAttr,proto3" json:"b_attr,omitempty"`
	// 8. 展示广告的尺寸，以像素为单位。
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	IconSizes []string `protobuf:"bytes,8,rep,name=icon_sizes,json=iconSizes,proto3" json:"icon_sizes,omitempty"`
	// 9. 展示广告的文本要求
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	TextData             []string `protobuf:"bytes,9,rep,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestNative) Reset()         { *m = RequestNative{} }
func (m *RequestNative) String() string { return proto.CompactTextString(m) }
func (*RequestNative) ProtoMessage()    {}
func (*RequestNative) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{4}
}
func (m *RequestNative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestNative.Unmarshal(m, b)
}
func (m *RequestNative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestNative.Marshal(b, m, deterministic)
}
func (dst *RequestNative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestNative.Merge(dst, src)
}
func (m *RequestNative) XXX_Size() int {
	return xxx_messageInfo_RequestNative.Size(m)
}
func (m *RequestNative) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestNative.DiscardUnknown(m)
}

var xxx_messageInfo_RequestNative proto.InternalMessageInfo

func (m *RequestNative) GetImageSize() []string {
	if m != nil {
		return m.ImageSize
	}
	return nil
}

func (m *RequestNative) GetImageMimes() []string {
	if m != nil {
		return m.ImageMimes
	}
	return nil
}

func (m *RequestNative) GetVideoSize() []string {
	if m != nil {
		return m.VideoSize
	}
	return nil
}

func (m *RequestNative) GetVideoOrientation() int32 {
	if m != nil {
		return m.VideoOrientation
	}
	return 0
}

func (m *RequestNative) GetVideoMimes() []string {
	if m != nil {
		return m.VideoMimes
	}
	return nil
}

func (m *RequestNative) GetApi() []int32 {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *RequestNative) GetBAttr() []int32 {
	if m != nil {
		return m.BAttr
	}
	return nil
}

func (m *RequestNative) GetIconSizes() []string {
	if m != nil {
		return m.IconSizes
	}
	return nil
}

func (m *RequestNative) GetTextData() []string {
	if m != nil {
		return m.TextData
	}
	return nil
}

type NativeRequestData struct {
	// 1. 该element是展示必要的元素
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	Required int32 `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	// 2. 展示text的类型
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段，参考native 7.3
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// 3. 展示text的最大长度，为0默认不限制长度
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	Len                  int32    `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NativeRequestData) Reset()         { *m = NativeRequestData{} }
func (m *NativeRequestData) String() string { return proto.CompactTextString(m) }
func (*NativeRequestData) ProtoMessage()    {}
func (*NativeRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{5}
}
func (m *NativeRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NativeRequestData.Unmarshal(m, b)
}
func (m *NativeRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NativeRequestData.Marshal(b, m, deterministic)
}
func (dst *NativeRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeRequestData.Merge(dst, src)
}
func (m *NativeRequestData) XXX_Size() int {
	return xxx_messageInfo_NativeRequestData.Size(m)
}
func (m *NativeRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_NativeRequestData proto.InternalMessageInfo

func (m *NativeRequestData) GetRequired() int32 {
	if m != nil {
		return m.Required
	}
	return 0
}

func (m *NativeRequestData) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NativeRequestData) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

// 【1】size、orientation
// （规则1）根据video.w/h或video.ext.orientation召回视频
// （规则2）默认召回16:9视频
// 【2】max_bitrate、min_bitrate
// （规则1）根据video.maxbidrate和video.minbitrate召回符合范围的视频
// 【3】max_duration、min_duration、max_extended
// （规则1）根据video.maxduration和video.minduration召回符合范围的视频
// 【4】companion_ad、companiontype
// （规则1）按照请求的video.companionad.w/h或video.companionad.format.w/h匹配同尺寸图片，或按照video.companionad.format.wratio/hratio/wmin匹配同比例图片
type RequestVideo struct {
	// 1. [w]x[h],如320x50，w=bidRequest.imp.video.w, h=bidRequest.imp.video.h
	// [DSP]: 1) RTB标准字段
	Size []string `protobuf:"bytes,1,rep,name=size,proto3" json:"size,omitempty"`
	// 2. 视频的方向要求。值为1是竖屏，值为2是横屏
	// [DSP]: 1) RTB标准字段
	Orientation int32 `protobuf:"varint,2,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// 3. 最大的比特率，以Kbps为单位。
	// [DSP]: 1) RTB标准字段
	MaxBitrate int32 `protobuf:"varint,3,opt,name=max_bitrate,json=maxBitrate,proto3" json:"max_bitrate,omitempty"`
	// 4. 最小的比特率，以Kbps为单位。
	// [DSP]: 1) RTB标准字段
	MinBitrate int32 `protobuf:"varint,4,opt,name=min_bitrate,json=minBitrate,proto3" json:"min_bitrate,omitempty"`
	// 5. 视频清晰度要求。1为高清，2为低清
	// [DSP]: 1) RTB标准字段
	Clarity int32 `protobuf:"varint,5,opt,name=clarity,proto3" json:"clarity,omitempty"`
	// 6. 最大的视频长度， 以秒为单位
	// [DSP]: 1) RTB标准字段
	MaxDuration int32 `protobuf:"varint,6,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	// 7. 最小的视频长度， 以秒为单位
	// [DSP]: 1) RTB标准字段
	MinDuration int32 `protobuf:"varint,7,opt,name=min_duration,json=minDuration,proto3" json:"min_duration,omitempty"`
	// 8. 最大的视频广告延长时间长度（如果支持延长）。如果为空或者0，表示不允许延长， 如果为-1，表示允许延时，且没有时间限制， 如果为大于0的数字， 则表示可以延长的时间长度比maxduration大的值
	// [DSP]: 1) RTB标准字段
	MaxExtended int32 `protobuf:"varint,8,opt,name=max_extended,json=maxExtended,proto3" json:"max_extended,omitempty"`
	// 9. 支持的内容mime-type， 常用的类型包括用于windows媒体的video/x-ms-wmv以及用于Flash视频的video/x-flv.
	// [DSP]: 1) RTB标准字段
	Mimes []string `protobuf:"bytes,9,rep,name=mimes,proto3" json:"mimes,omitempty"`
	// 10. 限制的物料属性
	// [DSP]: 1) RTB标准字段
	BAttr []int32 `protobuf:"varint,10,rep,packed,name=b_attr,json=bAttr,proto3" json:"b_attr,omitempty"`
	// 11. 本次展示支持的API框架列表，如果一个API没有被显式在列表中指明，则表示不支持
	// [DSP]: 1) RTB标准字段
	Api []int32 `protobuf:"varint,11,rep,packed,name=api,proto3" json:"api,omitempty"`
	// 12. 如果支持复合广告，表示一组Banner对象
	// [DSP]: 1) RTB标准字段
	CompanionAd []*RequestBanner `protobuf:"bytes,12,rep,name=companion_ad,json=companionAd,proto3" json:"companion_ad,omitempty"`
	// 13. 支持的VAST companion 广告类型，如果在companionad中填充了Banner对象则推荐使用
	// [DSP]: 1) RTB标准字段
	Companiontype        []int32  `protobuf:"varint,13,rep,packed,name=companiontype,proto3" json:"companiontype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVideo) Reset()         { *m = RequestVideo{} }
func (m *RequestVideo) String() string { return proto.CompactTextString(m) }
func (*RequestVideo) ProtoMessage()    {}
func (*RequestVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{6}
}
func (m *RequestVideo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVideo.Unmarshal(m, b)
}
func (m *RequestVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVideo.Marshal(b, m, deterministic)
}
func (dst *RequestVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVideo.Merge(dst, src)
}
func (m *RequestVideo) XXX_Size() int {
	return xxx_messageInfo_RequestVideo.Size(m)
}
func (m *RequestVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVideo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVideo proto.InternalMessageInfo

func (m *RequestVideo) GetSize() []string {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *RequestVideo) GetOrientation() int32 {
	if m != nil {
		return m.Orientation
	}
	return 0
}

func (m *RequestVideo) GetMaxBitrate() int32 {
	if m != nil {
		return m.MaxBitrate
	}
	return 0
}

func (m *RequestVideo) GetMinBitrate() int32 {
	if m != nil {
		return m.MinBitrate
	}
	return 0
}

func (m *RequestVideo) GetClarity() int32 {
	if m != nil {
		return m.Clarity
	}
	return 0
}

func (m *RequestVideo) GetMaxDuration() int32 {
	if m != nil {
		return m.MaxDuration
	}
	return 0
}

func (m *RequestVideo) GetMinDuration() int32 {
	if m != nil {
		return m.MinDuration
	}
	return 0
}

func (m *RequestVideo) GetMaxExtended() int32 {
	if m != nil {
		return m.MaxExtended
	}
	return 0
}

func (m *RequestVideo) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

func (m *RequestVideo) GetBAttr() []int32 {
	if m != nil {
		return m.BAttr
	}
	return nil
}

func (m *RequestVideo) GetApi() []int32 {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *RequestVideo) GetCompanionAd() []*RequestBanner {
	if m != nil {
		return m.CompanionAd
	}
	return nil
}

func (m *RequestVideo) GetCompaniontype() []int32 {
	if m != nil {
		return m.Companiontype
	}
	return nil
}

type RequestDevice struct {
	// 1. 设备操作系统， 例如 “ios"
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段。bidRequest.device.os
	Os int32 `protobuf:"varint,1,opt,name=os,proto3" json:"os,omitempty"`
	// 2. 设备操作系统版本号， 例如 “3.1.2”
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) bidRequest.device.osv
	Osv string `protobuf:"bytes,2,opt,name=osv,proto3" json:"osv,omitempty"`
	// 3. 网络连接类型
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段。bidRequest.device.connectiontype
	NetworkTypeAs int32 `protobuf:"varint,3,opt,name=network_type_as,json=networkTypeAs,proto3" json:"network_type_as,omitempty"`
	// 4. 用户当前地理位置, 设备位置
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段。bidRequest.device.geo.country
	Country string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	// 5. 低版本设备标志
	// [AS ]: 1) 上游协议参数
	LowDevice bool `protobuf:"varint,5,opt,name=low_device,json=lowDevice,proto3" json:"low_device,omitempty"`
	// 6.
	// [AS ]: 1) 上游协议参数
	ApiVersion int32 `protobuf:"varint,6,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// 7.
	// [AS ]: 1) 上游协议参数
	SdkVersion string `protobuf:"bytes,7,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// 8. RTB标准字段。bidRequest.app.id
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	AppId int64 `protobuf:"varint,8,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 9. RTB标准字段。bidRequest.app.bundle
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段
	AppBundle string `protobuf:"bytes,9,opt,name=app_bundle,json=appBundle,proto3" json:"app_bundle,omitempty"`
	// 10.
	// [AS ]: 1) 上游协议参数
	UnitId int64 `protobuf:"varint,10,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	// 11. 展示广告的媒体的发布者交易特定的发布者标识
	// [AS ]: 1) 上游协议参数
	// [DSP]: 1) RTB标准字段。bidRequest.app.publisher.id
	PublisherId int64 `protobuf:"varint,11,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	// 12. MinSWPercent,companion屏幕尺寸的最小宽度比例
	// [DSP]: 1) 非RTB字段
	MinScreenWidthPercent int32 `protobuf:"varint,12,opt,name=min_screen_width_percent,json=minScreenWidthPercent,proto3" json:"min_screen_width_percent,omitempty"`
	// 13. MaxSWPercent,companion屏幕尺寸的最大宽度比例
	// [DSP]: 1) 非RTB字段
	MaxScreenWidthPercent int32 `protobuf:"varint,13,opt,name=max_screen_width_percent,json=maxScreenWidthPercent,proto3" json:"max_screen_width_percent,omitempty"`
	// 14. MaxSHPercent,companion屏幕尺寸的最大高度比例
	// [DSP]: 1) 非RTB字段
	MaxScreenHeightPercent int32 `protobuf:"varint,14,opt,name=max_screen_height_percent,json=maxScreenHeightPercent,proto3" json:"max_screen_height_percent,omitempty"`
	// 15. MinSHPercent,companion屏幕尺寸的最小高度比例
	// [DSP]: 1) 非RTB字段
	MinScreenHeightPercent int32    `protobuf:"varint,15,opt,name=min_screen_height_percent,json=minScreenHeightPercent,proto3" json:"min_screen_height_percent,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *RequestDevice) Reset()         { *m = RequestDevice{} }
func (m *RequestDevice) String() string { return proto.CompactTextString(m) }
func (*RequestDevice) ProtoMessage()    {}
func (*RequestDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{7}
}
func (m *RequestDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDevice.Unmarshal(m, b)
}
func (m *RequestDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDevice.Marshal(b, m, deterministic)
}
func (dst *RequestDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDevice.Merge(dst, src)
}
func (m *RequestDevice) XXX_Size() int {
	return xxx_messageInfo_RequestDevice.Size(m)
}
func (m *RequestDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDevice.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDevice proto.InternalMessageInfo

func (m *RequestDevice) GetOs() int32 {
	if m != nil {
		return m.Os
	}
	return 0
}

func (m *RequestDevice) GetOsv() string {
	if m != nil {
		return m.Osv
	}
	return ""
}

func (m *RequestDevice) GetNetworkTypeAs() int32 {
	if m != nil {
		return m.NetworkTypeAs
	}
	return 0
}

func (m *RequestDevice) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *RequestDevice) GetLowDevice() bool {
	if m != nil {
		return m.LowDevice
	}
	return false
}

func (m *RequestDevice) GetApiVersion() int32 {
	if m != nil {
		return m.ApiVersion
	}
	return 0
}

func (m *RequestDevice) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *RequestDevice) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *RequestDevice) GetAppBundle() string {
	if m != nil {
		return m.AppBundle
	}
	return ""
}

func (m *RequestDevice) GetUnitId() int64 {
	if m != nil {
		return m.UnitId
	}
	return 0
}

func (m *RequestDevice) GetPublisherId() int64 {
	if m != nil {
		return m.PublisherId
	}
	return 0
}

func (m *RequestDevice) GetMinScreenWidthPercent() int32 {
	if m != nil {
		return m.MinScreenWidthPercent
	}
	return 0
}

func (m *RequestDevice) GetMaxScreenWidthPercent() int32 {
	if m != nil {
		return m.MaxScreenWidthPercent
	}
	return 0
}

func (m *RequestDevice) GetMaxScreenHeightPercent() int32 {
	if m != nil {
		return m.MaxScreenHeightPercent
	}
	return 0
}

func (m *RequestDevice) GetMinScreenHeightPercent() int32 {
	if m != nil {
		return m.MinScreenHeightPercent
	}
	return 0
}

type RequestExt struct {
	// 1. DonotSupportDynamicDyImage是否不支持动态图片
	// [DSP]: 1) 非RTB字段
	ForbidDynamicImage bool `protobuf:"varint,1,opt,name=forbid_dynamic_image,json=forbidDynamicImage,proto3" json:"forbid_dynamic_image,omitempty"`
	// 2. NeedAdvAudit,是否需要广告主审核
	// [DSP]: 1) 非RTB字段
	NeedAdvAudit bool `protobuf:"varint,2,opt,name=need_adv_audit,json=needAdvAudit,proto3" json:"need_adv_audit,omitempty"`
	// 3. NeedCreativeAudit,是否需要素材审核
	// [DSP]: 1) 非RTB字段
	NeedCreativeAudit bool `protobuf:"varint,3,opt,name=need_creative_audit,json=needCreativeAudit,proto3" json:"need_creative_audit,omitempty"`
	// 4. 是否需要行业审核
	// [DSP]: 1) 非RTB字段, BlockAuditIndustyIds
	BIndustyIdAudit []string `protobuf:"bytes,4,rep,name=b_industy_id_audit,json=bIndustyIdAudit,proto3" json:"b_industy_id_audit,omitempty"`
	// 5.
	// [DSP]: 1) RTB非标字段, BlockAuditAttribute
	BAttrAudit string `protobuf:"bytes,5,opt,name=b_attr_audit,json=bAttrAudit,proto3" json:"b_attr_audit,omitempty"`
	// 6. BlackKeyWords关键字黑名单，目前腾讯使用
	// [DSP]: 1) RTB非标字段, BlackKeyWords
	BlackKeywords        []string `protobuf:"bytes,6,rep,name=black_keywords,json=blackKeywords,proto3" json:"black_keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestExt) Reset()         { *m = RequestExt{} }
func (m *RequestExt) String() string { return proto.CompactTextString(m) }
func (*RequestExt) ProtoMessage()    {}
func (*RequestExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{8}
}
func (m *RequestExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestExt.Unmarshal(m, b)
}
func (m *RequestExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestExt.Marshal(b, m, deterministic)
}
func (dst *RequestExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestExt.Merge(dst, src)
}
func (m *RequestExt) XXX_Size() int {
	return xxx_messageInfo_RequestExt.Size(m)
}
func (m *RequestExt) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestExt.DiscardUnknown(m)
}

var xxx_messageInfo_RequestExt proto.InternalMessageInfo

func (m *RequestExt) GetForbidDynamicImage() bool {
	if m != nil {
		return m.ForbidDynamicImage
	}
	return false
}

func (m *RequestExt) GetNeedAdvAudit() bool {
	if m != nil {
		return m.NeedAdvAudit
	}
	return false
}

func (m *RequestExt) GetNeedCreativeAudit() bool {
	if m != nil {
		return m.NeedCreativeAudit
	}
	return false
}

func (m *RequestExt) GetBIndustyIdAudit() []string {
	if m != nil {
		return m.BIndustyIdAudit
	}
	return nil
}

func (m *RequestExt) GetBAttrAudit() string {
	if m != nil {
		return m.BAttrAudit
	}
	return ""
}

func (m *RequestExt) GetBlackKeywords() []string {
	if m != nil {
		return m.BlackKeywords
	}
	return nil
}

// ***************************** PolarisResponse ********************************
type PolarisResponse struct {
	// 1. 资源请求处理结果状态
	// [AS ]: 1)
	// [DSP]: 1)
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 2. 资源请求处理耗时, 单位：ms
	// [AS ]: 1)
	// [DSP]: 1)
	Time int32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	// 3. 召回的可用大模板以及slot信息
	// [AS ]: 1) rs.thrift - SRankerInput - 201
	BigTemplateList []*BigTemplate `protobuf:"bytes,3,rep,name=big_template_list,json=bigTemplateList,proto3" json:"big_template_list,omitempty"`
	// 4. slot详细信息
	// [AS ]: 1) rs.thrift - SRankerInput - 202
	// [DSP]: 1) 单子信息
	SlotList             []*SlotObj `protobuf:"bytes,4,rep,name=slot_list,json=slotList,proto3" json:"slot_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PolarisResponse) Reset()         { *m = PolarisResponse{} }
func (m *PolarisResponse) String() string { return proto.CompactTextString(m) }
func (*PolarisResponse) ProtoMessage()    {}
func (*PolarisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{9}
}
func (m *PolarisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolarisResponse.Unmarshal(m, b)
}
func (m *PolarisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolarisResponse.Marshal(b, m, deterministic)
}
func (dst *PolarisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolarisResponse.Merge(dst, src)
}
func (m *PolarisResponse) XXX_Size() int {
	return xxx_messageInfo_PolarisResponse.Size(m)
}
func (m *PolarisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PolarisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PolarisResponse proto.InternalMessageInfo

func (m *PolarisResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PolarisResponse) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PolarisResponse) GetBigTemplateList() []*BigTemplate {
	if m != nil {
		return m.BigTemplateList
	}
	return nil
}

func (m *PolarisResponse) GetSlotList() []*SlotObj {
	if m != nil {
		return m.SlotList
	}
	return nil
}

// 在Polaris协议中，<BigTemplate>包含显示广告素材所需的全部信息。Polaris响应可能会提供多个大模版。
type BigTemplate struct {
	// 1. 大模板ID
	// [AS ]: 1) rs.thrift - SBigTemplate - 1
	BigTemplateId int32 `protobuf:"varint,1,opt,name=big_template_id,json=bigTemplateId,proto3" json:"big_template_id,omitempty"`
	// 2. 大模板包含的slot数组
	// [AS ]: 1) rs.thrift - SBigTemplate - 2
	SlotList             []*SlotReference `protobuf:"bytes,2,rep,name=slot_list,json=slotList,proto3" json:"slot_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BigTemplate) Reset()         { *m = BigTemplate{} }
func (m *BigTemplate) String() string { return proto.CompactTextString(m) }
func (*BigTemplate) ProtoMessage()    {}
func (*BigTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{10}
}
func (m *BigTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigTemplate.Unmarshal(m, b)
}
func (m *BigTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigTemplate.Marshal(b, m, deterministic)
}
func (dst *BigTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigTemplate.Merge(dst, src)
}
func (m *BigTemplate) XXX_Size() int {
	return xxx_messageInfo_BigTemplate.Size(m)
}
func (m *BigTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_BigTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_BigTemplate proto.InternalMessageInfo

func (m *BigTemplate) GetBigTemplateId() int32 {
	if m != nil {
		return m.BigTemplateId
	}
	return 0
}

func (m *BigTemplate) GetSlotList() []*SlotReference {
	if m != nil {
		return m.SlotList
	}
	return nil
}

// 在Polaris协议中，<Slot>包含显示广告素材所需的Pod信息和属性信息。Polaris响应大模版中可能会提供多个Slot。
type SlotReference struct {
	// 1. Slot显示位置定义。从0开始
	// [AS ]: 1) rs.thrift - SlotObjReference - 1
	SlotIndex int32 `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	// 2. Slot类型定义
	// [AS ]: 1) rs.thrift - SlotObjReference - 2
	SlotId int32 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// 3. 该类slot是否是该大模板中所必要的
	// [AS ]: 1) rs.thrift - SlotObjReference - 3
	Required             bool     `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotReference) Reset()         { *m = SlotReference{} }
func (m *SlotReference) String() string { return proto.CompactTextString(m) }
func (*SlotReference) ProtoMessage()    {}
func (*SlotReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{11}
}
func (m *SlotReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotReference.Unmarshal(m, b)
}
func (m *SlotReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotReference.Marshal(b, m, deterministic)
}
func (dst *SlotReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotReference.Merge(dst, src)
}
func (m *SlotReference) XXX_Size() int {
	return xxx_messageInfo_SlotReference.Size(m)
}
func (m *SlotReference) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotReference.DiscardUnknown(m)
}

var xxx_messageInfo_SlotReference proto.InternalMessageInfo

func (m *SlotReference) GetSlotIndex() int32 {
	if m != nil {
		return m.SlotIndex
	}
	return 0
}

func (m *SlotReference) GetSlotId() int32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *SlotReference) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

// 在Polaris协议中，<Slot>包含显示广告素材所需的Pod信息和属性信息（单子--模版/素材组）。
type SlotObj struct {
	// 1. 技术侧定义为全局唯一的ID，只用于as和rs交互，外部系统及产品定义中无slotId概念
	// [AS ]: 1) rs.thrift - SlotObj - 1
	SlotId int32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// 2. 召回单子下的模版/素材
	// [AS ]: 1) rs.thrift - SlotObj - 2
	// [DSP]: 1)
	CampaignTemplateList []*CampaignTemplate `protobuf:"bytes,2,rep,name=campaign_template_list,json=campaignTemplateList,proto3" json:"campaign_template_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SlotObj) Reset()         { *m = SlotObj{} }
func (m *SlotObj) String() string { return proto.CompactTextString(m) }
func (*SlotObj) ProtoMessage()    {}
func (*SlotObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{12}
}
func (m *SlotObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotObj.Unmarshal(m, b)
}
func (m *SlotObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotObj.Marshal(b, m, deterministic)
}
func (dst *SlotObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotObj.Merge(dst, src)
}
func (m *SlotObj) XXX_Size() int {
	return xxx_messageInfo_SlotObj.Size(m)
}
func (m *SlotObj) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotObj.DiscardUnknown(m)
}

var xxx_messageInfo_SlotObj proto.InternalMessageInfo

func (m *SlotObj) GetSlotId() int32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *SlotObj) GetCampaignTemplateList() []*CampaignTemplate {
	if m != nil {
		return m.CampaignTemplateList
	}
	return nil
}

// CampaignTemplate...包含一个offer召回的完整的模板信息
type CampaignTemplate struct {
	// 1. offer id
	// [AS ]: 1) rs.thrift - SCampaignDataFromFrame - 1
	// [DSP]: 1)
	CampaignId int64 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	// 2. 把模板组合在templateId的维度上打平,
	// [AS ]: 1) rs.thrift - SCampaignDataFromFrame - 200
	TemplateGroupList []*TemplateTypeGroupInstance `protobuf:"bytes,2,rep,name=template_group_list,json=templateGroupList,proto3" json:"template_group_list,omitempty"`
	// 3. 模板数据，包含模板属性以及召回的素材
	// [AS ]: 1) rs.thrift - SCampaignDataFromFrame - 201
	// [DSP]: 1)
	TemplateList []*TemplateObj `protobuf:"bytes,3,rep,name=template_list,json=templateList,proto3" json:"template_list,omitempty"`
	// 4. 素材数据表
	// [AS ]: 1) rs.thrift - SCampaignDataFromFrame - 203
	// [DSP]: 1)
	CreativeList         []*CreativeAttr `protobuf:"bytes,4,rep,name=creative_list,json=creativeList,proto3" json:"creative_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CampaignTemplate) Reset()         { *m = CampaignTemplate{} }
func (m *CampaignTemplate) String() string { return proto.CompactTextString(m) }
func (*CampaignTemplate) ProtoMessage()    {}
func (*CampaignTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{13}
}
func (m *CampaignTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignTemplate.Unmarshal(m, b)
}
func (m *CampaignTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignTemplate.Marshal(b, m, deterministic)
}
func (dst *CampaignTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignTemplate.Merge(dst, src)
}
func (m *CampaignTemplate) XXX_Size() int {
	return xxx_messageInfo_CampaignTemplate.Size(m)
}
func (m *CampaignTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignTemplate proto.InternalMessageInfo

func (m *CampaignTemplate) GetCampaignId() int64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *CampaignTemplate) GetTemplateGroupList() []*TemplateTypeGroupInstance {
	if m != nil {
		return m.TemplateGroupList
	}
	return nil
}

func (m *CampaignTemplate) GetTemplateList() []*TemplateObj {
	if m != nil {
		return m.TemplateList
	}
	return nil
}

func (m *CampaignTemplate) GetCreativeList() []*CreativeAttr {
	if m != nil {
		return m.CreativeList
	}
	return nil
}

type TemplateTypeGroupInstance struct {
	// 1. 模版组合（为了屏蔽传输链路结点感知业务细节变化，所以枚举类型转成int来透明传输）
	// [AS ]: 1) rs.thrift - TemplateTypeGroupInstance - 1
	TemplateGroup int32 `protobuf:"varint,1,opt,name=template_group,json=templateGroup,proto3" json:"template_group,omitempty"`
	// 2. 模板组合召回的子模版ID
	// [AS ]: 1) rs.thrift - TemplateTypeGroupInstance - 2
	TemplateIdTuple      []int32  `protobuf:"varint,2,rep,packed,name=template_id_tuple,json=templateIdTuple,proto3" json:"template_id_tuple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateTypeGroupInstance) Reset()         { *m = TemplateTypeGroupInstance{} }
func (m *TemplateTypeGroupInstance) String() string { return proto.CompactTextString(m) }
func (*TemplateTypeGroupInstance) ProtoMessage()    {}
func (*TemplateTypeGroupInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{14}
}
func (m *TemplateTypeGroupInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateTypeGroupInstance.Unmarshal(m, b)
}
func (m *TemplateTypeGroupInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateTypeGroupInstance.Marshal(b, m, deterministic)
}
func (dst *TemplateTypeGroupInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateTypeGroupInstance.Merge(dst, src)
}
func (m *TemplateTypeGroupInstance) XXX_Size() int {
	return xxx_messageInfo_TemplateTypeGroupInstance.Size(m)
}
func (m *TemplateTypeGroupInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateTypeGroupInstance.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateTypeGroupInstance proto.InternalMessageInfo

func (m *TemplateTypeGroupInstance) GetTemplateGroup() int32 {
	if m != nil {
		return m.TemplateGroup
	}
	return 0
}

func (m *TemplateTypeGroupInstance) GetTemplateIdTuple() []int32 {
	if m != nil {
		return m.TemplateIdTuple
	}
	return nil
}

// 模版中包含预送审素材和非预送审素材，因二者素材组织层级关系不同，分成两组字段使用
// 预送审逻辑：国内adx召回的素材是送审是组织好的素材组，每个creativeSpec可以召回多个素材组，经算法优选后，仅保留最优的一个。每个素材组中的素材保持完整，算法输入和输出时素材组内容不变。
// 素材索引字段：creative_spec、group_creative_list
// 非预送审逻辑：国外adx召回的是polaris内部定义的模版，每个模版包含多个元素，元素描述了素材的类型和size，任意符合素材类型和size要求的素材都可以作为元素构成模版，算法优选时，仅选出一个模版，模版的每个元素都要有一个素材。
// 素材索引字段：element_list
type TemplateObj struct {
	// 1.
	// [AS ]: 1) rs.thrift - STemplateObj - 1 - templateId
	// [DSP]: 1)
	TemplateId int32 `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// 2.
	// [AS ]: 1) rs.thrift - STemplateObj - 2 - templateType
	TemplateType int32 `protobuf:"varint,2,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"`
	// 3.
	// [AS ]: 1) rs.thrift - STemplateObj - 3 - componentType
	ComponentType int32 `protobuf:"varint,3,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	// 4. 新老协议Mapping逻辑： 参数templateId + 参数apiFramework -> 旧协议templateId
	// [AS ]: 1) rs.thrift - STemplateObj - 4 - apiFramework
	// [DSP]: 1) Response - CrType
	ApiFramework int32 `protobuf:"varint,4,opt,name=api_framework,json=apiFramework,proto3" json:"api_framework,omitempty"`
	// 5. 对应component的展示顺序，数字越小越先展示
	// [AS ]: 1) rs.thrift - STemplateObj - 5 - order
	Order int32 `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	// 6. 横竖屏
	// [AS ]: 1) rs.thrift - STemplateObj - 6 - orientation
	Orientation int32 `protobuf:"varint,6,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// 7. 视频模版的屏幕尺寸（全屏、半屏）
	// [AS ]: 1) rs.thrift - STemplateObj - 7 - videoTemplateScreenSize
	TemplateScreenSize int32 `protobuf:"varint,7,opt,name=template_screen_size,json=templateScreenSize,proto3" json:"template_screen_size,omitempty"`
	// 8. 可点击区域
	// [AS ]: 1) rs.thrift - STemplateObj - 8 - clickArea
	ClickArea []int32 `protobuf:"varint,8,rep,packed,name=click_area,json=clickArea,proto3" json:"click_area,omitempty"`
	// 9. 模板元素候选的素材
	// [AS ]: 1) rs.thrift - STemplateObj - 9 - elementList
	// [DSP]: 1)
	ElementList []*TemplateElement `protobuf:"bytes,9,rep,name=element_list,json=elementList,proto3" json:"element_list,omitempty"`
	// 10. 国内adx请求广告位
	// [DSP]: 1)
	CreativeSpec string `protobuf:"bytes,10,opt,name=creative_spec,json=creativeSpec,proto3" json:"creative_spec,omitempty"`
	// 11. 国内adx广告位召回的素材组
	// [DSP]: 1)
	GroupCreativeList    []*GroupCreative `protobuf:"bytes,11,rep,name=group_creative_list,json=groupCreativeList,proto3" json:"group_creative_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TemplateObj) Reset()         { *m = TemplateObj{} }
func (m *TemplateObj) String() string { return proto.CompactTextString(m) }
func (*TemplateObj) ProtoMessage()    {}
func (*TemplateObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{15}
}
func (m *TemplateObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateObj.Unmarshal(m, b)
}
func (m *TemplateObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateObj.Marshal(b, m, deterministic)
}
func (dst *TemplateObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateObj.Merge(dst, src)
}
func (m *TemplateObj) XXX_Size() int {
	return xxx_messageInfo_TemplateObj.Size(m)
}
func (m *TemplateObj) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateObj.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateObj proto.InternalMessageInfo

func (m *TemplateObj) GetTemplateId() int32 {
	if m != nil {
		return m.TemplateId
	}
	return 0
}

func (m *TemplateObj) GetTemplateType() int32 {
	if m != nil {
		return m.TemplateType
	}
	return 0
}

func (m *TemplateObj) GetComponentType() int32 {
	if m != nil {
		return m.ComponentType
	}
	return 0
}

func (m *TemplateObj) GetApiFramework() int32 {
	if m != nil {
		return m.ApiFramework
	}
	return 0
}

func (m *TemplateObj) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *TemplateObj) GetOrientation() int32 {
	if m != nil {
		return m.Orientation
	}
	return 0
}

func (m *TemplateObj) GetTemplateScreenSize() int32 {
	if m != nil {
		return m.TemplateScreenSize
	}
	return 0
}

func (m *TemplateObj) GetClickArea() []int32 {
	if m != nil {
		return m.ClickArea
	}
	return nil
}

func (m *TemplateObj) GetElementList() []*TemplateElement {
	if m != nil {
		return m.ElementList
	}
	return nil
}

func (m *TemplateObj) GetCreativeSpec() string {
	if m != nil {
		return m.CreativeSpec
	}
	return ""
}

func (m *TemplateObj) GetGroupCreativeList() []*GroupCreative {
	if m != nil {
		return m.GroupCreativeList
	}
	return nil
}

type TemplateElement struct {
	// 1.
	// [AS ]: 1) rs.thrift - STemplateElement - 1 - elementType
	// [DSP]: 1)
	ElementName string `protobuf:"bytes,1,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`
	// 2. 素材候选集合
	// [AS ]: 1) rs.thrift - STemplateElement - 2 - creativeList
	// [DSP]: 1)
	CreativeIdList       []*ElementCreative `protobuf:"bytes,2,rep,name=creative_id_list,json=creativeIdList,proto3" json:"creative_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TemplateElement) Reset()         { *m = TemplateElement{} }
func (m *TemplateElement) String() string { return proto.CompactTextString(m) }
func (*TemplateElement) ProtoMessage()    {}
func (*TemplateElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{16}
}
func (m *TemplateElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateElement.Unmarshal(m, b)
}
func (m *TemplateElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateElement.Marshal(b, m, deterministic)
}
func (dst *TemplateElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateElement.Merge(dst, src)
}
func (m *TemplateElement) XXX_Size() int {
	return xxx_messageInfo_TemplateElement.Size(m)
}
func (m *TemplateElement) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateElement.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateElement proto.InternalMessageInfo

func (m *TemplateElement) GetElementName() string {
	if m != nil {
		return m.ElementName
	}
	return ""
}

func (m *TemplateElement) GetCreativeIdList() []*ElementCreative {
	if m != nil {
		return m.CreativeIdList
	}
	return nil
}

type GroupCreative struct {
	// 1.素材组ID
	// [DSP]: 1)
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 2. 素材候选集合
	// [DSP]: 1)
	CreativeIdList       []*ElementCreative `protobuf:"bytes,2,rep,name=creative_id_list,json=creativeIdList,proto3" json:"creative_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GroupCreative) Reset()         { *m = GroupCreative{} }
func (m *GroupCreative) String() string { return proto.CompactTextString(m) }
func (*GroupCreative) ProtoMessage()    {}
func (*GroupCreative) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{17}
}
func (m *GroupCreative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupCreative.Unmarshal(m, b)
}
func (m *GroupCreative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupCreative.Marshal(b, m, deterministic)
}
func (dst *GroupCreative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupCreative.Merge(dst, src)
}
func (m *GroupCreative) XXX_Size() int {
	return xxx_messageInfo_GroupCreative.Size(m)
}
func (m *GroupCreative) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupCreative.DiscardUnknown(m)
}

var xxx_messageInfo_GroupCreative proto.InternalMessageInfo

func (m *GroupCreative) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupCreative) GetCreativeIdList() []*ElementCreative {
	if m != nil {
		return m.CreativeIdList
	}
	return nil
}

type ElementCreative struct {
	// 1.
	// [AS ]: 1) rs.thrift - CreativeDesc - 1 - creativeType
	// [DSP]: 1)
	CreativeType int64 `protobuf:"varint,1,opt,name=creative_type,json=creativeType,proto3" json:"creative_type,omitempty"`
	// 2.
	// [AS ]: 1) rs.thrift - CreativeDesc - 2 - creativeId
	CreativeId int64 `protobuf:"varint,2,opt,name=creative_id,json=creativeId,proto3" json:"creative_id,omitempty"`
	// 3.
	// [AS ]: 1) rs.thrift - CreativeDesc - 3 - docId
	// [DSP]
	DocId string `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	// 4.
	// [DSP ]:
	AdnCreativeId int64 `protobuf:"varint,4,opt,name=adn_creative_id,json=adnCreativeId,proto3" json:"adn_creative_id,omitempty"`
	// [DSP]
	FormatType           int32    `protobuf:"varint,5,opt,name=format_type,json=formatType,proto3" json:"format_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElementCreative) Reset()         { *m = ElementCreative{} }
func (m *ElementCreative) String() string { return proto.CompactTextString(m) }
func (*ElementCreative) ProtoMessage()    {}
func (*ElementCreative) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{18}
}
func (m *ElementCreative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElementCreative.Unmarshal(m, b)
}
func (m *ElementCreative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElementCreative.Marshal(b, m, deterministic)
}
func (dst *ElementCreative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElementCreative.Merge(dst, src)
}
func (m *ElementCreative) XXX_Size() int {
	return xxx_messageInfo_ElementCreative.Size(m)
}
func (m *ElementCreative) XXX_DiscardUnknown() {
	xxx_messageInfo_ElementCreative.DiscardUnknown(m)
}

var xxx_messageInfo_ElementCreative proto.InternalMessageInfo

func (m *ElementCreative) GetCreativeType() int64 {
	if m != nil {
		return m.CreativeType
	}
	return 0
}

func (m *ElementCreative) GetCreativeId() int64 {
	if m != nil {
		return m.CreativeId
	}
	return 0
}

func (m *ElementCreative) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func (m *ElementCreative) GetAdnCreativeId() int64 {
	if m != nil {
		return m.AdnCreativeId
	}
	return 0
}

func (m *ElementCreative) GetFormatType() int32 {
	if m != nil {
		return m.FormatType
	}
	return 0
}

type CreativeAttr struct {
	// 1. creative_id
	// [AS ]: 1)
	// [DSP]: 1)
	CreativeId int64 `protobuf:"varint,1,opt,name=creative_id,json=creativeId,proto3" json:"creative_id,omitempty"`
	// 2. sub_creative_id，最内层的creativeId
	// [AS ]: 1) 素材ID, creativeId字段
	// [DSP]: 1) 素材ID, creativeId字段
	SubCreativeId int64 `protobuf:"varint,2,opt,name=sub_creative_id,json=subCreativeId,proto3" json:"sub_creative_id,omitempty"`
	// 3.
	// [AS ]: 1) rs.thrift - CreativeAttr - 9
	// [DSP]: 1)
	Resolution string `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	// 4.
	// [AS ]: 1) rs.thrift - CreativeAttr - 11
	// [DSP]: 1)
	VideoResolution string `protobuf:"bytes,4,opt,name=video_resolution,json=videoResolution,proto3" json:"video_resolution,omitempty"`
	// 5.
	// [AS ]: 1) rs.thrift - CreativeAttr - 10
	// [DSP]: 1)
	VideoLength string `protobuf:"bytes,5,opt,name=video_length,json=videoLength,proto3" json:"video_length,omitempty"`
	// 6.
	// [AS ]: 1) rs.thrift - CreativeAttr - 5
	// [DSP]: 1)
	Width int32 `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	// 7.
	// [AS ]: 1) rs.thrift - CreativeAttr - 4
	// [DSP]: 1)
	Height int32 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	// 8.
	// [AS ]: 1) rs.thrift - CreativeAttr - 1
	// [DSP]: 1)
	Bitrate int32 `protobuf:"varint,8,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// 9.
	// [AS ]: 1) rs.thrift - CreativeAttr - 12
	// [DSP]: 1)
	VideoSize string `protobuf:"bytes,9,opt,name=video_size,json=videoSize,proto3" json:"video_size,omitempty"`
	// 10.
	// [AS ]: 1) rs.thrift - CreativeAttr - 7
	// [DSP]: 1)
	Orientation int32 `protobuf:"varint,10,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// 11.
	// [AS ]: 1) rs.thrift - CreativeAttr - 6
	MinOs int64 `protobuf:"varint,11,opt,name=minOs,proto3" json:"minOs,omitempty"`
	// 12.
	// [AS ]: 1) rs.thrift - CreativeAttr - 21
	Platform int32 `protobuf:"varint,12,opt,name=platform,proto3" json:"platform,omitempty"`
	// 13.
	// [AS ]: 1) rs.thrift - CreativeAttr - 13
	// [DSP]: 1)
	Fmd5 string `protobuf:"bytes,13,opt,name=fmd5,proto3" json:"fmd5,omitempty"`
	// 14. 素材来源，1是creativeInfo表上的campaign+CC或者packageName+CC维度素材，如果非1为其他来源，比如来自campaignInfo对象上的素材
	// [AS ]: 1)
	// [DSP]: 1)
	Source int32 `protobuf:"varint,14,opt,name=source,proto3" json:"source,omitempty"`
	// 15.
	// [AS ]: 1) rs.thrift - CreativeAttr - 15
	// [DSP]: 1)
	Ctime int64 `protobuf:"varint,15,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 16.
	// [AS ]: 1) rs.thrift - CreativeAttr - 16
	// [DSP]: 1)
	Utime int64 `protobuf:"varint,16,opt,name=utime,proto3" json:"utime,omitempty"`
	// 17.对应creative_package.cpId，表示该素材所属的素材包id， 如dco包，abtest包
	// [AS ]: 1) rs.thrift - CreativeAttr - 25
	// [DSP]: 1)
	CpId int64 `protobuf:"varint,17,opt,name=cp_id,json=cpId,proto3" json:"cp_id,omitempty"`
	// 18.对应 creative_package.settings.parts
	// [AS ]: 1) rs.thrift - CreativeAttr - 26
	// [DSP]: 1)
	DcoPartList []*DcoPart `protobuf:"bytes,18,rep,name=dco_part_list,json=dcoPartList,proto3" json:"dco_part_list,omitempty"`
	// 19.对应creative_package.packageType，区分素材是作为哪种素材包被召回的，0:普通素材，1:DCO包素材 2:abtest组素材
	CreativePackageType int32 `protobuf:"varint,19,opt,name=creative_package_type,json=creativePackageType,proto3" json:"creative_package_type,omitempty"`
	// 20. 对应creative_package.advCreativeGid，表示广告主素材组id
	AdvCreativeGroupId int64 `protobuf:"varint,20,opt,name=adv_creative_group_id,json=advCreativeGroupId,proto3" json:"adv_creative_group_id,omitempty"`
	// 21.abtest素材套id
	AbtestTupleId int64 `protobuf:"varint,21,opt,name=abtest_tuple_id,json=abtestTupleId,proto3" json:"abtest_tuple_id,omitempty"`
	// 22.rs做效果特征素材标记
	// [AS ]: 1) rs.thrift - CreativeAttr - 30
	UniqCid int64 `protobuf:"varint,22,opt,name=uniq_cid,json=uniqCid,proto3" json:"uniq_cid,omitempty"`
	// 23.广告主素材Id
	// [AS ]: 1) rs.thrift - CreativeAttr - 20
	AdvCreativeId string `protobuf:"bytes,23,opt,name=adv_creative_id,json=advCreativeId,proto3" json:"adv_creative_id,omitempty"`
	// 24.素材仓库提供dco原始id
	// [AS ]: 1) rs.thrift - CreativeAttr - 28
	WhdcoId              int64    `protobuf:"varint,24,opt,name=whdcoId,proto3" json:"whdcoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreativeAttr) Reset()         { *m = CreativeAttr{} }
func (m *CreativeAttr) String() string { return proto.CompactTextString(m) }
func (*CreativeAttr) ProtoMessage()    {}
func (*CreativeAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_polaris_879154dddea0bbe6, []int{19}
}
func (m *CreativeAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreativeAttr.Unmarshal(m, b)
}
func (m *CreativeAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreativeAttr.Marshal(b, m, deterministic)
}
func (dst *CreativeAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreativeAttr.Merge(dst, src)
}
func (m *CreativeAttr) XXX_Size() int {
	return xxx_messageInfo_CreativeAttr.Size(m)
}
func (m *CreativeAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_CreativeAttr.DiscardUnknown(m)
}

var xxx_messageInfo_CreativeAttr proto.InternalMessageInfo

func (m *CreativeAttr) GetCreativeId() int64 {
	if m != nil {
		return m.CreativeId
	}
	return 0
}

func (m *CreativeAttr) GetSubCreativeId() int64 {
	if m != nil {
		return m.SubCreativeId
	}
	return 0
}

func (m *CreativeAttr) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

func (m *CreativeAttr) GetVideoResolution() string {
	if m != nil {
		return m.VideoResolution
	}
	return ""
}

func (m *CreativeAttr) GetVideoLength() string {
	if m != nil {
		return m.VideoLength
	}
	return ""
}

func (m *CreativeAttr) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CreativeAttr) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CreativeAttr) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *CreativeAttr) GetVideoSize() string {
	if m != nil {
		return m.VideoSize
	}
	return ""
}

func (m *CreativeAttr) GetOrientation() int32 {
	if m != nil {
		return m.Orientation
	}
	return 0
}

func (m *CreativeAttr) GetMinOs() int64 {
	if m != nil {
		return m.MinOs
	}
	return 0
}

func (m *CreativeAttr) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *CreativeAttr) GetFmd5() string {
	if m != nil {
		return m.Fmd5
	}
	return ""
}

func (m *CreativeAttr) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *CreativeAttr) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *CreativeAttr) GetUtime() int64 {
	if m != nil {
		return m.Utime
	}
	return 0
}

func (m *CreativeAttr) GetCpId() int64 {
	if m != nil {
		return m.CpId
	}
	return 0
}

func (m *CreativeAttr) GetDcoPartList() []*DcoPart {
	if m != nil {
		return m.DcoPartList
	}
	return nil
}

func (m *CreativeAttr) GetCreativePackageType() int32 {
	if m != nil {
		return m.CreativePackageType
	}
	return 0
}

func (m *CreativeAttr) GetAdvCreativeGroupId() int64 {
	if m != nil {
		return m.AdvCreativeGroupId
	}
	return 0
}

func (m *CreativeAttr) GetAbtestTupleId() int64 {
	if m != nil {
		return m.AbtestTupleId
	}
	return 0
}

func (m *CreativeAttr) GetUniqCid() int64 {
	if m != nil {
		return m.UniqCid
	}
	return 0
}

func (m *CreativeAttr) GetAdvCreativeId() string {
	if m != nil {
		return m.AdvCreativeId
	}
	return ""
}

func (m *CreativeAttr) GetWhdcoId() int64 {
	if m != nil {
		return m.WhdcoId
	}
	return 0
}

func init() {
	proto.RegisterType((*PolarisRequest)(nil), "polaris.PolarisRequest")
	proto.RegisterMapType((map[string]string)(nil), "polaris.PolarisRequest.AbTestEntry")
	proto.RegisterType((*RequestRatio)(nil), "polaris.RequestRatio")
	proto.RegisterType((*DcoPart)(nil), "polaris.DcoPart")
	proto.RegisterType((*RequestBanner)(nil), "polaris.RequestBanner")
	proto.RegisterType((*RequestNative)(nil), "polaris.RequestNative")
	proto.RegisterType((*NativeRequestData)(nil), "polaris.NativeRequestData")
	proto.RegisterType((*RequestVideo)(nil), "polaris.RequestVideo")
	proto.RegisterType((*RequestDevice)(nil), "polaris.RequestDevice")
	proto.RegisterType((*RequestExt)(nil), "polaris.RequestExt")
	proto.RegisterType((*PolarisResponse)(nil), "polaris.PolarisResponse")
	proto.RegisterType((*BigTemplate)(nil), "polaris.BigTemplate")
	proto.RegisterType((*SlotReference)(nil), "polaris.SlotReference")
	proto.RegisterType((*SlotObj)(nil), "polaris.SlotObj")
	proto.RegisterType((*CampaignTemplate)(nil), "polaris.CampaignTemplate")
	proto.RegisterType((*TemplateTypeGroupInstance)(nil), "polaris.TemplateTypeGroupInstance")
	proto.RegisterType((*TemplateObj)(nil), "polaris.TemplateObj")
	proto.RegisterType((*TemplateElement)(nil), "polaris.TemplateElement")
	proto.RegisterType((*GroupCreative)(nil), "polaris.GroupCreative")
	proto.RegisterType((*ElementCreative)(nil), "polaris.ElementCreative")
	proto.RegisterType((*CreativeAttr)(nil), "polaris.CreativeAttr")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PolarisServiceClient is the client API for PolarisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolarisServiceClient interface {
	GetPolarisResponse(ctx context.Context, in *PolarisRequest, opts ...grpc.CallOption) (*PolarisResponse, error)
}

type polarisServiceClient struct {
	cc *grpc.ClientConn
}

func NewPolarisServiceClient(cc *grpc.ClientConn) PolarisServiceClient {
	return &polarisServiceClient{cc}
}

func (c *polarisServiceClient) GetPolarisResponse(ctx context.Context, in *PolarisRequest, opts ...grpc.CallOption) (*PolarisResponse, error) {
	out := new(PolarisResponse)
	err := c.cc.Invoke(ctx, "/polaris.PolarisService/GetPolarisResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolarisServiceServer is the server API for PolarisService service.
type PolarisServiceServer interface {
	GetPolarisResponse(context.Context, *PolarisRequest) (*PolarisResponse, error)
}

func RegisterPolarisServiceServer(s *grpc.Server, srv PolarisServiceServer) {
	s.RegisterService(&_PolarisService_serviceDesc, srv)
}

func _PolarisService_GetPolarisResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolarisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisServiceServer).GetPolarisResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/polaris.PolarisService/GetPolarisResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisServiceServer).GetPolarisResponse(ctx, req.(*PolarisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolarisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "polaris.PolarisService",
	HandlerType: (*PolarisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolarisResponse",
			Handler:    _PolarisService_GetPolarisResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "polaris/polaris.proto",
}

func init() { proto.RegisterFile("polaris/polaris.proto", fileDescriptor_polaris_879154dddea0bbe6) }

var fileDescriptor_polaris_879154dddea0bbe6 = []byte{
	// 2498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0xff, 0x03, 0x20, 0x5e, 0x0d, 0x80, 0x20, 0x86, 0x0f, 0x2d, 0xe5, 0xb2, 0x0d, 0x43, 0xb6,
	0xff, 0x4c, 0x54, 0xa6, 0x1c, 0xd9, 0xa9, 0x58, 0x4e, 0x0e, 0x21, 0x45, 0x4b, 0x41, 0xc5, 0x7a,
	0xd4, 0x52, 0xb1, 0xab, 0x92, 0xc3, 0xd6, 0xec, 0xce, 0x90, 0x18, 0x13, 0xfb, 0xd0, 0xee, 0x2c,
	0x01, 0xe6, 0x23, 0xe4, 0x92, 0x1c, 0xf2, 0x05, 0x72, 0xcc, 0xc5, 0xd7, 0x7c, 0x8f, 0x7c, 0x99,
	0xdc, 0x52, 0xa9, 0xee, 0x99, 0x5d, 0x2c, 0x40, 0x2a, 0xa7, 0x5c, 0x48, 0x74, 0xf7, 0xaf, 0x67,
	0x7a, 0xfa, 0x35, 0x3d, 0x0b, 0xfb, 0x49, 0x3c, 0xe7, 0xa9, 0xca, 0x1e, 0xd9, 0xff, 0xc7, 0x49,
	0x1a, 0xeb, 0x98, 0xb5, 0x2d, 0x79, 0x7f, 0xe8, 0xf3, 0x4c, 0x3e, 0xc2, 0x3f, 0x46, 0x32, 0xf9,
	0x57, 0x07, 0xb6, 0x5f, 0x1b, 0xa1, 0x2b, 0xdf, 0xe6, 0x32, 0xd3, 0xec, 0x0b, 0xe8, 0x21, 0x20,
	0x35, 0xa4, 0x53, 0x1b, 0xd7, 0x8e, 0x7a, 0x8f, 0x47, 0xc7, 0xa4, 0x74, 0xca, 0x33, 0x69, 0x71,
	0x6e, 0x15, 0xc5, 0xee, 0x43, 0x47, 0x2e, 0x83, 0x19, 0x8f, 0x2e, 0xa5, 0x53, 0x1f, 0xd7, 0x8e,
	0xba, 0x6e, 0x49, 0xb3, 0x43, 0xe8, 0xa8, 0x30, 0xf1, 0xf4, 0x4d, 0x22, 0x9d, 0x06, 0xc9, 0xda,
	0x2a, 0x4c, 0xde, 0xdc, 0x24, 0x92, 0xdd, 0x83, 0x36, 0x17, 0x46, 0xb2, 0x35, 0xae, 0x1d, 0x35,
	0xdd, 0x16, 0x17, 0x15, 0x41, 0x26, 0xb9, 0x76, 0x9a, 0xe3, 0xc6, 0x51, 0x17, 0x05, 0xe7, 0x92,
	0x6b, 0x76, 0x04, 0x3b, 0x01, 0x0f, 0x13, 0xae, 0x2e, 0x23, 0x4f, 0x09, 0x6f, 0xae, 0x32, 0xed,
	0xb4, 0xc6, 0x8d, 0xa3, 0x86, 0xbb, 0x5d, 0xf0, 0xa7, 0xe2, 0x5b, 0x95, 0x69, 0xf6, 0x11, 0xf4,
	0x4b, 0x64, 0xc8, 0x97, 0x4e, 0x9b, 0x36, 0xe8, 0x15, 0xbc, 0x17, 0x7c, 0xc9, 0x8e, 0xa1, 0xe5,
	0xf3, 0x28, 0x92, 0xa9, 0xd3, 0xa1, 0x53, 0x1e, 0x1c, 0x17, 0x7e, 0xb3, 0x87, 0x3c, 0x25, 0xa9,
	0x6b, 0x51, 0x88, 0x8f, 0xb8, 0x56, 0xd7, 0xd2, 0xe9, 0xde, 0x8d, 0x7f, 0x49, 0x52, 0xd7, 0xa2,
	0xd8, 0x43, 0x68, 0x5e, 0x2b, 0x21, 0x63, 0x07, 0x08, 0xbe, 0xbf, 0x09, 0xff, 0x0e, 0x85, 0xae,
	0xc1, 0xe0, 0xe2, 0x42, 0x5e, 0xab, 0x40, 0x3a, 0xbd, 0xbb, 0x17, 0x3f, 0x23, 0xa9, 0x6b, 0x51,
	0x8c, 0xc1, 0x96, 0xc6, 0x73, 0xf5, 0xe9, 0x5c, 0xf4, 0x9b, 0x78, 0x18, 0xb4, 0xc1, 0xb8, 0x76,
	0xd4, 0x71, 0xe9, 0x37, 0xfb, 0x04, 0x1a, 0x72, 0xa9, 0x9d, 0x6d, 0x5a, 0x74, 0x77, 0x73, 0xd1,
	0x6f, 0x96, 0xda, 0x45, 0x39, 0xfb, 0x18, 0xb6, 0xd5, 0x85, 0x97, 0xe5, 0x49, 0x12, 0xa7, 0xda,
	0x13, 0x41, 0xec, 0x0c, 0x69, 0xe1, 0xbe, 0xba, 0x38, 0x37, 0xcc, 0xb3, 0x20, 0x66, 0x0f, 0x61,
	0x14, 0xa4, 0x92, 0x4e, 0xe7, 0x5d, 0x48, 0xae, 0xf3, 0x54, 0x66, 0xce, 0x0e, 0x45, 0x68, 0xa7,
	0x10, 0x3c, 0xb3, 0x7c, 0x76, 0x0c, 0xbb, 0x42, 0xfa, 0xf9, 0xa5, 0xa7, 0x65, 0x98, 0xcc, 0xb9,
	0x96, 0x26, 0x5c, 0xa3, 0x71, 0xe3, 0xa8, 0xe9, 0x8e, 0x48, 0xf4, 0xc6, 0x4a, 0x28, 0x62, 0x47,
	0x30, 0x7c, 0x91, 0xcf, 0xb5, 0x9a, 0x86, 0xfc, 0x52, 0x3e, 0x8d, 0xf3, 0x48, 0x3b, 0x8c, 0x6c,
	0xd8, 0x64, 0xb3, 0x07, 0x30, 0xf0, 0xf3, 0x4c, 0x45, 0x32, 0xcb, 0x4c, 0xf6, 0xec, 0x52, 0x5e,
	0xf5, 0x0b, 0x26, 0xe5, 0xd0, 0xff, 0xc3, 0x50, 0xf3, 0xf4, 0x52, 0xea, 0x72, 0x7f, 0x67, 0x8f,
	0x60, 0xdb, 0x86, 0x5d, 0xec, 0xcd, 0x7e, 0x05, 0x6d, 0xee, 0x7b, 0xe4, 0xb8, 0xfd, 0x71, 0xe3,
	0xa8, 0xf7, 0xf8, 0x41, 0xe9, 0xa5, 0xf5, 0xda, 0x38, 0x3e, 0xf1, 0xdf, 0xa0, 0xcf, 0x22, 0x9d,
	0xde, 0xb8, 0x2d, 0x4e, 0x04, 0xdb, 0x83, 0x26, 0x17, 0x2f, 0xf3, 0xd0, 0x39, 0x20, 0x5b, 0x0d,
	0xc1, 0xc6, 0xd0, 0xb3, 0xb5, 0x81, 0xb6, 0x38, 0xf7, 0x4c, 0xf2, 0x55, 0x58, 0x98, 0xc9, 0x15,
	0x87, 0x2f, 0xa4, 0x7f, 0x39, 0x77, 0x1c, 0x82, 0x6d, 0x97, 0x2e, 0xff, 0x1e, 0xb9, 0xec, 0x18,
	0x98, 0xaf, 0x4a, 0x57, 0x59, 0x91, 0x73, 0x48, 0x31, 0xbe, 0x43, 0xc2, 0x1e, 0xc3, 0x7e, 0x65,
	0xe5, 0x54, 0x2e, 0x78, 0x2a, 0x92, 0x79, 0x9e, 0x39, 0xf7, 0x49, 0x65, 0xb7, 0x5c, 0xde, 0x2d,
	0x45, 0xec, 0x4b, 0x38, 0x88, 0xa3, 0xf9, 0x8d, 0x97, 0xcc, 0xf9, 0x0d, 0xf7, 0xe7, 0xd2, 0x2b,
	0xa2, 0xe9, 0xbc, 0x47, 0x4a, 0x7b, 0x28, 0x7d, 0x6d, 0x85, 0x4f, 0xad, 0xec, 0xfe, 0x13, 0xe8,
	0x55, 0x5c, 0xc2, 0x76, 0xa0, 0x71, 0x25, 0x6f, 0xa8, 0x65, 0x74, 0x5d, 0xfc, 0x89, 0xce, 0xb9,
	0xe6, 0xf3, 0xbc, 0x68, 0x0a, 0x86, 0xf8, 0xba, 0xfe, 0x55, 0x6d, 0xf2, 0xd7, 0x1a, 0xf4, 0x8b,
	0x56, 0xc2, 0xb5, 0x8a, 0xb1, 0xe4, 0x17, 0x5e, 0x8a, 0x3f, 0x69, 0x81, 0xa6, 0xdb, 0x5a, 0x94,
	0x82, 0x99, 0x15, 0xd4, 0x8d, 0x60, 0x66, 0x04, 0xbb, 0xd0, 0x5c, 0x78, 0xa1, 0x8a, 0xa8, 0xab,
	0x34, 0xdd, 0xad, 0xc5, 0x0b, 0x15, 0x59, 0x26, 0x5f, 0xda, 0x86, 0xb2, 0xb5, 0xc0, 0x42, 0xdf,
	0x85, 0xe6, 0x8c, 0x90, 0x4d, 0xc3, 0x9c, 0x59, 0xe4, 0x8c, 0x90, 0xad, 0x82, 0xc9, 0x97, 0x93,
	0x53, 0x68, 0x9f, 0x05, 0xf1, 0x6b, 0x9e, 0x6a, 0xdc, 0x37, 0xe1, 0xa9, 0xf6, 0x94, 0x20, 0x83,
	0x1a, 0x6e, 0x0b, 0xc9, 0xa9, 0x60, 0x1f, 0x60, 0x6c, 0xb3, 0xb2, 0xfd, 0xd4, 0xa9, 0xfd, 0x74,
	0x53, 0x99, 0x99, 0xce, 0x33, 0xf9, 0x4b, 0x1d, 0x06, 0x6b, 0x0d, 0x04, 0xdd, 0x90, 0xa9, 0x3f,
	0xca, 0xcc, 0xa9, 0x51, 0xa9, 0x18, 0x02, 0x3b, 0xd4, 0x45, 0x9c, 0x86, 0x5c, 0x7b, 0x46, 0x58,
	0x27, 0x61, 0xcf, 0xf0, 0xce, 0x09, 0xf2, 0x15, 0xf4, 0x4d, 0xef, 0xb1, 0x0e, 0x68, 0x50, 0x7e,
	0xde, 0x6a, 0x24, 0xe4, 0x0f, 0xec, 0xc8, 0xd4, 0xae, 0xc8, 0x39, 0x7b, 0xd0, 0x34, 0x2a, 0x5b,
	0xe3, 0xc6, 0x51, 0xdd, 0x35, 0x04, 0x72, 0x43, 0x15, 0xca, 0xcc, 0x76, 0x55, 0x43, 0xb0, 0x7d,
	0x68, 0xf9, 0x1e, 0xd7, 0x3a, 0xa5, 0x56, 0xda, 0x74, 0x9b, 0xfe, 0x89, 0xd6, 0xa9, 0x61, 0x53,
	0x79, 0xb5, 0x2d, 0x9b, 0x12, 0x77, 0x07, 0x1a, 0x3c, 0x51, 0x4e, 0x87, 0x78, 0xf8, 0x13, 0x93,
	0x3d, 0x4e, 0x95, 0x8c, 0x34, 0xee, 0x11, 0x51, 0x73, 0x6c, 0xba, 0x55, 0xd6, 0xe4, 0x6f, 0x2b,
	0x97, 0x98, 0x1e, 0xc9, 0xde, 0x07, 0x50, 0x58, 0xd0, 0x74, 0x76, 0xeb, 0x97, 0x2e, 0x71, 0xf0,
	0xe4, 0xec, 0x43, 0xe8, 0x19, 0xb1, 0x31, 0xd7, 0xb8, 0xc6, 0x68, 0xbc, 0x20, 0x9b, 0xdf, 0x07,
	0xa0, 0xbe, 0x69, 0xf4, 0x1b, 0x46, 0x9f, 0x38, 0xa4, 0xff, 0x10, 0x46, 0x46, 0x5c, 0x35, 0xcc,
	0xa4, 0xc4, 0x0e, 0x09, 0x5e, 0xad, 0xf8, 0xb8, 0x99, 0x01, 0x57, 0x7d, 0x63, 0x96, 0x37, 0x9b,
	0xd9, 0x23, 0xb7, 0x56, 0x47, 0x5e, 0xb9, 0xac, 0x5d, 0x75, 0x19, 0x9e, 0x2a, 0x88, 0x23, 0x1b,
	0xd0, 0x8e, 0x3d, 0x55, 0x10, 0x47, 0x26, 0x9c, 0xef, 0x41, 0x57, 0xcb, 0xa5, 0xf6, 0x04, 0xd7,
	0xdc, 0xe9, 0x92, 0xb4, 0x83, 0x8c, 0x33, 0xae, 0xf9, 0xe4, 0x77, 0x30, 0xb2, 0xf7, 0x87, 0xed,
	0xf7, 0x5c, 0x73, 0xbc, 0x58, 0xb1, 0x69, 0xa8, 0x54, 0x0a, 0x5b, 0x16, 0x25, 0x4d, 0xdd, 0x1e,
	0xa3, 0x53, 0xb7, 0x37, 0x80, 0x0d, 0xce, 0x5c, 0x16, 0x15, 0x81, 0x3f, 0x27, 0x7f, 0x6f, 0x94,
	0x85, 0x46, 0xf7, 0x0d, 0xaa, 0x55, 0x7c, 0x4e, 0xbf, 0x37, 0x23, 0x58, 0xbf, 0x15, 0x41, 0xf4,
	0x51, 0xc8, 0x97, 0x9e, 0xaf, 0x74, 0x8a, 0x9d, 0xd4, 0x6c, 0x00, 0x21, 0x5f, 0x9e, 0x1a, 0x0e,
	0x01, 0x54, 0x54, 0x02, 0xb6, 0x2c, 0x40, 0x45, 0x05, 0xc0, 0x81, 0x76, 0x80, 0x59, 0xab, 0x6f,
	0x6c, 0x19, 0x16, 0x24, 0x16, 0x02, 0xae, 0x2d, 0xf2, 0xd4, 0x6c, 0x6f, 0x0a, 0x12, 0xf7, 0x3b,
	0xb3, 0x2c, 0x82, 0xa8, 0x68, 0x05, 0xb1, 0xb7, 0x79, 0xa8, 0xa2, 0x35, 0x08, 0x5f, 0x7a, 0x72,
	0xa9, 0x65, 0x24, 0xa4, 0xa0, 0x3b, 0xdd, 0xac, 0xf2, 0x8d, 0x65, 0xad, 0xd2, 0xbf, 0x7b, 0x77,
	0xfa, 0x43, 0x35, 0x96, 0x36, 0xe8, 0xbd, 0x55, 0xd0, 0x9f, 0x40, 0x3f, 0x88, 0xc3, 0x84, 0x47,
	0x2a, 0x8e, 0x3c, 0x2e, 0x9c, 0x3e, 0x55, 0xe3, 0xbb, 0xa6, 0x86, 0x5e, 0x89, 0x3d, 0x11, 0xec,
	0x63, 0x18, 0x94, 0x24, 0x05, 0x6d, 0x40, 0xcb, 0xae, 0x33, 0x27, 0x3f, 0x6e, 0x95, 0x65, 0x62,
	0x6e, 0x7b, 0xb6, 0x0d, 0xf5, 0x38, 0xb3, 0x91, 0xaf, 0xc7, 0x94, 0x89, 0x71, 0x76, 0x6d, 0xdb,
	0x29, 0xfe, 0x64, 0x9f, 0xc2, 0x30, 0x92, 0x7a, 0x11, 0xa7, 0x57, 0x54, 0xab, 0x1e, 0xcf, 0x6c,
	0x70, 0x06, 0x96, 0x8d, 0x45, 0x7b, 0x92, 0x91, 0xfb, 0xf1, 0xf2, 0x4c, 0x6f, 0x28, 0x36, 0x5d,
	0xb7, 0x20, 0x31, 0x69, 0xe7, 0xf1, 0xc2, 0xb3, 0xd3, 0x47, 0x93, 0xfa, 0x7d, 0x77, 0x1e, 0x2f,
	0xac, 0x09, 0x1f, 0x42, 0x8f, 0x27, 0xca, 0xbb, 0x96, 0x69, 0xb6, 0x0a, 0x0e, 0xf0, 0x44, 0x7d,
	0x67, 0x38, 0x08, 0xc8, 0xc4, 0x55, 0x09, 0x68, 0xd3, 0xea, 0x90, 0x89, 0xab, 0x02, 0xb0, 0x0f,
	0x2d, 0x9e, 0x24, 0xd8, 0x48, 0x3b, 0xd4, 0x48, 0x9b, 0x3c, 0x49, 0xa6, 0x02, 0xf7, 0x45, 0xb6,
	0x9f, 0x47, 0x62, 0x6e, 0x46, 0xaa, 0xae, 0xdb, 0xe5, 0x49, 0x72, 0x4a, 0x0c, 0xec, 0xbf, 0x79,
	0xa4, 0xa8, 0xff, 0x82, 0xe9, 0xbf, 0x48, 0x4e, 0x05, 0x06, 0x3a, 0xc9, 0xfd, 0xb9, 0xca, 0x66,
	0x32, 0x45, 0x69, 0x8f, 0xa4, 0xbd, 0x92, 0x37, 0x15, 0xec, 0x17, 0xe0, 0x60, 0xba, 0x64, 0x41,
	0x2a, 0x65, 0xe4, 0x2d, 0x94, 0xd0, 0x33, 0x2f, 0x91, 0x69, 0x20, 0x23, 0x6d, 0x07, 0xa6, 0xfd,
	0x50, 0x45, 0xe7, 0x24, 0xfe, 0x1e, 0xa5, 0xaf, 0x8d, 0x90, 0x14, 0xf9, 0xf2, 0x6e, 0xc5, 0x81,
	0x55, 0xe4, 0xcb, 0x3b, 0x14, 0x9f, 0xc0, 0x61, 0x45, 0x71, 0x26, 0xd5, 0xe5, 0x4c, 0x97, 0x9a,
	0xdb, 0xa4, 0x79, 0x50, 0x6a, 0xfe, 0x86, 0xc4, 0x55, 0xd5, 0x95, 0xb1, 0x1b, 0xaa, 0x43, 0xab,
	0x5a, 0x58, 0xbb, 0xa6, 0x3a, 0xf9, 0x53, 0x1d, 0x60, 0x35, 0xc9, 0xb1, 0xcf, 0x61, 0xef, 0x22,
	0x4e, 0x7d, 0x25, 0x3c, 0x71, 0x13, 0xf1, 0x50, 0x05, 0x1e, 0x75, 0x4c, 0xca, 0x9f, 0x8e, 0xcb,
	0x8c, 0xec, 0xcc, 0x88, 0x68, 0x9c, 0xc2, 0xb1, 0x2f, 0x92, 0x52, 0x78, 0x5c, 0x5c, 0x7b, 0x3c,
	0x17, 0x4a, 0x53, 0x6a, 0x75, 0xdc, 0x3e, 0x72, 0x4f, 0xc4, 0xf5, 0x09, 0xf2, 0x70, 0x92, 0x23,
	0x54, 0x39, 0xfb, 0x19, 0x68, 0x83, 0xa0, 0x23, 0x14, 0x15, 0x23, 0x81, 0xc1, 0x3f, 0x04, 0xe6,
	0x7b, 0x2a, 0x12, 0x79, 0xa6, 0x6f, 0xf0, 0x9e, 0x34, 0xf0, 0x2d, 0x2a, 0xba, 0xa1, 0x3f, 0x35,
	0x82, 0xa9, 0x30, 0xe0, 0x31, 0xf4, 0x4d, 0xf9, 0x59, 0x58, 0xd3, 0xe4, 0x0f, 0x15, 0xa1, 0x41,
	0x7c, 0x02, 0xdb, 0xfe, 0x9c, 0x07, 0x57, 0xde, 0x95, 0xbc, 0x59, 0xc4, 0xa9, 0xc8, 0xa8, 0x13,
	0x77, 0xdd, 0x01, 0x71, 0x7f, 0x6b, 0x99, 0x93, 0x1f, 0x6b, 0x30, 0x2c, 0x07, 0xb6, 0x2c, 0x89,
	0xa3, 0x4c, 0xb2, 0x03, 0x68, 0x65, 0x9a, 0xeb, 0xbc, 0xa8, 0x21, 0x4b, 0x51, 0xef, 0x54, 0xe1,
	0xaa, 0x77, 0xaa, 0x50, 0xb2, 0x5f, 0xc3, 0xc8, 0x57, 0x9b, 0xd3, 0xaa, 0xb9, 0x71, 0xf7, 0xca,
	0x1a, 0x3f, 0x5d, 0xcd, 0x5b, 0xee, 0xb0, 0x32, 0x7c, 0xd1, 0x04, 0xfb, 0x19, 0x74, 0xb3, 0x79,
	0xac, 0x8d, 0xe6, 0x16, 0x69, 0xee, 0x94, 0x9a, 0xe7, 0xf3, 0x58, 0xbf, 0xf2, 0x7f, 0x70, 0x3b,
	0x08, 0xa1, 0x41, 0xe1, 0x07, 0xe8, 0x55, 0x96, 0xc3, 0x4a, 0x5e, 0xdb, 0x5f, 0x15, 0x2d, 0x7f,
	0x50, 0xd9, 0x67, 0x2a, 0xd8, 0x17, 0xd5, 0x5d, 0xea, 0x1b, 0x3d, 0x08, 0x77, 0x71, 0xe5, 0x85,
	0x4c, 0x65, 0x14, 0xc8, 0xca, 0x5e, 0x01, 0x0c, 0xd6, 0x44, 0x58, 0x7d, 0xb4, 0x8a, 0x8a, 0x84,
	0x5c, 0xda, 0x8d, 0x68, 0xdd, 0x29, 0x32, 0xb0, 0xfa, 0x8c, 0x58, 0x14, 0x53, 0x17, 0xc9, 0xc4,
	0xda, 0x8d, 0x64, 0x12, 0xa0, 0xa4, 0x27, 0x19, 0xb4, 0xed, 0x29, 0xab, 0xfa, 0xb5, 0x35, 0xfd,
	0x57, 0x70, 0x50, 0xbe, 0xcb, 0xd6, 0x5d, 0x6d, 0x8e, 0x72, 0x58, 0x1e, 0xe5, 0xa9, 0x85, 0x95,
	0xfe, 0xde, 0x0b, 0x36, 0x38, 0x74, 0xb2, 0x7f, 0xd7, 0x60, 0x67, 0x13, 0x8a, 0x3d, 0xa9, 0xf2,
	0x4e, 0xb4, 0x03, 0x1c, 0xac, 0x9e, 0x88, 0xcc, 0x85, 0xdd, 0x72, 0xf7, 0xcb, 0x34, 0xce, 0x93,
	0xaa, 0x0d, 0x93, 0xd2, 0x86, 0x62, 0x41, 0x6c, 0xa2, 0xcf, 0x11, 0x36, 0x8d, 0x32, 0xcd, 0xd1,
	0xb5, 0xa3, 0x42, 0x9d, 0xd8, 0x14, 0xfe, 0x27, 0x30, 0xf8, 0xef, 0xc9, 0x53, 0xac, 0x86, 0x69,
	0xd0, 0xd7, 0xd5, 0xcc, 0xf9, 0x1a, 0x06, 0x65, 0x71, 0x55, 0xb2, 0x67, 0x35, 0xe9, 0x95, 0x05,
	0xa6, 0x75, 0xea, 0xf6, 0x0b, 0x2c, 0x39, 0x20, 0x82, 0xc3, 0x77, 0x9a, 0x89, 0xb5, 0xb3, 0x7e,
	0xce, 0x22, 0xa7, 0xd6, 0xcc, 0x67, 0x3f, 0x85, 0x51, 0x25, 0xef, 0x3c, 0x9d, 0x27, 0x73, 0x49,
	0xce, 0x68, 0xba, 0x43, 0x5d, 0xa6, 0xde, 0x1b, 0x64, 0x4f, 0xfe, 0xd9, 0x80, 0x5e, 0xe5, 0x24,
	0xe8, 0xeb, 0xdb, 0x39, 0x0b, 0x2b, 0x2d, 0x7c, 0xae, 0x95, 0x80, 0xca, 0xc4, 0x52, 0x7a, 0x80,
	0xc6, 0xca, 0x4f, 0x60, 0x1b, 0x2f, 0xc3, 0x38, 0x92, 0x91, 0x5e, 0x7d, 0x2c, 0xb0, 0x57, 0x24,
	0x71, 0x09, 0xf6, 0x00, 0x06, 0x78, 0x1b, 0x5d, 0xa4, 0x3c, 0x94, 0x78, 0xbb, 0xd9, 0x41, 0xa3,
	0xcf, 0x13, 0xf5, 0xac, 0xe0, 0xe1, 0x3d, 0x1f, 0xa7, 0x42, 0xa6, 0x76, 0xd0, 0x30, 0xc4, 0xe6,
	0x90, 0xd3, 0xba, 0x3d, 0xe4, 0x7c, 0x0e, 0x7b, 0xa5, 0xa1, 0xb6, 0x1d, 0xd3, 0xa8, 0x64, 0xa6,
	0x0d, 0x56, 0xc8, 0x4c, 0x27, 0xa6, 0x39, 0xf3, 0x7d, 0x80, 0x60, 0xae, 0x82, 0x2b, 0x8f, 0xa7,
	0x92, 0xdb, 0x99, 0xb8, 0x4b, 0x9c, 0x93, 0x54, 0x72, 0xf6, 0x4b, 0xe8, 0xcb, 0xb9, 0x0c, 0xf1,
	0x48, 0x14, 0xd5, 0x2e, 0x45, 0xd5, 0xb9, 0x95, 0x10, 0xdf, 0x18, 0x90, 0xdb, 0xb3, 0x68, 0xca,
	0x89, 0x07, 0x95, 0x9c, 0xc8, 0x12, 0x19, 0xd0, 0x35, 0xd8, 0x5d, 0x05, 0xff, 0x3c, 0x91, 0x01,
	0x7b, 0x06, 0xbb, 0x26, 0x7d, 0xd7, 0xd3, 0xa7, 0xb7, 0xd1, 0x16, 0x28, 0xca, 0x45, 0x0e, 0xb9,
	0xa3, 0xcb, 0x2a, 0x49, 0x49, 0xb4, 0x84, 0xe1, 0x86, 0x31, 0x78, 0xcf, 0x16, 0xc6, 0x47, 0x3c,
	0x94, 0xf6, 0x5d, 0x57, 0x98, 0xf8, 0x92, 0x87, 0x92, 0x9d, 0x42, 0xf9, 0xec, 0x5f, 0x7b, 0x0f,
	0x55, 0xcf, 0x68, 0x97, 0x2b, 0x37, 0xdf, 0x2e, 0x34, 0xec, 0x73, 0x29, 0x82, 0xc1, 0x9a, 0x75,
	0xec, 0x10, 0x3a, 0xe6, 0x48, 0x36, 0x99, 0xba, 0x6e, 0x9b, 0xe8, 0xa9, 0xf8, 0x9f, 0xec, 0xf7,
	0x8f, 0x1a, 0x0c, 0x37, 0x30, 0x6b, 0xae, 0xa6, 0xdc, 0x33, 0x0d, 0xa3, 0x74, 0x35, 0xa5, 0x1e,
	0xf6, 0x94, 0xd5, 0xe6, 0x94, 0xc4, 0xd8, 0x53, 0xca, 0xd5, 0x71, 0xce, 0x11, 0x71, 0x80, 0x32,
	0xf3, 0x9d, 0xab, 0x29, 0xe2, 0x60, 0x2a, 0xb0, 0xaf, 0x73, 0x11, 0x79, 0x55, 0xdd, 0x2d, 0xd2,
	0x1d, 0x70, 0x11, 0x3d, 0x5d, 0xa9, 0x7f, 0x08, 0xf6, 0xed, 0x67, 0x4c, 0x30, 0xb9, 0x0b, 0x86,
	0x85, 0x06, 0x4c, 0xfe, 0xdc, 0x82, 0x7e, 0xb5, 0x0f, 0x6c, 0x5a, 0x54, 0xbb, 0x65, 0xd1, 0xa7,
	0x30, 0xcc, 0x72, 0xdf, 0xbb, 0x6d, 0xf6, 0x20, 0xcb, 0xfd, 0xca, 0xd6, 0x1f, 0x00, 0xa4, 0x32,
	0x8b, 0xe7, 0x39, 0x55, 0x86, 0xb1, 0xbe, 0xc2, 0x61, 0x3f, 0x01, 0xf3, 0x6a, 0xf2, 0x2a, 0x28,
	0x33, 0x45, 0x0e, 0x89, 0xef, 0xae, 0xa0, 0x1f, 0x41, 0xdf, 0x40, 0xe7, 0x32, 0xba, 0xd4, 0x33,
	0x7b, 0x9d, 0x9b, 0x07, 0xd6, 0xb7, 0xc4, 0xc2, 0xf2, 0xa4, 0xc9, 0xca, 0x96, 0xa0, 0x21, 0xf0,
	0xaa, 0x36, 0xb3, 0x8f, 0x2d, 0x37, 0x4b, 0xe1, 0xe0, 0x5a, 0x3c, 0x2a, 0xcc, 0x48, 0x5f, 0x90,
	0x1b, 0x6f, 0x40, 0x3b, 0x40, 0xae, 0xde, 0x80, 0x1b, 0xf5, 0x0e, 0xb7, 0xeb, 0x9d, 0xde, 0x03,
	0xd1, 0xab, 0xcc, 0x8e, 0x90, 0x86, 0xc0, 0x1b, 0x0e, 0xeb, 0x00, 0x1d, 0x6f, 0x87, 0xc5, 0x92,
	0xc6, 0xb9, 0xe1, 0x22, 0x14, 0x3f, 0xa7, 0x59, 0xb0, 0xeb, 0xd2, 0x6f, 0x9a, 0x31, 0xe2, 0x3c,
	0x0d, 0xa4, 0x9d, 0xf3, 0x2c, 0x85, 0xab, 0x07, 0x34, 0x64, 0x0c, 0xcd, 0xea, 0x44, 0x20, 0x37,
	0x27, 0xee, 0x8e, 0xe1, 0x12, 0xc1, 0x76, 0xa1, 0x19, 0x50, 0xc2, 0x8f, 0x88, 0xbb, 0x15, 0x60,
	0xb6, 0x7f, 0x09, 0x03, 0x11, 0xc4, 0x1e, 0x7d, 0x85, 0xa0, 0x54, 0x67, 0x1b, 0x23, 0x85, 0xfd,
	0x54, 0xe1, 0xf6, 0x84, 0xf9, 0x41, 0x6d, 0xe3, 0x31, 0xec, 0x97, 0xf1, 0x4e, 0x78, 0x70, 0x85,
	0xaf, 0xe8, 0xf2, 0x23, 0x59, 0xd3, 0xdd, 0x2d, 0x84, 0xaf, 0x8d, 0x8c, 0x52, 0xfb, 0x67, 0xb0,
	0x8f, 0x13, 0x60, 0xa9, 0x57, 0xd6, 0xdf, 0x1e, 0x99, 0xc3, 0xb8, 0xb8, 0x2e, 0xb2, 0xe5, 0xb9,
	0x2d, 0x45, 0xcc, 0x6a, 0x5f, 0xcb, 0x4c, 0x9b, 0xcb, 0x02, 0xc1, 0xfb, 0x36, 0xab, 0x89, 0x4d,
	0x77, 0xc5, 0x54, 0x60, 0x35, 0xe7, 0x91, 0x7a, 0xeb, 0x05, 0x4a, 0xd0, 0x27, 0xb2, 0x86, 0x8b,
	0x63, 0xfd, 0xdb, 0xa7, 0xca, 0x16, 0xc6, 0xf5, 0x5a, 0x76, 0xde, 0x23, 0xbf, 0x0e, 0x2a, 0xfb,
	0x4d, 0x05, 0x66, 0xc0, 0x62, 0x26, 0x82, 0x78, 0x2a, 0xe8, 0x0b, 0x59, 0xc3, 0x2d, 0xc8, 0xc7,
	0x7f, 0x28, 0x3f, 0x5f, 0x9f, 0xcb, 0x94, 0x5e, 0x2b, 0x53, 0x60, 0xcf, 0xa5, 0xde, 0x1c, 0x03,
	0xef, 0xbd, 0xe3, 0x8b, 0xde, 0x7d, 0xe7, 0xb6, 0xc0, 0xa8, 0x4c, 0xfe, 0xef, 0x74, 0xf2, 0xfb,
	0xb1, 0xc8, 0x92, 0xcf, 0x8a, 0xae, 0xff, 0x88, 0x27, 0xea, 0xd1, 0xc6, 0x07, 0x76, 0xbf, 0x45,
	0xdf, 0xd1, 0xbf, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x53, 0x47, 0x7a, 0x7a, 0x17,
	0x00, 0x00,
}
