// Code generated by protoc-gen-go. DO NOT EDIT.
// source: juno/juno.proto

package juno // import "dsp-template/api/juno/juno"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import base "dsp-template/api/base"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SErrorCode int32

const (
	SErrorCode_kSuc  SErrorCode = 0
	SErrorCode_kFail SErrorCode = 1
)

var SErrorCode_name = map[int32]string{
	0: "kSuc",
	1: "kFail",
}
var SErrorCode_value = map[string]int32{
	"kSuc":  0,
	"kFail": 1,
}

func (x SErrorCode) String() string {
	return proto.EnumName(SErrorCode_name, int32(x))
}
func (SErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_juno_32f86f2d69714a22, []int{0}
}

// JunoRequest defines the dsp juno request structure
// 暂时从11开始，1-9留着标准化用,1分配给serializable id
type JunoRequest struct {
	Baserequest          *base.BaseRequest `protobuf:"bytes,1,opt,name=baserequest,proto3" json:"baserequest,omitempty"`
	ClientLable          string            `protobuf:"bytes,2,opt,name=clientLable,proto3" json:"clientLable,omitempty"`
	Exchange             string            `protobuf:"bytes,10,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Os                   string            `protobuf:"bytes,11,opt,name=Os,proto3" json:"Os,omitempty"`
	Country              string            `protobuf:"bytes,12,opt,name=Country,proto3" json:"Country,omitempty"`
	PkgName              string            `protobuf:"bytes,13,opt,name=PkgName,proto3" json:"PkgName,omitempty"`
	AdType               string            `protobuf:"bytes,14,opt,name=AdType,proto3" json:"AdType,omitempty"`
	GoogleAdId           string            `protobuf:"bytes,15,opt,name=GoogleAdId,proto3" json:"GoogleAdId,omitempty"`
	GoogleAdIdMd5        string            `protobuf:"bytes,16,opt,name=GoogleAdIdMd5,proto3" json:"GoogleAdIdMd5,omitempty"`
	IsGoogleAdId         bool              `protobuf:"varint,17,opt,name=IsGoogleAdId,proto3" json:"IsGoogleAdId,omitempty"`
	AppId                string            `protobuf:"bytes,18,opt,name=AppId,proto3" json:"AppId,omitempty"`
	ReserverFlag         bool              `protobuf:"varint,19,opt,name=ReserverFlag,proto3" json:"ReserverFlag,omitempty"`
	OsNum                int32             `protobuf:"varint,20,opt,name=OsNum,proto3" json:"OsNum,omitempty"`
	DeviceLanguage       string            `protobuf:"bytes,21,opt,name=DeviceLanguage,proto3" json:"DeviceLanguage,omitempty"`
	Https                bool              `protobuf:"varint,22,opt,name=Https,proto3" json:"Https,omitempty"`
	Bcat                 []string          `protobuf:"bytes,23,rep,name=Bcat,proto3" json:"Bcat,omitempty"`
	AdvertiserWhiteList  []string          `protobuf:"bytes,24,rep,name=AdvertiserWhiteList,proto3" json:"AdvertiserWhiteList,omitempty"`
	AdvertiserBlackList  []string          `protobuf:"bytes,25,rep,name=AdvertiserBlackList,proto3" json:"AdvertiserBlackList,omitempty"`
	BlockIndustryIds     []int64           `protobuf:"varint,26,rep,packed,name=BlockIndustryIds,proto3" json:"BlockIndustryIds,omitempty"`
	BlockClickType       []int64           `protobuf:"varint,27,rep,packed,name=BlockClickType,proto3" json:"BlockClickType,omitempty"`
	DevImpLimit          bool              `protobuf:"varint,28,opt,name=DevImpLimit,proto3" json:"DevImpLimit,omitempty"`
	Badv                 []string          `protobuf:"bytes,29,rep,name=Badv,proto3" json:"Badv,omitempty"`
	NetWorkType          int32             `protobuf:"varint,30,opt,name=NetWorkType,proto3" json:"NetWorkType,omitempty"`
	RequestGender        int32             `protobuf:"varint,31,opt,name=RequestGender,proto3" json:"RequestGender,omitempty"`
	UserAge              int32             `protobuf:"varint,32,opt,name=UserAge,proto3" json:"UserAge,omitempty"`
	Coppa                int32             `protobuf:"varint,33,opt,name=Coppa,proto3" json:"Coppa,omitempty"`
	WhiteOfferList       []int64           `protobuf:"varint,34,rep,packed,name=WhiteOfferList,proto3" json:"WhiteOfferList,omitempty"`
	BlackOfferList       []int64           `protobuf:"varint,35,rep,packed,name=BlackOfferList,proto3" json:"BlackOfferList,omitempty"`
	ForbidApk            bool              `protobuf:"varint,36,opt,name=ForbidApk,proto3" json:"ForbidApk,omitempty"`
	BSubCategorySDK      []int32           `protobuf:"varint,37,rep,packed,name=BSubCategorySDK,proto3" json:"BSubCategorySDK,omitempty"`
	IabCategory          []string          `protobuf:"bytes,38,rep,name=IabCategory,proto3" json:"IabCategory,omitempty"`
	IfSupportDeepLink    bool              `protobuf:"varint,39,opt,name=IfSupportDeepLink,proto3" json:"IfSupportDeepLink,omitempty"`
	CityCode             string            `protobuf:"bytes,40,opt,name=CityCode,proto3" json:"CityCode,omitempty"`
	Carrier              string            `protobuf:"bytes,41,opt,name=Carrier,proto3" json:"Carrier,omitempty"`
	Make                 string            `protobuf:"bytes,42,opt,name=Make,proto3" json:"Make,omitempty"`
	DeviceType           int32             `protobuf:"varint,43,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Model                string            `protobuf:"bytes,44,opt,name=Model,proto3" json:"Model,omitempty"`
	Hwv                  string            `protobuf:"bytes,45,opt,name=Hwv,proto3" json:"Hwv,omitempty"`
	Bundle               string            `protobuf:"bytes,46,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
	Imei                 string            `protobuf:"bytes,47,opt,name=Imei,proto3" json:"Imei,omitempty"`
	ImeiMd5              string            `protobuf:"bytes,48,opt,name=ImeiMd5,proto3" json:"ImeiMd5,omitempty"`
	AndroidId            string            `protobuf:"bytes,49,opt,name=AndroidId,proto3" json:"AndroidId,omitempty"`
	AndroidIdMd5         string            `protobuf:"bytes,50,opt,name=AndroidIdMd5,proto3" json:"AndroidIdMd5,omitempty"`
	IsImei               bool              `protobuf:"varint,51,opt,name=IsImei,proto3" json:"IsImei,omitempty"`
	IsAndroidId          bool              `protobuf:"varint,52,opt,name=IsAndroidId,proto3" json:"IsAndroidId,omitempty"`
	TrafficType          string            `protobuf:"bytes,53,opt,name=TrafficType,proto3" json:"TrafficType,omitempty"`
	AppSite              string            `protobuf:"bytes,54,opt,name=AppSite,proto3" json:"AppSite,omitempty"`
	MvAppId              string            `protobuf:"bytes,55,opt,name=MvAppId,proto3" json:"MvAppId,omitempty"`
	BApp                 []string          `protobuf:"bytes,56,rep,name=BApp,proto3" json:"BApp,omitempty"`
	BAppCategory         []string          `protobuf:"bytes,57,rep,name=BAppCategory,proto3" json:"BAppCategory,omitempty"`
	BAppSubCategory      []string          `protobuf:"bytes,58,rep,name=BAppSubCategory,proto3" json:"BAppSubCategory,omitempty"`
	BSubCategoryName     []string          `protobuf:"bytes,59,rep,name=BSubCategoryName,proto3" json:"BSubCategoryName,omitempty"`
	NeedAdvAudit         bool              `protobuf:"varint,60,opt,name=NeedAdvAudit,proto3" json:"NeedAdvAudit,omitempty"`
	NeedCreativeAudit    bool              `protobuf:"varint,61,opt,name=NeedCreativeAudit,proto3" json:"NeedCreativeAudit,omitempty"`
	OpenLog              bool              `protobuf:"varint,62,opt,name=OpenLog,proto3" json:"OpenLog,omitempty"`
	NeedSearchCpc        bool              `protobuf:"varint,63,opt,name=NeedSearchCpc,proto3" json:"NeedSearchCpc,omitempty"`
	QueryDmpDone         bool              `protobuf:"varint,64,opt,name=QueryDmpDone,proto3" json:"QueryDmpDone,omitempty"`
	TagId                string            `protobuf:"bytes,65,opt,name=TagId,proto3" json:"TagId,omitempty"`
	DebugCampaignIdList  []int64           `protobuf:"varint,66,rep,packed,name=DebugCampaignIdList,proto3" json:"DebugCampaignIdList,omitempty"`
	BlockAuditIndustryId []int64           `protobuf:"varint,67,rep,packed,name=BlockAuditIndustryId,proto3" json:"BlockAuditIndustryId,omitempty"`
	ManualPosId          string            `protobuf:"bytes,68,opt,name=ManualPosId,proto3" json:"ManualPosId,omitempty"`
	Osv                  int32             `protobuf:"varint,69,opt,name=Osv,proto3" json:"Osv,omitempty"`
	TcPkgTime            []string          `protobuf:"bytes,79,rep,name=Tc_pkg_time,json=TcPkgTime,proto3" json:"Tc_pkg_time,omitempty"`
	Ext8                 string            `protobuf:"bytes,80,opt,name=ext8,proto3" json:"ext8,omitempty"`
	AlgoPreRankRate      float64           `protobuf:"fixed64,81,opt,name=algo_pre_rank_rate,json=algoPreRankRate,proto3" json:"algo_pre_rank_rate,omitempty"`
	UnitId               int64             `protobuf:"varint,82,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	MAppId               int64             `protobuf:"varint,83,opt,name=MAppId,proto3" json:"MAppId,omitempty"`
	PublisherId          int64             `protobuf:"varint,84,opt,name=PublisherId,proto3" json:"PublisherId,omitempty"`
	Category             int64             `protobuf:"varint,85,opt,name=Category,proto3" json:"Category,omitempty"`
	Time                 int64             `protobuf:"varint,86,opt,name=Time,proto3" json:"Time,omitempty"`
	AbKey                map[string]string `protobuf:"bytes,87,rep,name=abKey,proto3" json:"abKey,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TcPackageName        []string          `protobuf:"bytes,88,rep,name=TcPackageName,proto3" json:"TcPackageName,omitempty"`
	RtCampaignIds        []int64           `protobuf:"varint,89,rep,packed,name=RtCampaignIds,proto3" json:"RtCampaignIds,omitempty"`
	PriceFloor           float64           `protobuf:"fixed64,90,opt,name=PriceFloor,proto3" json:"PriceFloor,omitempty"`
	RequestType          int64             `protobuf:"varint,91,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
	Device               *Device           `protobuf:"bytes,92,opt,name=device,proto3" json:"device,omitempty"`
	PackageNameBlackList []string          `protobuf:"bytes,93,rep,name=PackageNameBlackList,proto3" json:"PackageNameBlackList,omitempty"`
	AdSource             []int64           `protobuf:"varint,94,rep,packed,name=AdSource,proto3" json:"AdSource,omitempty"`
	DebugJuno            bool              `protobuf:"varint,95,opt,name=DebugJuno,proto3" json:"DebugJuno,omitempty"`
	NeedApkLandingPage   bool              `protobuf:"varint,96,opt,name=NeedApkLandingPage,proto3" json:"NeedApkLandingPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JunoRequest) Reset()         { *m = JunoRequest{} }
func (m *JunoRequest) String() string { return proto.CompactTextString(m) }
func (*JunoRequest) ProtoMessage()    {}
func (*JunoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_32f86f2d69714a22, []int{0}
}
func (m *JunoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunoRequest.Unmarshal(m, b)
}
func (m *JunoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunoRequest.Marshal(b, m, deterministic)
}
func (dst *JunoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunoRequest.Merge(dst, src)
}
func (m *JunoRequest) XXX_Size() int {
	return xxx_messageInfo_JunoRequest.Size(m)
}
func (m *JunoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JunoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JunoRequest proto.InternalMessageInfo

func (m *JunoRequest) GetBaserequest() *base.BaseRequest {
	if m != nil {
		return m.Baserequest
	}
	return nil
}

func (m *JunoRequest) GetClientLable() string {
	if m != nil {
		return m.ClientLable
	}
	return ""
}

func (m *JunoRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *JunoRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *JunoRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *JunoRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *JunoRequest) GetAdType() string {
	if m != nil {
		return m.AdType
	}
	return ""
}

func (m *JunoRequest) GetGoogleAdId() string {
	if m != nil {
		return m.GoogleAdId
	}
	return ""
}

func (m *JunoRequest) GetGoogleAdIdMd5() string {
	if m != nil {
		return m.GoogleAdIdMd5
	}
	return ""
}

func (m *JunoRequest) GetIsGoogleAdId() bool {
	if m != nil {
		return m.IsGoogleAdId
	}
	return false
}

func (m *JunoRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *JunoRequest) GetReserverFlag() bool {
	if m != nil {
		return m.ReserverFlag
	}
	return false
}

func (m *JunoRequest) GetOsNum() int32 {
	if m != nil {
		return m.OsNum
	}
	return 0
}

func (m *JunoRequest) GetDeviceLanguage() string {
	if m != nil {
		return m.DeviceLanguage
	}
	return ""
}

func (m *JunoRequest) GetHttps() bool {
	if m != nil {
		return m.Https
	}
	return false
}

func (m *JunoRequest) GetBcat() []string {
	if m != nil {
		return m.Bcat
	}
	return nil
}

func (m *JunoRequest) GetAdvertiserWhiteList() []string {
	if m != nil {
		return m.AdvertiserWhiteList
	}
	return nil
}

func (m *JunoRequest) GetAdvertiserBlackList() []string {
	if m != nil {
		return m.AdvertiserBlackList
	}
	return nil
}

func (m *JunoRequest) GetBlockIndustryIds() []int64 {
	if m != nil {
		return m.BlockIndustryIds
	}
	return nil
}

func (m *JunoRequest) GetBlockClickType() []int64 {
	if m != nil {
		return m.BlockClickType
	}
	return nil
}

func (m *JunoRequest) GetDevImpLimit() bool {
	if m != nil {
		return m.DevImpLimit
	}
	return false
}

func (m *JunoRequest) GetBadv() []string {
	if m != nil {
		return m.Badv
	}
	return nil
}

func (m *JunoRequest) GetNetWorkType() int32 {
	if m != nil {
		return m.NetWorkType
	}
	return 0
}

func (m *JunoRequest) GetRequestGender() int32 {
	if m != nil {
		return m.RequestGender
	}
	return 0
}

func (m *JunoRequest) GetUserAge() int32 {
	if m != nil {
		return m.UserAge
	}
	return 0
}

func (m *JunoRequest) GetCoppa() int32 {
	if m != nil {
		return m.Coppa
	}
	return 0
}

func (m *JunoRequest) GetWhiteOfferList() []int64 {
	if m != nil {
		return m.WhiteOfferList
	}
	return nil
}

func (m *JunoRequest) GetBlackOfferList() []int64 {
	if m != nil {
		return m.BlackOfferList
	}
	return nil
}

func (m *JunoRequest) GetForbidApk() bool {
	if m != nil {
		return m.ForbidApk
	}
	return false
}

func (m *JunoRequest) GetBSubCategorySDK() []int32 {
	if m != nil {
		return m.BSubCategorySDK
	}
	return nil
}

func (m *JunoRequest) GetIabCategory() []string {
	if m != nil {
		return m.IabCategory
	}
	return nil
}

func (m *JunoRequest) GetIfSupportDeepLink() bool {
	if m != nil {
		return m.IfSupportDeepLink
	}
	return false
}

func (m *JunoRequest) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *JunoRequest) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *JunoRequest) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *JunoRequest) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *JunoRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *JunoRequest) GetHwv() string {
	if m != nil {
		return m.Hwv
	}
	return ""
}

func (m *JunoRequest) GetBundle() string {
	if m != nil {
		return m.Bundle
	}
	return ""
}

func (m *JunoRequest) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *JunoRequest) GetImeiMd5() string {
	if m != nil {
		return m.ImeiMd5
	}
	return ""
}

func (m *JunoRequest) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *JunoRequest) GetAndroidIdMd5() string {
	if m != nil {
		return m.AndroidIdMd5
	}
	return ""
}

func (m *JunoRequest) GetIsImei() bool {
	if m != nil {
		return m.IsImei
	}
	return false
}

func (m *JunoRequest) GetIsAndroidId() bool {
	if m != nil {
		return m.IsAndroidId
	}
	return false
}

func (m *JunoRequest) GetTrafficType() string {
	if m != nil {
		return m.TrafficType
	}
	return ""
}

func (m *JunoRequest) GetAppSite() string {
	if m != nil {
		return m.AppSite
	}
	return ""
}

func (m *JunoRequest) GetMvAppId() string {
	if m != nil {
		return m.MvAppId
	}
	return ""
}

func (m *JunoRequest) GetBApp() []string {
	if m != nil {
		return m.BApp
	}
	return nil
}

func (m *JunoRequest) GetBAppCategory() []string {
	if m != nil {
		return m.BAppCategory
	}
	return nil
}

func (m *JunoRequest) GetBAppSubCategory() []string {
	if m != nil {
		return m.BAppSubCategory
	}
	return nil
}

func (m *JunoRequest) GetBSubCategoryName() []string {
	if m != nil {
		return m.BSubCategoryName
	}
	return nil
}

func (m *JunoRequest) GetNeedAdvAudit() bool {
	if m != nil {
		return m.NeedAdvAudit
	}
	return false
}

func (m *JunoRequest) GetNeedCreativeAudit() bool {
	if m != nil {
		return m.NeedCreativeAudit
	}
	return false
}

func (m *JunoRequest) GetOpenLog() bool {
	if m != nil {
		return m.OpenLog
	}
	return false
}

func (m *JunoRequest) GetNeedSearchCpc() bool {
	if m != nil {
		return m.NeedSearchCpc
	}
	return false
}

func (m *JunoRequest) GetQueryDmpDone() bool {
	if m != nil {
		return m.QueryDmpDone
	}
	return false
}

func (m *JunoRequest) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

func (m *JunoRequest) GetDebugCampaignIdList() []int64 {
	if m != nil {
		return m.DebugCampaignIdList
	}
	return nil
}

func (m *JunoRequest) GetBlockAuditIndustryId() []int64 {
	if m != nil {
		return m.BlockAuditIndustryId
	}
	return nil
}

func (m *JunoRequest) GetManualPosId() string {
	if m != nil {
		return m.ManualPosId
	}
	return ""
}

func (m *JunoRequest) GetOsv() int32 {
	if m != nil {
		return m.Osv
	}
	return 0
}

func (m *JunoRequest) GetTcPkgTime() []string {
	if m != nil {
		return m.TcPkgTime
	}
	return nil
}

func (m *JunoRequest) GetExt8() string {
	if m != nil {
		return m.Ext8
	}
	return ""
}

func (m *JunoRequest) GetAlgoPreRankRate() float64 {
	if m != nil {
		return m.AlgoPreRankRate
	}
	return 0
}

func (m *JunoRequest) GetUnitId() int64 {
	if m != nil {
		return m.UnitId
	}
	return 0
}

func (m *JunoRequest) GetMAppId() int64 {
	if m != nil {
		return m.MAppId
	}
	return 0
}

func (m *JunoRequest) GetPublisherId() int64 {
	if m != nil {
		return m.PublisherId
	}
	return 0
}

func (m *JunoRequest) GetCategory() int64 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *JunoRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *JunoRequest) GetAbKey() map[string]string {
	if m != nil {
		return m.AbKey
	}
	return nil
}

func (m *JunoRequest) GetTcPackageName() []string {
	if m != nil {
		return m.TcPackageName
	}
	return nil
}

func (m *JunoRequest) GetRtCampaignIds() []int64 {
	if m != nil {
		return m.RtCampaignIds
	}
	return nil
}

func (m *JunoRequest) GetPriceFloor() float64 {
	if m != nil {
		return m.PriceFloor
	}
	return 0
}

func (m *JunoRequest) GetRequestType() int64 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

func (m *JunoRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *JunoRequest) GetPackageNameBlackList() []string {
	if m != nil {
		return m.PackageNameBlackList
	}
	return nil
}

func (m *JunoRequest) GetAdSource() []int64 {
	if m != nil {
		return m.AdSource
	}
	return nil
}

func (m *JunoRequest) GetDebugJuno() bool {
	if m != nil {
		return m.DebugJuno
	}
	return false
}

func (m *JunoRequest) GetNeedApkLandingPage() bool {
	if m != nil {
		return m.NeedApkLandingPage
	}
	return false
}

type Device struct {
	Network              int32    `protobuf:"varint,1,opt,name=Network,proto3" json:"Network,omitempty"`
	SdkVersion           string   `protobuf:"bytes,2,opt,name=SdkVersion,proto3" json:"SdkVersion,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	DeviceMd5            string   `protobuf:"bytes,4,opt,name=DeviceMd5,proto3" json:"DeviceMd5,omitempty"`
	Oaid                 string   `protobuf:"bytes,5,opt,name=Oaid,proto3" json:"Oaid,omitempty"`
	Idfa                 string   `protobuf:"bytes,6,opt,name=Idfa,proto3" json:"Idfa,omitempty"`
	IdfaMd5              string   `protobuf:"bytes,7,opt,name=IdfaMd5,proto3" json:"IdfaMd5,omitempty"`
	AudienceIds          []int64  `protobuf:"varint,8,rep,packed,name=AudienceIds,proto3" json:"AudienceIds,omitempty"`
	RuleIds              []string `protobuf:"bytes,9,rep,name=RuleIds,proto3" json:"RuleIds,omitempty"`
	OaidMd5              string   `protobuf:"bytes,10,opt,name=OaidMd5,proto3" json:"OaidMd5,omitempty"`
	GoogleAdId           string   `protobuf:"bytes,11,opt,name=GoogleAdId,proto3" json:"GoogleAdId,omitempty"`
	GoogleAdIdMd5        string   `protobuf:"bytes,12,opt,name=GoogleAdIdMd5,proto3" json:"GoogleAdIdMd5,omitempty"`
	Imei                 string   `protobuf:"bytes,13,opt,name=Imei,proto3" json:"Imei,omitempty"`
	ImeiMd5              string   `protobuf:"bytes,14,opt,name=ImeiMd5,proto3" json:"ImeiMd5,omitempty"`
	AndroidId            string   `protobuf:"bytes,15,opt,name=AndroidId,proto3" json:"AndroidId,omitempty"`
	AndroidIdMd5         string   `protobuf:"bytes,16,opt,name=AndroidIdMd5,proto3" json:"AndroidIdMd5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_32f86f2d69714a22, []int{1}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetNetwork() int32 {
	if m != nil {
		return m.Network
	}
	return 0
}

func (m *Device) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *Device) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Device) GetDeviceMd5() string {
	if m != nil {
		return m.DeviceMd5
	}
	return ""
}

func (m *Device) GetOaid() string {
	if m != nil {
		return m.Oaid
	}
	return ""
}

func (m *Device) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *Device) GetIdfaMd5() string {
	if m != nil {
		return m.IdfaMd5
	}
	return ""
}

func (m *Device) GetAudienceIds() []int64 {
	if m != nil {
		return m.AudienceIds
	}
	return nil
}

func (m *Device) GetRuleIds() []string {
	if m != nil {
		return m.RuleIds
	}
	return nil
}

func (m *Device) GetOaidMd5() string {
	if m != nil {
		return m.OaidMd5
	}
	return ""
}

func (m *Device) GetGoogleAdId() string {
	if m != nil {
		return m.GoogleAdId
	}
	return ""
}

func (m *Device) GetGoogleAdIdMd5() string {
	if m != nil {
		return m.GoogleAdIdMd5
	}
	return ""
}

func (m *Device) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *Device) GetImeiMd5() string {
	if m != nil {
		return m.ImeiMd5
	}
	return ""
}

func (m *Device) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *Device) GetAndroidIdMd5() string {
	if m != nil {
		return m.AndroidIdMd5
	}
	return ""
}

// RankerResponse defines the dsp ranker response structure
// 暂时从11开始，1-9留着标准化用,1返回服务状态
type JunoResponse struct {
	JunoStatus                      *ServerStatus       `protobuf:"bytes,1,opt,name=JunoStatus,proto3" json:"JunoStatus,omitempty"`
	DeprecatedSearchResultList      []int64             `protobuf:"varint,2,rep,packed,name=deprecatedSearchResultList,proto3" json:"deprecatedSearchResultList,omitempty"`
	SearchResultListWithTag         []*JunoSearchResult `protobuf:"bytes,3,rep,name=SearchResultListWithTag,proto3" json:"SearchResultListWithTag,omitempty"`
	Ext8                            string              `protobuf:"bytes,4,opt,name=Ext8,proto3" json:"Ext8,omitempty"`
	DeprecatedIsPreference          bool                `protobuf:"varint,5,opt,name=deprecatedIsPreference,proto3" json:"deprecatedIsPreference,omitempty"`
	DeprecatedITciFilterInfo        string              `protobuf:"bytes,6,opt,name=deprecatedITciFilterInfo,proto3" json:"deprecatedITciFilterInfo,omitempty"`
	DeprecatedStrategy              string              `protobuf:"bytes,7,opt,name=deprecatedStrategy,proto3" json:"deprecatedStrategy,omitempty"`
	DeprecatedFilteredTcPackages    []string            `protobuf:"bytes,8,rep,name=deprecatedFilteredTcPackages,proto3" json:"deprecatedFilteredTcPackages,omitempty"`
	DeprecatedFilteredTcCampaignIds []int64             `protobuf:"varint,9,rep,packed,name=deprecatedFilteredTcCampaignIds,proto3" json:"deprecatedFilteredTcCampaignIds,omitempty"`
	InstallApps                     []int64             `protobuf:"varint,10,rep,packed,name=installApps,proto3" json:"installApps,omitempty"`
	// common.JunoCommonInfo commonInfo = 11;
	UsedAbKeys           map[string]string `protobuf:"bytes,12,rep,name=usedAbKeys,proto3" json:"usedAbKeys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JunoResponse) Reset()         { *m = JunoResponse{} }
func (m *JunoResponse) String() string { return proto.CompactTextString(m) }
func (*JunoResponse) ProtoMessage()    {}
func (*JunoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_32f86f2d69714a22, []int{2}
}
func (m *JunoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunoResponse.Unmarshal(m, b)
}
func (m *JunoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunoResponse.Marshal(b, m, deterministic)
}
func (dst *JunoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunoResponse.Merge(dst, src)
}
func (m *JunoResponse) XXX_Size() int {
	return xxx_messageInfo_JunoResponse.Size(m)
}
func (m *JunoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JunoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JunoResponse proto.InternalMessageInfo

func (m *JunoResponse) GetJunoStatus() *ServerStatus {
	if m != nil {
		return m.JunoStatus
	}
	return nil
}

func (m *JunoResponse) GetDeprecatedSearchResultList() []int64 {
	if m != nil {
		return m.DeprecatedSearchResultList
	}
	return nil
}

func (m *JunoResponse) GetSearchResultListWithTag() []*JunoSearchResult {
	if m != nil {
		return m.SearchResultListWithTag
	}
	return nil
}

func (m *JunoResponse) GetExt8() string {
	if m != nil {
		return m.Ext8
	}
	return ""
}

func (m *JunoResponse) GetDeprecatedIsPreference() bool {
	if m != nil {
		return m.DeprecatedIsPreference
	}
	return false
}

func (m *JunoResponse) GetDeprecatedITciFilterInfo() string {
	if m != nil {
		return m.DeprecatedITciFilterInfo
	}
	return ""
}

func (m *JunoResponse) GetDeprecatedStrategy() string {
	if m != nil {
		return m.DeprecatedStrategy
	}
	return ""
}

func (m *JunoResponse) GetDeprecatedFilteredTcPackages() []string {
	if m != nil {
		return m.DeprecatedFilteredTcPackages
	}
	return nil
}

func (m *JunoResponse) GetDeprecatedFilteredTcCampaignIds() []int64 {
	if m != nil {
		return m.DeprecatedFilteredTcCampaignIds
	}
	return nil
}

func (m *JunoResponse) GetInstallApps() []int64 {
	if m != nil {
		return m.InstallApps
	}
	return nil
}

func (m *JunoResponse) GetUsedAbKeys() map[string]string {
	if m != nil {
		return m.UsedAbKeys
	}
	return nil
}

// Status defines normal info about server
type ServerStatus struct {
	ErrorCode            SErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=juno.SErrorCode" json:"errorCode,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ip                   string     `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Elapsed              int64      `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_32f86f2d69714a22, []int{3}
}
func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (dst *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(dst, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetErrorCode() SErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return SErrorCode_kSuc
}

func (m *ServerStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ServerStatus) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServerStatus) GetElapsed() int64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

// juno返回的单子对象
type JunoSearchResult struct {
	CampaignId           int64    `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	DeprecatedStrategy   string   `protobuf:"bytes,2,opt,name=deprecatedStrategy,proto3" json:"deprecatedStrategy,omitempty"`
	GivingPrice          float64  `protobuf:"fixed64,3,opt,name=givingPrice,proto3" json:"givingPrice,omitempty"`
	DeprecatedWeight     int64    `protobuf:"varint,4,opt,name=deprecatedWeight,proto3" json:"deprecatedWeight,omitempty"`
	DeprecatedRecallType int64    `protobuf:"varint,5,opt,name=deprecatedRecallType,proto3" json:"deprecatedRecallType,omitempty"`
	DeprecatedSequency   int32    `protobuf:"varint,6,opt,name=deprecatedSequency,proto3" json:"deprecatedSequency,omitempty"`
	TryNewRate           float32  `protobuf:"fixed32,7,opt,name=tryNewRate,proto3" json:"tryNewRate,omitempty"`
	TryNewPriceRate      float32  `protobuf:"fixed32,8,opt,name=tryNewPriceRate,proto3" json:"tryNewPriceRate,omitempty"`
	RecallTypes          []string `protobuf:"bytes,9,rep,name=recallTypes,proto3" json:"recallTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JunoSearchResult) Reset()         { *m = JunoSearchResult{} }
func (m *JunoSearchResult) String() string { return proto.CompactTextString(m) }
func (*JunoSearchResult) ProtoMessage()    {}
func (*JunoSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_32f86f2d69714a22, []int{4}
}
func (m *JunoSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunoSearchResult.Unmarshal(m, b)
}
func (m *JunoSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunoSearchResult.Marshal(b, m, deterministic)
}
func (dst *JunoSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunoSearchResult.Merge(dst, src)
}
func (m *JunoSearchResult) XXX_Size() int {
	return xxx_messageInfo_JunoSearchResult.Size(m)
}
func (m *JunoSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JunoSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_JunoSearchResult proto.InternalMessageInfo

func (m *JunoSearchResult) GetCampaignId() int64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *JunoSearchResult) GetDeprecatedStrategy() string {
	if m != nil {
		return m.DeprecatedStrategy
	}
	return ""
}

func (m *JunoSearchResult) GetGivingPrice() float64 {
	if m != nil {
		return m.GivingPrice
	}
	return 0
}

func (m *JunoSearchResult) GetDeprecatedWeight() int64 {
	if m != nil {
		return m.DeprecatedWeight
	}
	return 0
}

func (m *JunoSearchResult) GetDeprecatedRecallType() int64 {
	if m != nil {
		return m.DeprecatedRecallType
	}
	return 0
}

func (m *JunoSearchResult) GetDeprecatedSequency() int32 {
	if m != nil {
		return m.DeprecatedSequency
	}
	return 0
}

func (m *JunoSearchResult) GetTryNewRate() float32 {
	if m != nil {
		return m.TryNewRate
	}
	return 0
}

func (m *JunoSearchResult) GetTryNewPriceRate() float32 {
	if m != nil {
		return m.TryNewPriceRate
	}
	return 0
}

func (m *JunoSearchResult) GetRecallTypes() []string {
	if m != nil {
		return m.RecallTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*JunoRequest)(nil), "juno.JunoRequest")
	proto.RegisterMapType((map[string]string)(nil), "juno.JunoRequest.AbKeyEntry")
	proto.RegisterType((*Device)(nil), "juno.Device")
	proto.RegisterType((*JunoResponse)(nil), "juno.JunoResponse")
	proto.RegisterMapType((map[string]string)(nil), "juno.JunoResponse.UsedAbKeysEntry")
	proto.RegisterType((*ServerStatus)(nil), "juno.ServerStatus")
	proto.RegisterType((*JunoSearchResult)(nil), "juno.JunoSearchResult")
	proto.RegisterEnum("juno.SErrorCode", SErrorCode_name, SErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JunoServiceClient is the client API for JunoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JunoServiceClient interface {
	JunoSearch(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error)
	JunoSearchTC(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error)
	JunoSearchRtDsp(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error)
}

type junoServiceClient struct {
	cc *grpc.ClientConn
}

func NewJunoServiceClient(cc *grpc.ClientConn) JunoServiceClient {
	return &junoServiceClient{cc}
}

func (c *junoServiceClient) JunoSearch(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error) {
	out := new(JunoResponse)
	err := c.cc.Invoke(ctx, "/juno.JunoService/junoSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoServiceClient) JunoSearchTC(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error) {
	out := new(JunoResponse)
	err := c.cc.Invoke(ctx, "/juno.JunoService/junoSearchTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *junoServiceClient) JunoSearchRtDsp(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error) {
	out := new(JunoResponse)
	err := c.cc.Invoke(ctx, "/juno.JunoService/junoSearchRtDsp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JunoServiceServer is the server API for JunoService service.
type JunoServiceServer interface {
	JunoSearch(context.Context, *JunoRequest) (*JunoResponse, error)
	JunoSearchTC(context.Context, *JunoRequest) (*JunoResponse, error)
	JunoSearchRtDsp(context.Context, *JunoRequest) (*JunoResponse, error)
}

func RegisterJunoServiceServer(s *grpc.Server, srv JunoServiceServer) {
	s.RegisterService(&_JunoService_serviceDesc, srv)
}

func _JunoService_JunoSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServiceServer).JunoSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.JunoService/JunoSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServiceServer).JunoSearch(ctx, req.(*JunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JunoService_JunoSearchTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServiceServer).JunoSearchTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.JunoService/JunoSearchTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServiceServer).JunoSearchTC(ctx, req.(*JunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JunoService_JunoSearchRtDsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServiceServer).JunoSearchRtDsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.JunoService/JunoSearchRtDsp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServiceServer).JunoSearchRtDsp(ctx, req.(*JunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JunoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "juno.JunoService",
	HandlerType: (*JunoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "junoSearch",
			Handler:    _JunoService_JunoSearch_Handler,
		},
		{
			MethodName: "junoSearchTC",
			Handler:    _JunoService_JunoSearchTC_Handler,
		},
		{
			MethodName: "junoSearchRtDsp",
			Handler:    _JunoService_JunoSearchRtDsp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juno/juno.proto",
}

func init() { proto.RegisterFile("juno/juno.proto", fileDescriptor_juno_32f86f2d69714a22) }

var fileDescriptor_juno_32f86f2d69714a22 = []byte{
	// 1909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0x6d, 0x7f, 0x1b, 0x47,
	0x11, 0x47, 0x56, 0x94, 0x5a, 0x6b, 0x27, 0x76, 0xb6, 0x21, 0x5d, 0x4c, 0x48, 0x55, 0x13, 0x8a,
	0x48, 0x5b, 0xbb, 0x38, 0xa4, 0x98, 0x40, 0x0b, 0x92, 0x6c, 0x37, 0xa2, 0x7e, 0x50, 0x4f, 0x4a,
	0x0d, 0xe5, 0xc1, 0xac, 0x6f, 0x47, 0xe7, 0xad, 0x4e, 0x77, 0xc7, 0xde, 0x9e, 0x52, 0xbd, 0xe3,
	0xc7, 0x57, 0xe2, 0x03, 0xf0, 0x9e, 0x2f, 0xc4, 0x5b, 0x7e, 0x33, 0x7b, 0x92, 0x4e, 0xb2, 0x9c,
	0x94, 0x37, 0xc9, 0xce, 0x7f, 0x66, 0xf7, 0x66, 0x66, 0xff, 0x33, 0xb3, 0x16, 0xdb, 0xf8, 0x26,
	0x8b, 0xe2, 0x5d, 0xfc, 0x67, 0x27, 0x31, 0xb1, 0x8d, 0xf9, 0x2d, 0x5c, 0x6f, 0x6d, 0x5c, 0xca,
	0x14, 0x76, 0xf1, 0x1f, 0x07, 0x6f, 0xff, 0xf7, 0x3e, 0x5b, 0xfb, 0x7d, 0x16, 0xc5, 0x1e, 0xfc,
	0x3d, 0x83, 0xd4, 0xf2, 0xa7, 0x6c, 0x0d, 0xb5, 0xc6, 0x89, 0xa2, 0x54, 0x2b, 0xd5, 0xd7, 0xf6,
	0xee, 0xed, 0xd0, 0x8e, 0xa6, 0x4c, 0x21, 0xb7, 0xf3, 0x8a, 0x56, 0xbc, 0xc6, 0xd6, 0xfc, 0x50,
	0x43, 0x64, 0x8f, 0xe5, 0x65, 0x08, 0x62, 0xa5, 0x56, 0xaa, 0x57, 0xbd, 0x22, 0xc4, 0xb7, 0xd8,
	0xea, 0xe1, 0xb7, 0xfe, 0x95, 0x8c, 0x02, 0x10, 0x8c, 0xd4, 0x53, 0x99, 0xdf, 0x65, 0x2b, 0x67,
	0xa9, 0x58, 0x23, 0x74, 0xe5, 0x2c, 0xe5, 0x82, 0xbd, 0xd5, 0x8a, 0xb3, 0xc8, 0x9a, 0xb1, 0x58,
	0x27, 0x70, 0x22, 0xa2, 0xa6, 0x33, 0x08, 0x4e, 0xe5, 0x10, 0xc4, 0x1d, 0xa7, 0xc9, 0x45, 0xfe,
	0x80, 0xdd, 0x6e, 0xa8, 0xde, 0x38, 0x01, 0x71, 0x97, 0x14, 0xb9, 0xc4, 0x1f, 0x31, 0xf6, 0x79,
	0x1c, 0x07, 0x21, 0x34, 0x54, 0x5b, 0x89, 0x0d, 0xd2, 0x15, 0x10, 0xfe, 0x98, 0xdd, 0x99, 0x49,
	0x27, 0xea, 0x99, 0xd8, 0x24, 0x93, 0x79, 0x90, 0x6f, 0xb3, 0xf5, 0x76, 0x5a, 0x38, 0xe7, 0x5e,
	0xad, 0x54, 0x5f, 0xf5, 0xe6, 0x30, 0x7e, 0x9f, 0x55, 0x1a, 0x49, 0xd2, 0x56, 0x82, 0xd3, 0x09,
	0x4e, 0xc0, 0x9d, 0x1e, 0xa4, 0x60, 0x46, 0x60, 0x8e, 0x42, 0x19, 0x88, 0xb7, 0xdd, 0xce, 0x22,
	0x86, 0x3b, 0xcf, 0xd2, 0xd3, 0x6c, 0x28, 0xee, 0xd7, 0x4a, 0xf5, 0x8a, 0xe7, 0x04, 0xfe, 0x3e,
	0xbb, 0x7b, 0x00, 0x23, 0xed, 0xc3, 0xb1, 0x8c, 0x82, 0x4c, 0x06, 0x20, 0xbe, 0x4f, 0x07, 0x2f,
	0xa0, 0xb8, 0xfb, 0x85, 0xb5, 0x49, 0x2a, 0x1e, 0xd0, 0xd1, 0x4e, 0xe0, 0x9c, 0xdd, 0x6a, 0xfa,
	0xd2, 0x8a, 0x77, 0x6a, 0xe5, 0x7a, 0xd5, 0xa3, 0x35, 0xff, 0x98, 0xbd, 0xdd, 0x50, 0x23, 0x30,
	0x56, 0xa7, 0x60, 0xce, 0xaf, 0xb4, 0x85, 0x63, 0x9d, 0x5a, 0x21, 0xc8, 0x64, 0x99, 0x6a, 0x7e,
	0x47, 0x33, 0x94, 0xfe, 0x80, 0x76, 0xfc, 0x60, 0x71, 0xc7, 0x54, 0xc5, 0x9f, 0xb0, 0xcd, 0x66,
	0x18, 0xfb, 0x83, 0x76, 0xa4, 0xb2, 0xd4, 0x9a, 0x71, 0x5b, 0xa5, 0x62, 0xab, 0x56, 0xae, 0x97,
	0xbd, 0x6b, 0x38, 0x46, 0x48, 0x58, 0x2b, 0xd4, 0xfe, 0x80, 0xee, 0xee, 0x87, 0x64, 0xb9, 0x80,
	0x22, 0xbb, 0x0e, 0x60, 0xd4, 0x1e, 0x26, 0xc7, 0x7a, 0xa8, 0xad, 0x78, 0x48, 0x71, 0x16, 0x21,
	0x8a, 0x56, 0xaa, 0x91, 0xf8, 0x51, 0x1e, 0xad, 0x54, 0x23, 0xdc, 0x75, 0x0a, 0xf6, 0x3c, 0x36,
	0xee, 0xe8, 0x47, 0x94, 0xdb, 0x22, 0x84, 0x77, 0x9f, 0xb3, 0xf9, 0x73, 0x88, 0x14, 0x18, 0xf1,
	0x2e, 0xd9, 0xcc, 0x83, 0xc8, 0xb9, 0x97, 0x29, 0x98, 0x46, 0x00, 0xa2, 0x46, 0xfa, 0x89, 0x88,
	0x99, 0x6f, 0xc5, 0x49, 0x22, 0xc5, 0x7b, 0xee, 0xde, 0x48, 0xc0, 0xa8, 0x28, 0x81, 0x67, 0xfd,
	0x3e, 0x18, 0x4a, 0xd7, 0xb6, 0x8b, 0x6a, 0x1e, 0x75, 0xd1, 0x4b, 0x7f, 0x30, 0xb3, 0xfb, 0xf1,
	0x24, 0xfa, 0x22, 0xca, 0x1f, 0xb2, 0xea, 0x51, 0x6c, 0x2e, 0xb5, 0x6a, 0x24, 0x03, 0xf1, 0x98,
	0x62, 0x9f, 0x01, 0xbc, 0xce, 0x36, 0x9a, 0xdd, 0xec, 0xb2, 0x25, 0x2d, 0x04, 0xb1, 0x19, 0x77,
	0x0f, 0xbe, 0x10, 0x3f, 0xa9, 0x95, 0xeb, 0x15, 0x6f, 0x11, 0xc6, 0x7c, 0xb4, 0xe5, 0x14, 0x11,
	0xef, 0x53, 0xaa, 0x8a, 0x10, 0xff, 0x90, 0xdd, 0x6b, 0xf7, 0xbb, 0x59, 0x92, 0xc4, 0xc6, 0x1e,
	0x00, 0x24, 0xc7, 0x3a, 0x1a, 0x88, 0x9f, 0xd2, 0x17, 0xaf, 0x2b, 0xb0, 0xa2, 0x5b, 0xda, 0x8e,
	0x5b, 0xb1, 0x02, 0x51, 0x77, 0x15, 0x3d, 0x91, 0xa9, 0x82, 0xa5, 0x31, 0x1a, 0x8c, 0xf8, 0x59,
	0x5e, 0xc1, 0x4e, 0xc4, 0x9b, 0x3a, 0x91, 0x03, 0x10, 0x4f, 0x08, 0xa6, 0x35, 0xd6, 0xa8, 0xe3,
	0x34, 0x5d, 0xd4, 0x07, 0x94, 0xcc, 0x02, 0x82, 0x79, 0x3e, 0x89, 0x15, 0x84, 0xe2, 0x43, 0x57,
	0x59, 0x24, 0xf0, 0x4d, 0x56, 0x7e, 0xf1, 0x6a, 0x24, 0x3e, 0x22, 0x0c, 0x97, 0xd8, 0x03, 0x9a,
	0x59, 0xa4, 0x42, 0x10, 0x3b, 0xae, 0x07, 0x38, 0x09, 0xbf, 0xd9, 0x1e, 0x82, 0x16, 0xbb, 0xee,
	0x9b, 0xb8, 0x46, 0x0f, 0xf1, 0x7f, 0xac, 0xf8, 0x8f, 0x9d, 0x87, 0xb9, 0x88, 0xf9, 0x6e, 0x44,
	0xca, 0xc4, 0x1a, 0x0b, 0xfd, 0xe7, 0xa4, 0x9b, 0x01, 0x58, 0xcf, 0x53, 0x01, 0x37, 0xef, 0x91,
	0xc1, 0x1c, 0x86, 0x7e, 0xb4, 0x53, 0xfa, 0xe2, 0x53, 0x4a, 0x5e, 0x2e, 0xd1, 0x0d, 0xa4, 0xb3,
	0xb3, 0x7f, 0xe1, 0x78, 0x5c, 0x80, 0xd0, 0xa2, 0x67, 0x64, 0xbf, 0xaf, 0x7d, 0x4a, 0xc5, 0x33,
	0xd7, 0x47, 0x0b, 0x10, 0xfa, 0xdd, 0x48, 0x92, 0xae, 0xb6, 0x20, 0x3e, 0x71, 0x7e, 0xe7, 0x22,
	0x6a, 0x4e, 0x46, 0xae, 0x03, 0xfd, 0xd2, 0x69, 0x72, 0x91, 0xaa, 0xa3, 0x91, 0x24, 0x62, 0x3f,
	0xaf, 0x8e, 0x46, 0x92, 0x60, 0x1c, 0xf8, 0xff, 0x94, 0x0e, 0xbf, 0x22, 0xdd, 0x1c, 0x46, 0xdc,
	0xc2, 0xd3, 0x67, 0x3c, 0x12, 0xcf, 0xc9, 0x6c, 0x11, 0xa6, 0xaa, 0x2f, 0xc8, 0xd4, 0xa0, 0x7f,
	0x4d, 0xa6, 0xd7, 0x70, 0xfc, 0xf2, 0x29, 0x80, 0x6a, 0xa8, 0x51, 0x23, 0x53, 0xda, 0x8a, 0xdf,
	0xb8, 0x8e, 0x58, 0xc4, 0x90, 0x89, 0x28, 0xb7, 0x0c, 0x48, 0xab, 0x47, 0xe0, 0x0c, 0x3f, 0x75,
	0x4c, 0xbc, 0xa6, 0xc0, 0xc8, 0xcf, 0x12, 0x88, 0x8e, 0xe3, 0x40, 0x7c, 0x46, 0x36, 0x13, 0x11,
	0x2b, 0x1c, 0xcd, 0xbb, 0x20, 0x8d, 0x7f, 0xd5, 0x4a, 0x7c, 0xf1, 0x5b, 0xd2, 0xcf, 0x83, 0xe8,
	0xd1, 0x97, 0x19, 0x98, 0xf1, 0xc1, 0x30, 0x39, 0x88, 0x23, 0x10, 0xbf, 0x73, 0x1e, 0x15, 0x31,
	0xe4, 0x60, 0x4f, 0x06, 0x6d, 0x25, 0x1a, 0x8e, 0x83, 0x24, 0x60, 0x7f, 0x3c, 0x80, 0xcb, 0x2c,
	0x68, 0xc9, 0x61, 0x22, 0x75, 0x10, 0xb5, 0x15, 0x15, 0x72, 0x93, 0x0a, 0x79, 0x99, 0x8a, 0xef,
	0xb1, 0xfb, 0xd4, 0xdd, 0xc8, 0xf3, 0x59, 0x33, 0x14, 0x2d, 0xda, 0xb2, 0x54, 0x87, 0xac, 0x38,
	0x91, 0x51, 0x26, 0xc3, 0x4e, 0x9c, 0xb6, 0x95, 0x38, 0x70, 0xac, 0x28, 0x40, 0x58, 0x0b, 0x67,
	0xe9, 0x48, 0x1c, 0x52, 0xe9, 0xe0, 0x92, 0x3f, 0x62, 0x6b, 0x3d, 0xff, 0x22, 0x19, 0x04, 0x17,
	0x56, 0x0f, 0x41, 0x9c, 0xd1, 0x65, 0x54, 0x7b, 0x7e, 0x67, 0x10, 0xf4, 0xf4, 0x90, 0x6a, 0x02,
	0xbe, 0xb5, 0xfb, 0xa2, 0xe3, 0x6a, 0x02, 0xd7, 0xfc, 0x03, 0xc6, 0x65, 0x18, 0xc4, 0x17, 0x89,
	0x81, 0x0b, 0x23, 0xa3, 0xc1, 0x85, 0x91, 0x16, 0xc4, 0x97, 0xb5, 0x52, 0xbd, 0xe4, 0x6d, 0xa0,
	0xa6, 0x63, 0xc0, 0x93, 0xd1, 0xc0, 0x93, 0x96, 0x06, 0xee, 0xcb, 0x48, 0xdb, 0xb6, 0x12, 0x5e,
	0xad, 0x54, 0x2f, 0x7b, 0xb9, 0x84, 0xf8, 0x89, 0x63, 0x61, 0xd7, 0xe1, 0x4e, 0xc2, 0x20, 0x3a,
	0xd9, 0x65, 0xa8, 0xd3, 0x2b, 0x30, 0x6d, 0x25, 0x7a, 0xa4, 0x2c, 0x42, 0xd4, 0x50, 0x26, 0x3c,
	0x7b, 0x49, 0xea, 0xa9, 0x8c, 0xee, 0xa2, 0xdb, 0xe2, 0x2b, 0xc2, 0x69, 0xcd, 0xf7, 0x58, 0x45,
	0x5e, 0x7e, 0x01, 0x63, 0x71, 0x5e, 0x2b, 0xd7, 0xd7, 0xf6, 0x1e, 0xee, 0xd0, 0x63, 0xa7, 0xf0,
	0x96, 0xd9, 0x69, 0xa0, 0xfa, 0x10, 0x5f, 0x0e, 0x9e, 0x33, 0x45, 0x42, 0xf4, 0xfc, 0x8e, 0xf4,
	0x07, 0x32, 0x00, 0x62, 0xe9, 0x1f, 0x28, 0x31, 0xf3, 0x20, 0x0d, 0x06, 0x3b, 0xbb, 0xb8, 0x54,
	0xfc, 0x91, 0x6e, 0x67, 0x1e, 0xc4, 0xb6, 0xd5, 0x31, 0xda, 0x87, 0xa3, 0x30, 0x8e, 0x8d, 0xf8,
	0x9a, 0xd2, 0x54, 0x40, 0x30, 0xe2, 0xdc, 0x11, 0x2a, 0xe6, 0x3f, 0xb9, 0x88, 0x0b, 0x10, 0x7f,
	0xcc, 0x6e, 0x2b, 0x6a, 0x73, 0xe2, 0xcf, 0xf4, 0xcc, 0x5a, 0x77, 0x21, 0xb8, 0xd6, 0xe7, 0xe5,
	0x3a, 0xa4, 0x4c, 0xc1, 0xb9, 0xd9, 0x14, 0xfe, 0x0b, 0xb9, 0xbe, 0x54, 0x87, 0xb9, 0x6c, 0xa8,
	0x6e, 0x9c, 0x19, 0x1f, 0xc4, 0x5f, 0xc9, 0xf9, 0xa9, 0x8c, 0x0d, 0x8e, 0x98, 0x89, 0x99, 0x12,
	0x17, 0x6e, 0xa0, 0x4c, 0x01, 0xbe, 0xc3, 0x38, 0x95, 0x62, 0x32, 0x38, 0x96, 0x91, 0xd2, 0x51,
	0xd0, 0xc1, 0xa7, 0xc7, 0xdf, 0xc8, 0x6c, 0x89, 0x66, 0x6b, 0x9f, 0xb1, 0x59, 0x9a, 0x91, 0x88,
	0x03, 0x18, 0xd3, 0xab, 0xb1, 0xea, 0xe1, 0x12, 0x0b, 0x67, 0x24, 0xc3, 0x6c, 0xf2, 0x28, 0x74,
	0xc2, 0xf3, 0x95, 0xfd, 0xd2, 0xf6, 0x7f, 0xca, 0xec, 0xb6, 0x0b, 0x15, 0x2b, 0xf8, 0x14, 0xec,
	0xab, 0xd8, 0x0c, 0x68, 0x6b, 0xc5, 0x9b, 0x88, 0x98, 0xe4, 0xae, 0x1a, 0x7c, 0x05, 0x26, 0xd5,
	0x71, 0x94, 0x9f, 0x51, 0x40, 0x30, 0x50, 0x77, 0x46, 0x5b, 0x89, 0xb2, 0x9b, 0x42, 0x13, 0xd9,
	0x05, 0x8a, 0x6b, 0x6c, 0xd4, 0xb7, 0x5c, 0x27, 0x9f, 0x02, 0x48, 0xa9, 0x33, 0xa9, 0x95, 0xa8,
	0xb8, 0x0a, 0xc0, 0x35, 0x4d, 0x0a, 0xd5, 0x97, 0xe2, 0x76, 0x3e, 0x29, 0x54, 0x5f, 0xd2, 0xa4,
	0x50, 0x7d, 0x89, 0x67, 0xbc, 0x95, 0x4f, 0x0a, 0x27, 0xe2, 0x05, 0x63, 0xa9, 0x42, 0x84, 0x5f,
	0x4b, 0xc5, 0x2a, 0xe5, 0xb9, 0x08, 0xe1, 0x5e, 0x2f, 0x0b, 0x49, 0x5b, 0xa5, 0xdb, 0x9a, 0x88,
	0xd4, 0xb3, 0xa4, 0xa6, 0x11, 0xe2, 0x9e, 0xc3, 0x13, 0x71, 0xe1, 0xc5, 0xba, 0xf6, 0xe6, 0x17,
	0xeb, 0xfa, 0xb2, 0x17, 0xeb, 0x64, 0xe6, 0xdd, 0x59, 0x3e, 0xf3, 0xee, 0xbe, 0x66, 0xe6, 0x6d,
	0xbc, 0x69, 0xe6, 0x6d, 0x5e, 0x9f, 0x79, 0xdb, 0xff, 0xae, 0xb0, 0x75, 0x57, 0x7a, 0x69, 0x12,
	0x47, 0x29, 0xb2, 0x96, 0xa1, 0xdc, 0xb5, 0xd2, 0x66, 0x69, 0xfe, 0x67, 0x04, 0x77, 0xfc, 0xee,
	0xd2, 0xd3, 0xd7, 0x69, 0xbc, 0x82, 0x15, 0xff, 0x8c, 0x6d, 0x29, 0x48, 0x0c, 0xf8, 0xd2, 0x4e,
	0xfa, 0xb3, 0x07, 0x69, 0x16, 0x5a, 0xe2, 0xfb, 0x0a, 0xe5, 0xf7, 0x35, 0x16, 0xbc, 0xc3, 0xde,
	0x59, 0xc4, 0xce, 0xb5, 0xbd, 0xea, 0xc9, 0x40, 0x94, 0xa9, 0x47, 0x3c, 0x98, 0xf5, 0x88, 0xa2,
	0xa1, 0x77, 0xd3, 0x36, 0x4c, 0xe3, 0x21, 0xb6, 0x49, 0xc7, 0x1e, 0x5a, 0xf3, 0x4f, 0xd8, 0x83,
	0x99, 0x0f, 0xed, 0xb4, 0x63, 0xa0, 0x0f, 0x06, 0x6f, 0x9c, 0xa8, 0xb4, 0xea, 0xdd, 0xa0, 0xe5,
	0xcf, 0x99, 0x28, 0x68, 0x7a, 0xbe, 0x3e, 0xd2, 0xa1, 0x05, 0xd3, 0x8e, 0xfa, 0x71, 0x4e, 0xb8,
	0x1b, 0xf5, 0x58, 0x95, 0x85, 0xb8, 0x2d, 0x36, 0xe6, 0x60, 0x9c, 0xf3, 0x71, 0x89, 0x86, 0x37,
	0xd9, 0xc3, 0x19, 0xea, 0xce, 0x01, 0x35, 0x6d, 0x72, 0x8e, 0xab, 0x55, 0xef, 0xb5, 0x36, 0xfc,
	0x05, 0x7b, 0x77, 0x99, 0xbe, 0xd8, 0x17, 0xab, 0x74, 0x25, 0x6f, 0x32, 0xc3, 0x42, 0xd1, 0x51,
	0x6a, 0x65, 0x18, 0x36, 0x92, 0x24, 0x15, 0xcc, 0x15, 0x4a, 0x01, 0xe2, 0x4d, 0xc6, 0xb2, 0x14,
	0x14, 0x75, 0x92, 0x54, 0xac, 0xd3, 0x65, 0x6d, 0x17, 0x1b, 0xba, 0x63, 0xd5, 0xce, 0xcb, 0xa9,
	0x91, 0x6b, 0xeb, 0x85, 0x5d, 0x5b, 0x9f, 0xb2, 0x8d, 0x05, 0xf5, 0xff, 0xd5, 0x8e, 0xfe, 0x59,
	0x62, 0xeb, 0x45, 0x66, 0xf2, 0x1d, 0x56, 0x05, 0x63, 0x62, 0x43, 0x2f, 0x5c, 0x3c, 0xe2, 0xee,
	0xde, 0x66, 0x4e, 0xe0, 0xc3, 0x09, 0xee, 0xcd, 0x4c, 0xb0, 0xbc, 0x86, 0x90, 0xa6, 0xd8, 0x2e,
	0xdd, 0xe1, 0x13, 0x11, 0xff, 0xc0, 0xd5, 0x49, 0xde, 0x9e, 0x56, 0x74, 0x82, 0x96, 0x10, 0xca,
	0x24, 0x05, 0x45, 0xc4, 0x2a, 0x7b, 0x13, 0x71, 0xfb, 0x1f, 0x65, 0xb6, 0xb9, 0xc8, 0x4e, 0xec,
	0x08, 0xb3, 0x6c, 0x92, 0x27, 0x65, 0xaf, 0x80, 0xdc, 0x40, 0x8e, 0x95, 0x1b, 0xc9, 0x51, 0x63,
	0x6b, 0x81, 0x1e, 0x61, 0x03, 0xc7, 0x61, 0x45, 0x7e, 0x95, 0xbc, 0x22, 0x84, 0xef, 0xb9, 0xd9,
	0xbe, 0x73, 0xd0, 0xc1, 0x95, 0xcd, 0x3d, 0xbd, 0x86, 0xe3, 0x78, 0x9a, 0x61, 0x1e, 0xf8, 0x32,
	0x0c, 0x69, 0xde, 0x55, 0xc8, 0x7e, 0xa9, 0x6e, 0xc1, 0x63, 0x9c, 0x88, 0x91, 0x3f, 0xa6, 0x22,
	0xa8, 0x78, 0x4b, 0x34, 0x98, 0x01, 0x6b, 0xc6, 0xa7, 0xf0, 0x0a, 0x9f, 0x1e, 0x44, 0xfb, 0x15,
	0xaf, 0x80, 0xe0, 0x4b, 0xd5, 0x49, 0xe4, 0x3e, 0x19, 0xad, 0x92, 0xd1, 0x22, 0x8c, 0xb1, 0x9b,
	0xa9, 0x1f, 0x93, 0xae, 0x5c, 0x84, 0x9e, 0xbc, 0xc7, 0xd8, 0xec, 0x7e, 0xf9, 0x2a, 0xbb, 0x35,
	0xe8, 0x66, 0xfe, 0xe6, 0xf7, 0x78, 0x95, 0x55, 0x06, 0x47, 0x52, 0x87, 0x9b, 0xa5, 0xbd, 0x7f,
	0x95, 0xdc, 0x6f, 0x26, 0x48, 0x17, 0x4c, 0xd7, 0x53, 0xc6, 0xbe, 0x99, 0x5e, 0x1a, 0xbf, 0x77,
	0xed, 0x21, 0xb2, 0xc5, 0xaf, 0x53, 0x99, 0x3f, 0x63, 0xeb, 0xb3, 0x4d, 0xbd, 0xd6, 0x77, 0xdd,
	0xb6, 0xef, 0x7e, 0xd9, 0xc9, 0x09, 0x62, 0x0f, 0xd2, 0xe4, 0x3b, 0xee, 0x6c, 0x3e, 0xfc, 0x7a,
	0x4b, 0xa5, 0xc9, 0x47, 0x16, 0x86, 0x49, 0x28, 0x2d, 0xec, 0xca, 0x44, 0xef, 0x4e, 0x7f, 0x24,
	0xba, 0xbc, 0x4d, 0x3f, 0x07, 0x3d, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xd0, 0xc0,
	0x9f, 0x38, 0x12, 0x00, 0x00,
}
