// Code generated by protoc-gen-go. DO NOT EDIT.
// source: juno/juno.proto

package juno // import "dsp-template/api/juno/juno"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import base "dsp-template/api/base"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// JunoRequest defines the dsp juno request structure
// 暂时从11开始，1-9留着标准化用,1分配给serializable id
type JunoRequest struct {
	Baserequest          *base.BaseRequest `protobuf:"bytes,1,opt,name=baserequest,proto3" json:"baserequest,omitempty"`
	ClientLable          string            `protobuf:"bytes,2,opt,name=clientLable,proto3" json:"clientLable,omitempty"`
	Exchange             string            `protobuf:"bytes,10,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Os                   string            `protobuf:"bytes,11,opt,name=Os,proto3" json:"Os,omitempty"`
	Country              string            `protobuf:"bytes,12,opt,name=Country,proto3" json:"Country,omitempty"`
	PkgName              string            `protobuf:"bytes,13,opt,name=PkgName,proto3" json:"PkgName,omitempty"`
	AdType               string            `protobuf:"bytes,14,opt,name=AdType,proto3" json:"AdType,omitempty"`
	AppId                string            `protobuf:"bytes,18,opt,name=AppId,proto3" json:"AppId,omitempty"`
	OsNum                int32             `protobuf:"varint,20,opt,name=OsNum,proto3" json:"OsNum,omitempty"`
	DeviceLanguage       string            `protobuf:"bytes,21,opt,name=DeviceLanguage,proto3" json:"DeviceLanguage,omitempty"`
	Https                bool              `protobuf:"varint,22,opt,name=Https,proto3" json:"Https,omitempty"`
	Bcat                 []string          `protobuf:"bytes,23,rep,name=Bcat,proto3" json:"Bcat,omitempty"`
	AdvertiserWhiteList  []string          `protobuf:"bytes,24,rep,name=AdvertiserWhiteList,proto3" json:"AdvertiserWhiteList,omitempty"`
	AdvertiserBlackList  []string          `protobuf:"bytes,25,rep,name=AdvertiserBlackList,proto3" json:"AdvertiserBlackList,omitempty"`
	BlockIndustryIds     []int64           `protobuf:"varint,26,rep,packed,name=BlockIndustryIds,proto3" json:"BlockIndustryIds,omitempty"`
	BlockClickType       []int64           `protobuf:"varint,27,rep,packed,name=BlockClickType,proto3" json:"BlockClickType,omitempty"`
	DevImpLimit          bool              `protobuf:"varint,28,opt,name=DevImpLimit,proto3" json:"DevImpLimit,omitempty"`
	Badv                 []string          `protobuf:"bytes,29,rep,name=Badv,proto3" json:"Badv,omitempty"`
	NetWorkType          int32             `protobuf:"varint,30,opt,name=NetWorkType,proto3" json:"NetWorkType,omitempty"`
	RequestGender        int32             `protobuf:"varint,31,opt,name=RequestGender,proto3" json:"RequestGender,omitempty"`
	UserAge              int32             `protobuf:"varint,32,opt,name=UserAge,proto3" json:"UserAge,omitempty"`
	Coppa                int32             `protobuf:"varint,33,opt,name=Coppa,proto3" json:"Coppa,omitempty"`
	WhiteOfferList       []int64           `protobuf:"varint,34,rep,packed,name=WhiteOfferList,proto3" json:"WhiteOfferList,omitempty"`
	BlackOfferList       []int64           `protobuf:"varint,35,rep,packed,name=BlackOfferList,proto3" json:"BlackOfferList,omitempty"`
	ForbidApk            bool              `protobuf:"varint,36,opt,name=ForbidApk,proto3" json:"ForbidApk,omitempty"`
	BSubCategorySDK      []int32           `protobuf:"varint,37,rep,packed,name=BSubCategorySDK,proto3" json:"BSubCategorySDK,omitempty"`
	IabCategory          []string          `protobuf:"bytes,38,rep,name=IabCategory,proto3" json:"IabCategory,omitempty"`
	IfSupportDeepLink    bool              `protobuf:"varint,39,opt,name=IfSupportDeepLink,proto3" json:"IfSupportDeepLink,omitempty"`
	CityCode             string            `protobuf:"bytes,40,opt,name=CityCode,proto3" json:"CityCode,omitempty"`
	Carrier              string            `protobuf:"bytes,41,opt,name=Carrier,proto3" json:"Carrier,omitempty"`
	Make                 string            `protobuf:"bytes,42,opt,name=Make,proto3" json:"Make,omitempty"`
	DeviceType           int32             `protobuf:"varint,43,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	Model                string            `protobuf:"bytes,44,opt,name=Model,proto3" json:"Model,omitempty"`
	Hwv                  string            `protobuf:"bytes,45,opt,name=Hwv,proto3" json:"Hwv,omitempty"`
	Bundle               string            `protobuf:"bytes,46,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
	TrafficType          string            `protobuf:"bytes,53,opt,name=TrafficType,proto3" json:"TrafficType,omitempty"`
	AppSite              string            `protobuf:"bytes,54,opt,name=AppSite,proto3" json:"AppSite,omitempty"`
	MvAppId              string            `protobuf:"bytes,55,opt,name=MvAppId,proto3" json:"MvAppId,omitempty"`
	BApp                 []string          `protobuf:"bytes,56,rep,name=BApp,proto3" json:"BApp,omitempty"`
	BAppCategory         []string          `protobuf:"bytes,57,rep,name=BAppCategory,proto3" json:"BAppCategory,omitempty"`
	BAppSubCategory      []string          `protobuf:"bytes,58,rep,name=BAppSubCategory,proto3" json:"BAppSubCategory,omitempty"`
	BSubCategoryName     []string          `protobuf:"bytes,59,rep,name=BSubCategoryName,proto3" json:"BSubCategoryName,omitempty"`
	NeedAdvAudit         bool              `protobuf:"varint,60,opt,name=NeedAdvAudit,proto3" json:"NeedAdvAudit,omitempty"`
	NeedCreativeAudit    bool              `protobuf:"varint,61,opt,name=NeedCreativeAudit,proto3" json:"NeedCreativeAudit,omitempty"`
	NeedSearchCpc        bool              `protobuf:"varint,63,opt,name=NeedSearchCpc,proto3" json:"NeedSearchCpc,omitempty"`
	TagId                string            `protobuf:"bytes,65,opt,name=TagId,proto3" json:"TagId,omitempty"`
	DebugCampaignIdList  []int64           `protobuf:"varint,66,rep,packed,name=DebugCampaignIdList,proto3" json:"DebugCampaignIdList,omitempty"`
	BlockAuditIndustryId []int64           `protobuf:"varint,67,rep,packed,name=BlockAuditIndustryId,proto3" json:"BlockAuditIndustryId,omitempty"`
	ManualPosId          string            `protobuf:"bytes,68,opt,name=ManualPosId,proto3" json:"ManualPosId,omitempty"`
	Osv                  int32             `protobuf:"varint,69,opt,name=Osv,proto3" json:"Osv,omitempty"`
	Ext8                 string            `protobuf:"bytes,80,opt,name=ext8,proto3" json:"ext8,omitempty"`
	UnitId               int64             `protobuf:"varint,82,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	MAppId               int64             `protobuf:"varint,83,opt,name=MAppId,proto3" json:"MAppId,omitempty"`
	PublisherId          int64             `protobuf:"varint,84,opt,name=PublisherId,proto3" json:"PublisherId,omitempty"`
	Category             int64             `protobuf:"varint,85,opt,name=Category,proto3" json:"Category,omitempty"`
	PriceFloor           float64           `protobuf:"fixed64,90,opt,name=PriceFloor,proto3" json:"PriceFloor,omitempty"`
	RequestType          int64             `protobuf:"varint,91,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
	Device               *Device           `protobuf:"bytes,92,opt,name=device,proto3" json:"device,omitempty"`
	PackageNameBlackList []string          `protobuf:"bytes,93,rep,name=PackageNameBlackList,proto3" json:"PackageNameBlackList,omitempty"`
	AdSource             []int64           `protobuf:"varint,94,rep,packed,name=AdSource,proto3" json:"AdSource,omitempty"`
	NeedApkLandingPage   bool              `protobuf:"varint,96,opt,name=NeedApkLandingPage,proto3" json:"NeedApkLandingPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JunoRequest) Reset()         { *m = JunoRequest{} }
func (m *JunoRequest) String() string { return proto.CompactTextString(m) }
func (*JunoRequest) ProtoMessage()    {}
func (*JunoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_e42acdf1441e3359, []int{0}
}
func (m *JunoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunoRequest.Unmarshal(m, b)
}
func (m *JunoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunoRequest.Marshal(b, m, deterministic)
}
func (dst *JunoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunoRequest.Merge(dst, src)
}
func (m *JunoRequest) XXX_Size() int {
	return xxx_messageInfo_JunoRequest.Size(m)
}
func (m *JunoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JunoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JunoRequest proto.InternalMessageInfo

func (m *JunoRequest) GetBaserequest() *base.BaseRequest {
	if m != nil {
		return m.Baserequest
	}
	return nil
}

func (m *JunoRequest) GetClientLable() string {
	if m != nil {
		return m.ClientLable
	}
	return ""
}

func (m *JunoRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *JunoRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *JunoRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *JunoRequest) GetPkgName() string {
	if m != nil {
		return m.PkgName
	}
	return ""
}

func (m *JunoRequest) GetAdType() string {
	if m != nil {
		return m.AdType
	}
	return ""
}

func (m *JunoRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *JunoRequest) GetOsNum() int32 {
	if m != nil {
		return m.OsNum
	}
	return 0
}

func (m *JunoRequest) GetDeviceLanguage() string {
	if m != nil {
		return m.DeviceLanguage
	}
	return ""
}

func (m *JunoRequest) GetHttps() bool {
	if m != nil {
		return m.Https
	}
	return false
}

func (m *JunoRequest) GetBcat() []string {
	if m != nil {
		return m.Bcat
	}
	return nil
}

func (m *JunoRequest) GetAdvertiserWhiteList() []string {
	if m != nil {
		return m.AdvertiserWhiteList
	}
	return nil
}

func (m *JunoRequest) GetAdvertiserBlackList() []string {
	if m != nil {
		return m.AdvertiserBlackList
	}
	return nil
}

func (m *JunoRequest) GetBlockIndustryIds() []int64 {
	if m != nil {
		return m.BlockIndustryIds
	}
	return nil
}

func (m *JunoRequest) GetBlockClickType() []int64 {
	if m != nil {
		return m.BlockClickType
	}
	return nil
}

func (m *JunoRequest) GetDevImpLimit() bool {
	if m != nil {
		return m.DevImpLimit
	}
	return false
}

func (m *JunoRequest) GetBadv() []string {
	if m != nil {
		return m.Badv
	}
	return nil
}

func (m *JunoRequest) GetNetWorkType() int32 {
	if m != nil {
		return m.NetWorkType
	}
	return 0
}

func (m *JunoRequest) GetRequestGender() int32 {
	if m != nil {
		return m.RequestGender
	}
	return 0
}

func (m *JunoRequest) GetUserAge() int32 {
	if m != nil {
		return m.UserAge
	}
	return 0
}

func (m *JunoRequest) GetCoppa() int32 {
	if m != nil {
		return m.Coppa
	}
	return 0
}

func (m *JunoRequest) GetWhiteOfferList() []int64 {
	if m != nil {
		return m.WhiteOfferList
	}
	return nil
}

func (m *JunoRequest) GetBlackOfferList() []int64 {
	if m != nil {
		return m.BlackOfferList
	}
	return nil
}

func (m *JunoRequest) GetForbidApk() bool {
	if m != nil {
		return m.ForbidApk
	}
	return false
}

func (m *JunoRequest) GetBSubCategorySDK() []int32 {
	if m != nil {
		return m.BSubCategorySDK
	}
	return nil
}

func (m *JunoRequest) GetIabCategory() []string {
	if m != nil {
		return m.IabCategory
	}
	return nil
}

func (m *JunoRequest) GetIfSupportDeepLink() bool {
	if m != nil {
		return m.IfSupportDeepLink
	}
	return false
}

func (m *JunoRequest) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *JunoRequest) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *JunoRequest) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *JunoRequest) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *JunoRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *JunoRequest) GetHwv() string {
	if m != nil {
		return m.Hwv
	}
	return ""
}

func (m *JunoRequest) GetBundle() string {
	if m != nil {
		return m.Bundle
	}
	return ""
}

func (m *JunoRequest) GetTrafficType() string {
	if m != nil {
		return m.TrafficType
	}
	return ""
}

func (m *JunoRequest) GetAppSite() string {
	if m != nil {
		return m.AppSite
	}
	return ""
}

func (m *JunoRequest) GetMvAppId() string {
	if m != nil {
		return m.MvAppId
	}
	return ""
}

func (m *JunoRequest) GetBApp() []string {
	if m != nil {
		return m.BApp
	}
	return nil
}

func (m *JunoRequest) GetBAppCategory() []string {
	if m != nil {
		return m.BAppCategory
	}
	return nil
}

func (m *JunoRequest) GetBAppSubCategory() []string {
	if m != nil {
		return m.BAppSubCategory
	}
	return nil
}

func (m *JunoRequest) GetBSubCategoryName() []string {
	if m != nil {
		return m.BSubCategoryName
	}
	return nil
}

func (m *JunoRequest) GetNeedAdvAudit() bool {
	if m != nil {
		return m.NeedAdvAudit
	}
	return false
}

func (m *JunoRequest) GetNeedCreativeAudit() bool {
	if m != nil {
		return m.NeedCreativeAudit
	}
	return false
}

func (m *JunoRequest) GetNeedSearchCpc() bool {
	if m != nil {
		return m.NeedSearchCpc
	}
	return false
}

func (m *JunoRequest) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

func (m *JunoRequest) GetDebugCampaignIdList() []int64 {
	if m != nil {
		return m.DebugCampaignIdList
	}
	return nil
}

func (m *JunoRequest) GetBlockAuditIndustryId() []int64 {
	if m != nil {
		return m.BlockAuditIndustryId
	}
	return nil
}

func (m *JunoRequest) GetManualPosId() string {
	if m != nil {
		return m.ManualPosId
	}
	return ""
}

func (m *JunoRequest) GetOsv() int32 {
	if m != nil {
		return m.Osv
	}
	return 0
}

func (m *JunoRequest) GetExt8() string {
	if m != nil {
		return m.Ext8
	}
	return ""
}

func (m *JunoRequest) GetUnitId() int64 {
	if m != nil {
		return m.UnitId
	}
	return 0
}

func (m *JunoRequest) GetMAppId() int64 {
	if m != nil {
		return m.MAppId
	}
	return 0
}

func (m *JunoRequest) GetPublisherId() int64 {
	if m != nil {
		return m.PublisherId
	}
	return 0
}

func (m *JunoRequest) GetCategory() int64 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *JunoRequest) GetPriceFloor() float64 {
	if m != nil {
		return m.PriceFloor
	}
	return 0
}

func (m *JunoRequest) GetRequestType() int64 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

func (m *JunoRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *JunoRequest) GetPackageNameBlackList() []string {
	if m != nil {
		return m.PackageNameBlackList
	}
	return nil
}

func (m *JunoRequest) GetAdSource() []int64 {
	if m != nil {
		return m.AdSource
	}
	return nil
}

func (m *JunoRequest) GetNeedApkLandingPage() bool {
	if m != nil {
		return m.NeedApkLandingPage
	}
	return false
}

type Device struct {
	Network              int32            `protobuf:"varint,1,opt,name=Network,proto3" json:"Network,omitempty"`
	SdkVersion           string           `protobuf:"bytes,2,opt,name=SdkVersion,proto3" json:"SdkVersion,omitempty"`
	AudienceIds          []int64          `protobuf:"varint,8,rep,packed,name=AudienceIds,proto3" json:"AudienceIds,omitempty"`
	RuleIds              []string         `protobuf:"bytes,9,rep,name=RuleIds,proto3" json:"RuleIds,omitempty"`
	Deviceids            *base.FDeviceIds `protobuf:"bytes,10,opt,name=deviceids,proto3" json:"deviceids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_e42acdf1441e3359, []int{1}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetNetwork() int32 {
	if m != nil {
		return m.Network
	}
	return 0
}

func (m *Device) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *Device) GetAudienceIds() []int64 {
	if m != nil {
		return m.AudienceIds
	}
	return nil
}

func (m *Device) GetRuleIds() []string {
	if m != nil {
		return m.RuleIds
	}
	return nil
}

func (m *Device) GetDeviceids() *base.FDeviceIds {
	if m != nil {
		return m.Deviceids
	}
	return nil
}

// RankerResponse defines the dsp ranker response structure
// 暂时从11开始，1-9留着标准化用,1返回服务状态
type JunoResponse struct {
	Baseresponse            *base.BaseResponse  `protobuf:"bytes,1,opt,name=baseresponse,proto3" json:"baseresponse,omitempty"`
	SearchResultListWithTag []*JunoSearchResult `protobuf:"bytes,3,rep,name=SearchResultListWithTag,proto3" json:"SearchResultListWithTag,omitempty"`
	Ext8                    string              `protobuf:"bytes,4,opt,name=Ext8,proto3" json:"Ext8,omitempty"`
	InstallApps             []int64             `protobuf:"varint,10,rep,packed,name=installApps,proto3" json:"installApps,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}            `json:"-"`
	XXX_unrecognized        []byte              `json:"-"`
	XXX_sizecache           int32               `json:"-"`
}

func (m *JunoResponse) Reset()         { *m = JunoResponse{} }
func (m *JunoResponse) String() string { return proto.CompactTextString(m) }
func (*JunoResponse) ProtoMessage()    {}
func (*JunoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_e42acdf1441e3359, []int{2}
}
func (m *JunoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunoResponse.Unmarshal(m, b)
}
func (m *JunoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunoResponse.Marshal(b, m, deterministic)
}
func (dst *JunoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunoResponse.Merge(dst, src)
}
func (m *JunoResponse) XXX_Size() int {
	return xxx_messageInfo_JunoResponse.Size(m)
}
func (m *JunoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JunoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JunoResponse proto.InternalMessageInfo

func (m *JunoResponse) GetBaseresponse() *base.BaseResponse {
	if m != nil {
		return m.Baseresponse
	}
	return nil
}

func (m *JunoResponse) GetSearchResultListWithTag() []*JunoSearchResult {
	if m != nil {
		return m.SearchResultListWithTag
	}
	return nil
}

func (m *JunoResponse) GetExt8() string {
	if m != nil {
		return m.Ext8
	}
	return ""
}

func (m *JunoResponse) GetInstallApps() []int64 {
	if m != nil {
		return m.InstallApps
	}
	return nil
}

// juno返回的单子对象
type JunoSearchResult struct {
	CampaignId           int64    `protobuf:"varint,1,opt,name=CampaignId,proto3" json:"CampaignId,omitempty"`
	GivingPrice          float64  `protobuf:"fixed64,3,opt,name=givingPrice,proto3" json:"givingPrice,omitempty"`
	TryNewRate           float32  `protobuf:"fixed32,7,opt,name=tryNewRate,proto3" json:"tryNewRate,omitempty"`
	TryNewPriceRate      float32  `protobuf:"fixed32,8,opt,name=tryNewPriceRate,proto3" json:"tryNewPriceRate,omitempty"`
	RecallTypes          []string `protobuf:"bytes,9,rep,name=recallTypes,proto3" json:"recallTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JunoSearchResult) Reset()         { *m = JunoSearchResult{} }
func (m *JunoSearchResult) String() string { return proto.CompactTextString(m) }
func (*JunoSearchResult) ProtoMessage()    {}
func (*JunoSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_juno_e42acdf1441e3359, []int{3}
}
func (m *JunoSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunoSearchResult.Unmarshal(m, b)
}
func (m *JunoSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunoSearchResult.Marshal(b, m, deterministic)
}
func (dst *JunoSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunoSearchResult.Merge(dst, src)
}
func (m *JunoSearchResult) XXX_Size() int {
	return xxx_messageInfo_JunoSearchResult.Size(m)
}
func (m *JunoSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JunoSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_JunoSearchResult proto.InternalMessageInfo

func (m *JunoSearchResult) GetCampaignId() int64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *JunoSearchResult) GetGivingPrice() float64 {
	if m != nil {
		return m.GivingPrice
	}
	return 0
}

func (m *JunoSearchResult) GetTryNewRate() float32 {
	if m != nil {
		return m.TryNewRate
	}
	return 0
}

func (m *JunoSearchResult) GetTryNewPriceRate() float32 {
	if m != nil {
		return m.TryNewPriceRate
	}
	return 0
}

func (m *JunoSearchResult) GetRecallTypes() []string {
	if m != nil {
		return m.RecallTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*JunoRequest)(nil), "juno.JunoRequest")
	proto.RegisterType((*Device)(nil), "juno.Device")
	proto.RegisterType((*JunoResponse)(nil), "juno.JunoResponse")
	proto.RegisterType((*JunoSearchResult)(nil), "juno.JunoSearchResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JunoServiceClient is the client API for JunoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JunoServiceClient interface {
	JunoSearch(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error)
}

type junoServiceClient struct {
	cc *grpc.ClientConn
}

func NewJunoServiceClient(cc *grpc.ClientConn) JunoServiceClient {
	return &junoServiceClient{cc}
}

func (c *junoServiceClient) JunoSearch(ctx context.Context, in *JunoRequest, opts ...grpc.CallOption) (*JunoResponse, error) {
	out := new(JunoResponse)
	err := c.cc.Invoke(ctx, "/juno.JunoService/junoSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JunoServiceServer is the server API for JunoService service.
type JunoServiceServer interface {
	JunoSearch(context.Context, *JunoRequest) (*JunoResponse, error)
}

func RegisterJunoServiceServer(s *grpc.Server, srv JunoServiceServer) {
	s.RegisterService(&_JunoService_serviceDesc, srv)
}

func _JunoService_JunoSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServiceServer).JunoSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.JunoService/JunoSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServiceServer).JunoSearch(ctx, req.(*JunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JunoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "juno.JunoService",
	HandlerType: (*JunoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "junoSearch",
			Handler:    _JunoService_JunoSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juno/juno.proto",
}

func init() { proto.RegisterFile("juno/juno.proto", fileDescriptor_juno_e42acdf1441e3359) }

var fileDescriptor_juno_e42acdf1441e3359 = []byte{
	// 1257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x56, 0x6d, 0x73, 0x1b, 0xb5,
	0x13, 0x1f, 0xc7, 0x4d, 0x9a, 0xc8, 0x69, 0x93, 0xea, 0xdf, 0x7f, 0x2b, 0x42, 0x29, 0x26, 0x94,
	0x62, 0x4a, 0x9b, 0x30, 0xe9, 0x50, 0xca, 0xd3, 0x30, 0x67, 0xa7, 0xa5, 0x86, 0x3c, 0x78, 0xce,
	0x29, 0x9d, 0x29, 0x0f, 0x83, 0x7c, 0xda, 0x5c, 0x54, 0x5f, 0xee, 0x84, 0x4e, 0xe7, 0x34, 0x5f,
	0x8a, 0xcf, 0xc0, 0x4b, 0x5e, 0xf1, 0x99, 0x98, 0x5d, 0x9d, 0xed, 0xb3, 0x13, 0xde, 0xd8, 0xfa,
	0xfd, 0x76, 0x25, 0xdd, 0xee, 0xfe, 0x56, 0x12, 0x5b, 0x7b, 0x53, 0xa4, 0xd9, 0x36, 0xfe, 0x6c,
	0x19, 0x9b, 0xb9, 0x8c, 0x5f, 0xc1, 0xf1, 0xc6, 0xda, 0x40, 0xe6, 0xb0, 0x8d, 0x3f, 0x9e, 0xde,
	0xfc, 0x7b, 0x8d, 0x35, 0x7e, 0x28, 0xd2, 0x2c, 0x84, 0x3f, 0x0a, 0xc8, 0x1d, 0x7f, 0xcc, 0x1a,
	0x68, 0xb5, 0x1e, 0x8a, 0x5a, 0xb3, 0xd6, 0x6a, 0xec, 0xdc, 0xd8, 0xa2, 0x19, 0x6d, 0x99, 0x43,
	0xe9, 0x17, 0x56, 0xbd, 0x78, 0x93, 0x35, 0xa2, 0x44, 0x43, 0xea, 0xf6, 0xe4, 0x20, 0x01, 0xb1,
	0xd0, 0xac, 0xb5, 0x56, 0xc2, 0x2a, 0xc5, 0x37, 0xd8, 0xf2, 0xb3, 0xb7, 0xd1, 0x89, 0x4c, 0x63,
	0x10, 0x8c, 0xcc, 0x13, 0xcc, 0xaf, 0xb3, 0x85, 0xc3, 0x5c, 0x34, 0x88, 0x5d, 0x38, 0xcc, 0xb9,
	0x60, 0x57, 0x3b, 0x59, 0x91, 0x3a, 0x7b, 0x2e, 0x56, 0x89, 0x1c, 0x43, 0xb4, 0xf4, 0x86, 0xf1,
	0x81, 0x3c, 0x05, 0x71, 0xcd, 0x5b, 0x4a, 0xc8, 0x6f, 0xb1, 0xa5, 0x40, 0x1d, 0x9d, 0x1b, 0x10,
	0xd7, 0xc9, 0x50, 0x22, 0x7e, 0x93, 0x2d, 0x06, 0xc6, 0x74, 0x95, 0xe0, 0x44, 0x7b, 0x80, 0xec,
	0x61, 0x7e, 0x50, 0x9c, 0x8a, 0x9b, 0xcd, 0x5a, 0x6b, 0x31, 0xf4, 0x80, 0xdf, 0x67, 0xd7, 0x77,
	0x61, 0xa4, 0x23, 0xd8, 0x93, 0x69, 0x5c, 0xc8, 0x18, 0xc4, 0xff, 0x69, 0xd2, 0x1c, 0x8b, 0xb3,
	0x5f, 0x38, 0x67, 0x72, 0x71, 0xab, 0x59, 0x6b, 0x2d, 0x87, 0x1e, 0x70, 0xce, 0xae, 0xb4, 0x23,
	0xe9, 0xc4, 0xed, 0x66, 0xbd, 0xb5, 0x12, 0xd2, 0x98, 0x7f, 0xc6, 0xfe, 0x17, 0xa8, 0x11, 0x58,
	0xa7, 0x73, 0xb0, 0xaf, 0x4e, 0xb4, 0x83, 0x3d, 0x9d, 0x3b, 0x21, 0xc8, 0xe5, 0x32, 0xd3, 0xec,
	0x8c, 0x76, 0x22, 0xa3, 0x21, 0xcd, 0x78, 0x67, 0x7e, 0xc6, 0xc4, 0xc4, 0x1f, 0xb0, 0xf5, 0x76,
	0x92, 0x45, 0xc3, 0x6e, 0xaa, 0x8a, 0xdc, 0xd9, 0xf3, 0xae, 0xca, 0xc5, 0x46, 0xb3, 0xde, 0xaa,
	0x87, 0x17, 0x78, 0x8c, 0x90, 0xb8, 0x4e, 0xa2, 0xa3, 0x21, 0x65, 0xeb, 0x5d, 0xf2, 0x9c, 0x63,
	0xb1, 0x9e, 0xbb, 0x30, 0xea, 0x9e, 0x9a, 0x3d, 0x7d, 0xaa, 0x9d, 0xb8, 0x43, 0x71, 0x56, 0x29,
	0x8a, 0x56, 0xaa, 0x91, 0x78, 0xaf, 0x8c, 0x56, 0xaa, 0x11, 0xce, 0x3a, 0x00, 0xf7, 0x2a, 0xb3,
	0x7e, 0xe9, 0xbb, 0x94, 0xdb, 0x2a, 0xc5, 0xef, 0xb1, 0x6b, 0xa5, 0x7e, 0xbe, 0x87, 0x54, 0x81,
	0x15, 0xef, 0x93, 0xcf, 0x2c, 0x89, 0x55, 0x7e, 0x99, 0x83, 0x0d, 0x62, 0x10, 0x4d, 0xb2, 0x8f,
	0x21, 0x66, 0xbe, 0x93, 0x19, 0x23, 0xc5, 0x07, 0xbe, 0x6e, 0x04, 0x30, 0x2a, 0x4a, 0xe0, 0xe1,
	0xf1, 0x31, 0x58, 0x4a, 0xd7, 0xa6, 0x8f, 0x6a, 0x96, 0xf5, 0xd1, 0xcb, 0x68, 0x38, 0xf5, 0xfb,
	0x70, 0x1c, 0x7d, 0x95, 0xe5, 0x77, 0xd8, 0xca, 0xf3, 0xcc, 0x0e, 0xb4, 0x0a, 0xcc, 0x50, 0xdc,
	0xa3, 0xd8, 0xa7, 0x04, 0x6f, 0xb1, 0xb5, 0x76, 0xbf, 0x18, 0x74, 0xa4, 0x83, 0x38, 0xb3, 0xe7,
	0xfd, 0xdd, 0x1f, 0xc5, 0x47, 0xcd, 0x7a, 0x6b, 0x31, 0x9c, 0xa7, 0x31, 0x1f, 0x5d, 0x39, 0x61,
	0xc4, 0x7d, 0x4a, 0x55, 0x95, 0xe2, 0x0f, 0xd9, 0x8d, 0xee, 0x71, 0xbf, 0x30, 0x26, 0xb3, 0x6e,
	0x17, 0xc0, 0xec, 0xe9, 0x74, 0x28, 0x3e, 0xa6, 0x1d, 0x2f, 0x1a, 0xb0, 0x87, 0x3a, 0xda, 0x9d,
	0x77, 0x32, 0x05, 0xa2, 0xe5, 0x7b, 0x68, 0x8c, 0xa9, 0x67, 0xa4, 0xb5, 0x1a, 0xac, 0xf8, 0xa4,
	0xec, 0x19, 0x0f, 0xb1, 0x52, 0xfb, 0x72, 0x08, 0xe2, 0x01, 0xd1, 0x34, 0xe6, 0x77, 0x19, 0xf3,
	0x9a, 0xa6, 0x42, 0x7d, 0x4a, 0xc9, 0xac, 0x30, 0x98, 0xe7, 0xfd, 0x4c, 0x41, 0x22, 0x1e, 0xfa,
	0xae, 0x21, 0xc0, 0xd7, 0x59, 0xfd, 0xc5, 0xd9, 0x48, 0x3c, 0x22, 0x0e, 0x87, 0xd8, 0x75, 0xed,
	0x22, 0x55, 0x09, 0x88, 0x2d, 0xdf, 0x75, 0x1e, 0x61, 0xe4, 0x47, 0x56, 0x1e, 0x1f, 0xeb, 0x88,
	0x36, 0xf8, 0xdc, 0x9f, 0x07, 0x15, 0x0a, 0xbf, 0x37, 0x30, 0xa6, 0xaf, 0x1d, 0x88, 0x27, 0xfe,
	0x7b, 0x4b, 0x88, 0x96, 0xfd, 0x91, 0xef, 0xd9, 0x2f, 0xbc, 0xa5, 0x84, 0xa4, 0xb9, 0xc0, 0x18,
	0xf1, 0xb4, 0xd4, 0x5c, 0x60, 0x0c, 0xdf, 0x64, 0xab, 0xf8, 0x3f, 0x49, 0xf2, 0x97, 0x64, 0x9b,
	0xe1, 0xa8, 0x62, 0xb8, 0xfa, 0xb4, 0x3a, 0xe2, 0x2b, 0x72, 0x9b, 0xa7, 0xa9, 0x97, 0x2a, 0x98,
	0x0e, 0x9a, 0xaf, 0xc9, 0xf5, 0x02, 0x8f, 0x3b, 0x1f, 0x00, 0xa8, 0x40, 0x8d, 0x82, 0x42, 0x69,
	0x27, 0xbe, 0xa1, 0xb2, 0xcd, 0x70, 0x58, 0x5f, 0xc4, 0x1d, 0x0b, 0xd2, 0xe9, 0x11, 0x78, 0xc7,
	0x6f, 0x7d, 0x7d, 0x2f, 0x18, 0xb0, 0x3b, 0x90, 0xec, 0x83, 0xb4, 0xd1, 0x49, 0xc7, 0x44, 0xe2,
	0x3b, 0xf2, 0x9c, 0x25, 0xb1, 0x36, 0x47, 0x32, 0xee, 0x2a, 0x11, 0xf8, 0xda, 0x10, 0xc0, 0x73,
	0x63, 0x17, 0x06, 0x45, 0xdc, 0x91, 0xa7, 0x46, 0xea, 0x38, 0xed, 0x2a, 0x12, 0x78, 0x9b, 0x04,
	0x7e, 0x99, 0x89, 0xef, 0xb0, 0x9b, 0xd4, 0xf5, 0xb4, 0xf7, 0xf4, 0x90, 0x10, 0x1d, 0x9a, 0x72,
	0xa9, 0x0d, 0xeb, 0xba, 0x2f, 0xd3, 0x42, 0x26, 0xbd, 0x2c, 0xef, 0x2a, 0xb1, 0xeb, 0xeb, 0x5a,
	0xa1, 0x50, 0x23, 0x87, 0xf9, 0x48, 0x3c, 0x23, 0x49, 0xe1, 0x10, 0xab, 0x06, 0x6f, 0xdd, 0x53,
	0xd1, 0xf3, 0xfa, 0xc3, 0x31, 0xea, 0xe6, 0x65, 0xaa, 0x5d, 0x57, 0x89, 0xb0, 0x59, 0x6b, 0xd5,
	0xc3, 0x12, 0x21, 0xbf, 0xef, 0x4b, 0xdf, 0xf7, 0xbc, 0x47, 0xb8, 0x6f, 0xaf, 0x18, 0x24, 0x3a,
	0x3f, 0x01, 0xdb, 0x55, 0xe2, 0x88, 0x8c, 0x55, 0x8a, 0x7a, 0x63, 0x5c, 0xdc, 0x97, 0x64, 0x9e,
	0x60, 0x54, 0x7b, 0xcf, 0xea, 0x08, 0x9e, 0x27, 0x59, 0x66, 0xc5, 0xeb, 0x66, 0xad, 0x55, 0x0b,
	0x2b, 0x0c, 0xae, 0x5e, 0x1e, 0x40, 0xa4, 0xd6, 0x9f, 0xfd, 0xea, 0x15, 0x8a, 0xdf, 0x63, 0x4b,
	0x8a, 0xba, 0x43, 0xfc, 0x42, 0xf7, 0xe1, 0xea, 0x16, 0x5d, 0xac, 0xbe, 0x63, 0xc2, 0xd2, 0x86,
	0x19, 0xed, 0xc9, 0x68, 0x28, 0x63, 0x40, 0x81, 0x4c, 0x0f, 0xef, 0x5f, 0x49, 0x41, 0x97, 0xda,
	0xf0, 0xbb, 0x03, 0xd5, 0xcf, 0x0a, 0x1b, 0x81, 0xf8, 0x8d, 0x32, 0x3f, 0xc1, 0x7c, 0x8b, 0x71,
	0x52, 0x93, 0x19, 0xee, 0xc9, 0x54, 0xe9, 0x34, 0xee, 0xe1, 0x9d, 0xf4, 0x3b, 0x89, 0xe2, 0x12,
	0xcb, 0xe6, 0x9f, 0x35, 0xb6, 0xe4, 0x3f, 0x09, 0x9b, 0xe8, 0x00, 0xdc, 0x59, 0x66, 0x87, 0x74,
	0x83, 0x2f, 0x86, 0x63, 0x88, 0xc9, 0xe8, 0xab, 0xe1, 0x4f, 0x60, 0x73, 0x9d, 0xa5, 0xe5, 0x4d,
	0x5d, 0x61, 0x30, 0x19, 0x58, 0x75, 0x48, 0x23, 0xc0, 0x9b, 0x64, 0x99, 0xbe, 0xa9, 0x4a, 0xe1,
	0xda, 0x61, 0x91, 0x90, 0x75, 0x85, 0x22, 0x1b, 0x43, 0xbe, 0xc5, 0x56, 0x7c, 0x2a, 0xb4, 0xca,
	0xe9, 0x96, 0x6f, 0xec, 0xac, 0xfb, 0x97, 0xc3, 0x73, 0xff, 0x5d, 0x5d, 0x95, 0x87, 0x53, 0x97,
	0xcd, 0x7f, 0x6a, 0x6c, 0xd5, 0xbf, 0x3d, 0x72, 0x93, 0xa5, 0x39, 0xf0, 0x27, 0x6c, 0xd5, 0x3f,
	0x2b, 0x3c, 0x2e, 0x5f, 0x1f, 0xbc, 0xfa, 0xfa, 0xf0, 0x96, 0x70, 0xc6, 0x8f, 0xf7, 0xd8, 0x6d,
	0xdf, 0x20, 0x21, 0xe4, 0x45, 0xe2, 0x30, 0xb3, 0xaf, 0xb4, 0x3b, 0x39, 0x92, 0xb1, 0xa8, 0x37,
	0xeb, 0xad, 0xc6, 0xce, 0x2d, 0x5f, 0x30, 0xdc, 0xac, 0xea, 0x18, 0xfe, 0xd7, 0x34, 0x54, 0xed,
	0x33, 0x54, 0xed, 0x15, 0xaf, 0x5a, 0x1c, 0x63, 0x6a, 0x74, 0x9a, 0x3b, 0x99, 0x24, 0x81, 0x31,
	0x18, 0x20, 0xa5, 0xa6, 0x42, 0x6d, 0xfe, 0x55, 0x63, 0xeb, 0xf3, 0x7b, 0x60, 0xc6, 0xa7, 0xad,
	0x47, 0x21, 0xd5, 0xc3, 0x0a, 0x83, 0xcb, 0xc6, 0x7a, 0x84, 0x45, 0x44, 0x49, 0x8a, 0x3a, 0xe9,
	0xb3, 0x4a, 0xe1, 0x0a, 0xce, 0x9e, 0x1f, 0xc0, 0x59, 0x28, 0x1d, 0x88, 0xab, 0xcd, 0x5a, 0x6b,
	0x21, 0xac, 0x30, 0x78, 0xc0, 0x79, 0x44, 0xee, 0xe4, 0xb4, 0x4c, 0x4e, 0xf3, 0x34, 0xee, 0x65,
	0x21, 0x92, 0x49, 0x82, 0xb2, 0x1e, 0xd7, 0xaf, 0x4a, 0xed, 0xb4, 0xfd, 0x73, 0xb0, 0x0f, 0x96,
	0x84, 0xf4, 0x98, 0xb1, 0x37, 0x93, 0x80, 0xf8, 0x8d, 0x69, 0x1a, 0xcb, 0xf6, 0xd8, 0xe0, 0x55,
	0xca, 0x97, 0xa3, 0x7d, 0xe7, 0xf5, 0x86, 0xca, 0xcd, 0x23, 0x07, 0xa7, 0x26, 0x91, 0x0e, 0xb6,
	0xa5, 0xd1, 0xdb, 0x93, 0xe7, 0xe8, 0x60, 0x89, 0x1e, 0x9e, 0x8f, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0x8f, 0xa5, 0xc3, 0xa2, 0x0a, 0x00, 0x00,
}
