// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/base.proto

package base

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusBase int32

const (
	StatusBase_Default StatusBase = 0
	StatusBase_Success StatusBase = 1
	StatusBase_Fail    StatusBase = 2
)

var StatusBase_name = map[int32]string{
	0: "Default",
	1: "Success",
	2: "Fail",
}
var StatusBase_value = map[string]int32{
	"Default": 0,
	"Success": 1,
	"Fail":    2,
}

func (x StatusBase) String() string {
	return proto.EnumName(StatusBase_name, int32(x))
}
func (StatusBase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_base_ed8b45405af0071e, []int{0}
}

// -----被调用 rpc 服务 推荐集成 context
type BaseRequest struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Abtest               map[string]string `protobuf:"bytes,3,rep,name=abtest,proto3" json:"abtest,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Debug                bool              `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	Openlog              bool              `protobuf:"varint,5,opt,name=openlog,proto3" json:"openlog,omitempty"`
	Tmax                 int64             `protobuf:"varint,6,opt,name=tmax,proto3" json:"tmax,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ed8b45405af0071e, []int{0}
}
func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (dst *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(dst, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseRequest) GetAbtest() map[string]string {
	if m != nil {
		return m.Abtest
	}
	return nil
}

func (m *BaseRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *BaseRequest) GetOpenlog() bool {
	if m != nil {
		return m.Openlog
	}
	return false
}

func (m *BaseRequest) GetTmax() int64 {
	if m != nil {
		return m.Tmax
	}
	return 0
}

// 被调服务 timeout 或其他异常情况，可以选填 部分字段 返回上一层
type BaseResponse struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Status               StatusBase        `protobuf:"varint,2,opt,name=status,proto3,enum=base.StatusBase" json:"status,omitempty"`
	Elapsed              int64             `protobuf:"varint,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Abtested             map[string]string `protobuf:"bytes,4,rep,name=abtested,proto3" json:"abtested,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Debugmsg             map[string]string `protobuf:"bytes,5,rep,name=debugmsg,proto3" json:"debugmsg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Errormsg             string            `protobuf:"bytes,6,opt,name=errormsg,proto3" json:"errormsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ed8b45405af0071e, []int{1}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseResponse) GetStatus() StatusBase {
	if m != nil {
		return m.Status
	}
	return StatusBase_Default
}

func (m *BaseResponse) GetElapsed() int64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *BaseResponse) GetAbtested() map[string]string {
	if m != nil {
		return m.Abtested
	}
	return nil
}

func (m *BaseResponse) GetDebugmsg() map[string]string {
	if m != nil {
		return m.Debugmsg
	}
	return nil
}

func (m *BaseResponse) GetErrormsg() string {
	if m != nil {
		return m.Errormsg
	}
	return ""
}

// ----- metrics
type BaseMetrics struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subsystem            string   `protobuf:"bytes,4,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMetrics) Reset()         { *m = BaseMetrics{} }
func (m *BaseMetrics) String() string { return proto.CompactTextString(m) }
func (*BaseMetrics) ProtoMessage()    {}
func (*BaseMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ed8b45405af0071e, []int{2}
}
func (m *BaseMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMetrics.Unmarshal(m, b)
}
func (m *BaseMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMetrics.Marshal(b, m, deterministic)
}
func (dst *BaseMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMetrics.Merge(dst, src)
}
func (m *BaseMetrics) XXX_Size() int {
	return xxx_messageInfo_BaseMetrics.Size(m)
}
func (m *BaseMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMetrics proto.InternalMessageInfo

func (m *BaseMetrics) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *BaseMetrics) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseMetrics) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BaseMetrics) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

// ----- feature
type FDeviceIds struct {
	Googleadid           string   `protobuf:"bytes,1,opt,name=googleadid,proto3" json:"googleadid,omitempty"`
	Idfa                 string   `protobuf:"bytes,2,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Googleadidmd5        string   `protobuf:"bytes,3,opt,name=googleadidmd5,proto3" json:"googleadidmd5,omitempty"`
	Googleadidsh1        string   `protobuf:"bytes,4,opt,name=googleadidsh1,proto3" json:"googleadidsh1,omitempty"`
	Imei                 string   `protobuf:"bytes,5,opt,name=imei,proto3" json:"imei,omitempty"`
	Imeimd5              string   `protobuf:"bytes,6,opt,name=imeimd5,proto3" json:"imeimd5,omitempty"`
	Imeisha1             string   `protobuf:"bytes,7,opt,name=imeisha1,proto3" json:"imeisha1,omitempty"`
	Androidid            string   `protobuf:"bytes,8,opt,name=androidid,proto3" json:"androidid,omitempty"`
	Androididmd5         string   `protobuf:"bytes,9,opt,name=androididmd5,proto3" json:"androididmd5,omitempty"`
	Androididsha1        string   `protobuf:"bytes,10,opt,name=androididsha1,proto3" json:"androididsha1,omitempty"`
	Oaid                 string   `protobuf:"bytes,11,opt,name=oaid,proto3" json:"oaid,omitempty"`
	Oaidmd5              string   `protobuf:"bytes,12,opt,name=oaidmd5,proto3" json:"oaidmd5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FDeviceIds) Reset()         { *m = FDeviceIds{} }
func (m *FDeviceIds) String() string { return proto.CompactTextString(m) }
func (*FDeviceIds) ProtoMessage()    {}
func (*FDeviceIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ed8b45405af0071e, []int{3}
}
func (m *FDeviceIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FDeviceIds.Unmarshal(m, b)
}
func (m *FDeviceIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FDeviceIds.Marshal(b, m, deterministic)
}
func (dst *FDeviceIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FDeviceIds.Merge(dst, src)
}
func (m *FDeviceIds) XXX_Size() int {
	return xxx_messageInfo_FDeviceIds.Size(m)
}
func (m *FDeviceIds) XXX_DiscardUnknown() {
	xxx_messageInfo_FDeviceIds.DiscardUnknown(m)
}

var xxx_messageInfo_FDeviceIds proto.InternalMessageInfo

func (m *FDeviceIds) GetGoogleadid() string {
	if m != nil {
		return m.Googleadid
	}
	return ""
}

func (m *FDeviceIds) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *FDeviceIds) GetGoogleadidmd5() string {
	if m != nil {
		return m.Googleadidmd5
	}
	return ""
}

func (m *FDeviceIds) GetGoogleadidsh1() string {
	if m != nil {
		return m.Googleadidsh1
	}
	return ""
}

func (m *FDeviceIds) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *FDeviceIds) GetImeimd5() string {
	if m != nil {
		return m.Imeimd5
	}
	return ""
}

func (m *FDeviceIds) GetImeisha1() string {
	if m != nil {
		return m.Imeisha1
	}
	return ""
}

func (m *FDeviceIds) GetAndroidid() string {
	if m != nil {
		return m.Androidid
	}
	return ""
}

func (m *FDeviceIds) GetAndroididmd5() string {
	if m != nil {
		return m.Androididmd5
	}
	return ""
}

func (m *FDeviceIds) GetAndroididsha1() string {
	if m != nil {
		return m.Androididsha1
	}
	return ""
}

func (m *FDeviceIds) GetOaid() string {
	if m != nil {
		return m.Oaid
	}
	return ""
}

func (m *FDeviceIds) GetOaidmd5() string {
	if m != nil {
		return m.Oaidmd5
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "base.BaseRequest")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseRequest.AbtestEntry")
	proto.RegisterType((*BaseResponse)(nil), "base.BaseResponse")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseResponse.AbtestedEntry")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseResponse.DebugmsgEntry")
	proto.RegisterType((*BaseMetrics)(nil), "base.BaseMetrics")
	proto.RegisterType((*FDeviceIds)(nil), "base.FDeviceIds")
	proto.RegisterEnum("base.StatusBase", StatusBase_name, StatusBase_value)
}

func init() { proto.RegisterFile("base/base.proto", fileDescriptor_base_ed8b45405af0071e) }

var fileDescriptor_base_ed8b45405af0071e = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xdb, 0x3c,
	0x10, 0xfc, 0x24, 0x3b, 0x8a, 0xb5, 0x76, 0xf2, 0x19, 0x44, 0x51, 0x10, 0x46, 0x53, 0x18, 0x46,
	0x0f, 0x46, 0x0f, 0x6e, 0x93, 0x22, 0x40, 0xff, 0x2e, 0x2d, 0xdc, 0x00, 0x39, 0xf4, 0xa2, 0x3c,
	0x40, 0x41, 0x9b, 0x1b, 0x87, 0xa8, 0x24, 0x2a, 0x22, 0x15, 0xd4, 0xef, 0xdc, 0x53, 0xd1, 0x07,
	0x28, 0x96, 0xa4, 0x65, 0x0b, 0x45, 0x0f, 0xb9, 0x24, 0x3b, 0x43, 0xce, 0xee, 0xec, 0x72, 0x65,
	0xf8, 0x7f, 0x25, 0x0c, 0xbe, 0xa2, 0x3f, 0x8b, 0xaa, 0xd6, 0x56, 0xb3, 0x3e, 0xc5, 0xb3, 0x5f,
	0x11, 0x0c, 0x3f, 0x0b, 0x83, 0x19, 0xde, 0x37, 0x68, 0x2c, 0x3b, 0x03, 0xa8, 0x7d, 0xf8, 0x4d,
	0x49, 0x1e, 0x4d, 0xa3, 0x79, 0x9a, 0xa5, 0x81, 0xb9, 0x96, 0xec, 0x14, 0x62, 0x55, 0xf1, 0xd8,
	0xd1, 0xb1, 0xaa, 0xd8, 0x25, 0x24, 0x62, 0x65, 0xd1, 0x58, 0xde, 0x9b, 0xf6, 0xe6, 0xc3, 0x8b,
	0xb3, 0x85, 0xab, 0x70, 0x90, 0x71, 0xf1, 0xc9, 0x9d, 0x7f, 0x29, 0x6d, 0xbd, 0xcd, 0xc2, 0x65,
	0xf6, 0x04, 0x8e, 0x24, 0xae, 0x9a, 0x0d, 0xef, 0x4f, 0xa3, 0xf9, 0x20, 0xf3, 0x80, 0x71, 0x38,
	0xd6, 0x15, 0x96, 0xb9, 0xde, 0xf0, 0x23, 0xc7, 0xef, 0x20, 0x63, 0xd0, 0xb7, 0x85, 0xf8, 0xc1,
	0x93, 0x69, 0x34, 0xef, 0x65, 0x2e, 0x9e, 0xbc, 0x83, 0xe1, 0x41, 0x6a, 0x36, 0x86, 0xde, 0x77,
	0xdc, 0x06, 0xc7, 0x14, 0x52, 0x91, 0x07, 0x91, 0x37, 0x18, 0xec, 0x7a, 0xf0, 0x3e, 0x7e, 0x1b,
	0xcd, 0x7e, 0xc7, 0x30, 0xf2, 0x16, 0x4d, 0xa5, 0x4b, 0x83, 0xa1, 0xad, 0xa8, 0x6d, 0x6b, 0x0e,
	0x89, 0xb1, 0xc2, 0x36, 0xc6, 0x69, 0x4f, 0x2f, 0xc6, 0xbe, 0xad, 0x1b, 0xc7, 0x39, 0x65, 0x38,
	0x27, 0xcf, 0x98, 0x8b, 0xca, 0xa0, 0xe4, 0x3d, 0x67, 0x6e, 0x07, 0xd9, 0x47, 0x18, 0xf8, 0x6e,
	0x51, 0xf2, 0xbe, 0x1b, 0xce, 0xf4, 0x70, 0x38, 0xbe, 0x72, 0x98, 0x0e, 0x4a, 0x3f, 0x9f, 0x56,
	0x41, 0x6a, 0x37, 0x94, 0xc2, 0xd0, 0x30, 0xfe, 0xa5, 0x5e, 0x86, 0x2b, 0x41, 0xbd, 0x53, 0xb0,
	0x09, 0x0c, 0xb0, 0xae, 0x75, 0x4d, 0xea, 0xc4, 0x75, 0xd5, 0xe2, 0xc9, 0x07, 0x38, 0xe9, 0x14,
	0x7d, 0xcc, 0xe4, 0x48, 0xdc, 0xa9, 0xf9, 0xa8, 0xb1, 0xdf, 0xfb, 0x55, 0xfb, 0x8a, 0xb6, 0x56,
	0x6b, 0xc3, 0x9e, 0x42, 0x52, 0xe3, 0x46, 0xe9, 0x32, 0xa8, 0x03, 0xfa, 0x6b, 0xc7, 0x9e, 0x41,
	0x5a, 0x8a, 0x02, 0x4d, 0x25, 0xd6, 0xe8, 0x86, 0x9c, 0x66, 0x7b, 0x82, 0x4e, 0x4d, 0xb3, 0x32,
	0x5b, 0x63, 0xb1, 0x70, 0xeb, 0x94, 0x66, 0x7b, 0x62, 0xf6, 0x33, 0x06, 0xb8, 0x5a, 0xe2, 0x83,
	0x5a, 0xe3, 0xb5, 0x34, 0xec, 0x39, 0xc0, 0x46, 0xeb, 0x4d, 0x8e, 0x42, 0xb6, 0xdb, 0x7d, 0xc0,
	0xd0, 0x9e, 0x29, 0x79, 0x2b, 0x42, 0x71, 0x17, 0xb3, 0x17, 0x70, 0xb2, 0xbf, 0x51, 0xc8, 0xcb,
	0x60, 0xa1, 0x4b, 0x76, 0x6f, 0x99, 0xbb, 0xf3, 0x60, 0xa5, 0x4b, 0xba, 0xfc, 0x05, 0x2a, 0xb7,
	0xde, 0x94, 0xbf, 0x40, 0x45, 0x1b, 0x44, 0xff, 0x29, 0xb3, 0x7f, 0xaa, 0x1d, 0xa4, 0x57, 0xa4,
	0xd0, 0xdc, 0x89, 0x73, 0x7e, 0xec, 0x5f, 0x71, 0x87, 0xa9, 0x6d, 0x51, 0xca, 0x5a, 0x2b, 0x6a,
	0x64, 0xe0, 0xdb, 0x6e, 0x09, 0x36, 0x83, 0x51, 0x0b, 0x28, 0x71, 0xea, 0x2e, 0x74, 0x38, 0x72,
	0xdc, 0x62, 0x57, 0x02, 0xbc, 0xe3, 0x0e, 0x49, 0x8e, 0xb5, 0x50, 0x92, 0x0f, 0xbd, 0x63, 0x8a,
	0xdd, 0x77, 0x2a, 0x7c, 0xe2, 0x91, 0x77, 0x1c, 0xe0, 0xcb, 0xd7, 0x00, 0xfb, 0x6f, 0x84, 0x0d,
	0xe1, 0x78, 0x89, 0xb7, 0xa2, 0xc9, 0xed, 0xf8, 0x3f, 0x02, 0x37, 0xcd, 0x7a, 0x8d, 0xc6, 0x8c,
	0x23, 0x36, 0x80, 0xfe, 0x95, 0x50, 0xf9, 0x38, 0x5e, 0x25, 0xee, 0xc7, 0xe8, 0xcd, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x68, 0x1c, 0x67, 0x59, 0x9f, 0x04, 0x00, 0x00,
}
