// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base // import "dsp-template/api/base/base"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusBase int32

const (
	StatusBase_Default StatusBase = 0
	StatusBase_Success StatusBase = 1
	StatusBase_Fail    StatusBase = 2
)

var StatusBase_name = map[int32]string{
	0: "Default",
	1: "Success",
	2: "Fail",
}
var StatusBase_value = map[string]int32{
	"Default": 0,
	"Success": 1,
	"Fail":    2,
}

func (x StatusBase) String() string {
	return proto.EnumName(StatusBase_name, int32(x))
}
func (StatusBase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_base_276188cf639bc297, []int{0}
}

type BaseRequest struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Abtest               map[string]string `protobuf:"bytes,3,rep,name=abtest,proto3" json:"abtest,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Debug                bool              `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	Openlog              bool              `protobuf:"varint,5,opt,name=openlog,proto3" json:"openlog,omitempty"`
	Tmax                 int64             `protobuf:"varint,6,opt,name=tmax,proto3" json:"tmax,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_276188cf639bc297, []int{0}
}
func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (dst *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(dst, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseRequest) GetAbtest() map[string]string {
	if m != nil {
		return m.Abtest
	}
	return nil
}

func (m *BaseRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *BaseRequest) GetOpenlog() bool {
	if m != nil {
		return m.Openlog
	}
	return false
}

func (m *BaseRequest) GetTmax() int64 {
	if m != nil {
		return m.Tmax
	}
	return 0
}

type BaseResponse struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Status               StatusBase        `protobuf:"varint,2,opt,name=status,proto3,enum=base.StatusBase" json:"status,omitempty"`
	Elapsed              int64             `protobuf:"varint,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Abtested             map[string]string `protobuf:"bytes,4,rep,name=abtested,proto3" json:"abtested,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Debugmsg             map[string]string `protobuf:"bytes,5,rep,name=debugmsg,proto3" json:"debugmsg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Errormsg             string            `protobuf:"bytes,6,opt,name=errormsg,proto3" json:"errormsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_276188cf639bc297, []int{1}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseResponse) GetStatus() StatusBase {
	if m != nil {
		return m.Status
	}
	return StatusBase_Default
}

func (m *BaseResponse) GetElapsed() int64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *BaseResponse) GetAbtested() map[string]string {
	if m != nil {
		return m.Abtested
	}
	return nil
}

func (m *BaseResponse) GetDebugmsg() map[string]string {
	if m != nil {
		return m.Debugmsg
	}
	return nil
}

func (m *BaseResponse) GetErrormsg() string {
	if m != nil {
		return m.Errormsg
	}
	return ""
}

type BaseMetrics struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subsystem            string   `protobuf:"bytes,4,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMetrics) Reset()         { *m = BaseMetrics{} }
func (m *BaseMetrics) String() string { return proto.CompactTextString(m) }
func (*BaseMetrics) ProtoMessage()    {}
func (*BaseMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_276188cf639bc297, []int{2}
}
func (m *BaseMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMetrics.Unmarshal(m, b)
}
func (m *BaseMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMetrics.Marshal(b, m, deterministic)
}
func (dst *BaseMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMetrics.Merge(dst, src)
}
func (m *BaseMetrics) XXX_Size() int {
	return xxx_messageInfo_BaseMetrics.Size(m)
}
func (m *BaseMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMetrics proto.InternalMessageInfo

func (m *BaseMetrics) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *BaseMetrics) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseMetrics) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BaseMetrics) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "base.BaseRequest")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseRequest.AbtestEntry")
	proto.RegisterType((*BaseResponse)(nil), "base.BaseResponse")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseResponse.AbtestedEntry")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseResponse.DebugmsgEntry")
	proto.RegisterType((*BaseMetrics)(nil), "base.BaseMetrics")
	proto.RegisterEnum("base.StatusBase", StatusBase_name, StatusBase_value)
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_base_276188cf639bc297) }

var fileDescriptor_base_276188cf639bc297 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4b, 0x8b, 0xd4, 0x40,
	0x10, 0x36, 0x8f, 0xcd, 0x4e, 0x6a, 0x74, 0x09, 0x8d, 0x48, 0x33, 0xb8, 0x18, 0xf7, 0x14, 0x04,
	0x67, 0x65, 0x45, 0x50, 0xd7, 0x8b, 0xcb, 0x2a, 0x78, 0xf0, 0x92, 0xbd, 0x79, 0x91, 0x4e, 0x52,
	0x0e, 0xc1, 0x3c, 0x7a, 0xbb, 0x3a, 0xe2, 0xfc, 0x6d, 0xf1, 0x07, 0x48, 0x3f, 0xe6, 0xb1, 0xc8,
	0x1e, 0xe6, 0xd2, 0xd4, 0xf7, 0x55, 0x7f, 0x5d, 0x55, 0x5f, 0x2a, 0x00, 0x95, 0x20, 0x5c, 0x4a,
	0x35, 0xea, 0x91, 0xc5, 0x26, 0x3e, 0xfb, 0x13, 0xc0, 0xfc, 0x4a, 0x10, 0x96, 0x78, 0x3b, 0x21,
	0x69, 0x76, 0x0a, 0xa0, 0x5c, 0xf8, 0xbd, 0x6d, 0x78, 0x90, 0x07, 0x45, 0x5a, 0xa6, 0x9e, 0xf9,
	0xd2, 0xb0, 0x13, 0x08, 0x5b, 0xc9, 0x43, 0x4b, 0x87, 0xad, 0x64, 0x6f, 0x20, 0x11, 0x95, 0x46,
	0xd2, 0x3c, 0xca, 0xa3, 0x62, 0x7e, 0x71, 0xba, 0xb4, 0x15, 0xf6, 0x5e, 0x5c, 0x7e, 0xb4, 0xf9,
	0x4f, 0x83, 0x56, 0xeb, 0xd2, 0x5f, 0x66, 0x8f, 0xe1, 0xa8, 0xc1, 0x6a, 0x5a, 0xf1, 0x38, 0x0f,
	0x8a, 0x59, 0xe9, 0x00, 0xe3, 0x70, 0x3c, 0x4a, 0x1c, 0xba, 0x71, 0xc5, 0x8f, 0x2c, 0xbf, 0x81,
	0x8c, 0x41, 0xac, 0x7b, 0xf1, 0x9b, 0x27, 0x79, 0x50, 0x44, 0xa5, 0x8d, 0x17, 0xef, 0x60, 0xbe,
	0xf7, 0x34, 0xcb, 0x20, 0xfa, 0x89, 0x6b, 0xdf, 0xb1, 0x09, 0x4d, 0x91, 0x5f, 0xa2, 0x9b, 0xd0,
	0xb7, 0xeb, 0xc0, 0xfb, 0xf0, 0x6d, 0x70, 0xf6, 0x37, 0x84, 0x87, 0xae, 0x45, 0x92, 0xe3, 0x40,
	0xe8, 0xc7, 0x0a, 0xb6, 0x63, 0x15, 0x90, 0x90, 0x16, 0x7a, 0x22, 0xab, 0x3d, 0xb9, 0xc8, 0xdc,
	0x58, 0x37, 0x96, 0xb3, 0x4a, 0x9f, 0x37, 0x3d, 0x63, 0x27, 0x24, 0x61, 0xc3, 0x23, 0xdb, 0xdc,
	0x06, 0xb2, 0x0f, 0x30, 0x73, 0xd3, 0x62, 0xc3, 0x63, 0x6b, 0x4e, 0xbe, 0x6f, 0x8e, 0xab, 0xec,
	0xdd, 0xc1, 0xc6, 0xf9, 0xb3, 0x55, 0x18, 0xb5, 0x35, 0xa5, 0x27, 0x63, 0xc6, 0x7d, 0xea, 0x6b,
	0x7f, 0xc5, 0xab, 0x37, 0x0a, 0xb6, 0x80, 0x19, 0x2a, 0x35, 0x2a, 0xa3, 0x4e, 0xec, 0x54, 0x5b,
	0xbc, 0xb8, 0x84, 0x47, 0x77, 0x8a, 0x1e, 0xe2, 0x9c, 0x11, 0xdf, 0xa9, 0x79, 0x90, 0xed, 0xb7,
	0x6e, 0xd5, 0xbe, 0xa2, 0x56, 0x6d, 0x4d, 0xec, 0x09, 0x24, 0x0a, 0x57, 0xed, 0x38, 0x78, 0xb5,
	0x47, 0xff, 0xed, 0xd8, 0x53, 0x48, 0x07, 0xd1, 0x23, 0x49, 0x51, 0xa3, 0x35, 0x39, 0x2d, 0x77,
	0x84, 0xc9, 0xd2, 0x54, 0xd1, 0x9a, 0x34, 0xf6, 0x76, 0x9d, 0xd2, 0x72, 0x47, 0xbc, 0x78, 0x05,
	0xb0, 0xfb, 0x68, 0x6c, 0x0e, 0xc7, 0xd7, 0xf8, 0x43, 0x4c, 0x9d, 0xce, 0x1e, 0x18, 0x70, 0x33,
	0xd5, 0x35, 0x12, 0x65, 0x01, 0x9b, 0x41, 0xfc, 0x59, 0xb4, 0x5d, 0x16, 0x5e, 0x3d, 0xff, 0xf6,
	0xac, 0x21, 0xf9, 0x52, 0x63, 0x2f, 0x3b, 0xa1, 0xf1, 0x5c, 0xc8, 0xf6, 0xdc, 0x18, 0x6f, 0x8f,
	0x4b, 0x73, 0x54, 0x89, 0xfd, 0x81, 0x5e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x42, 0x72,
	0x36, 0x4e, 0x03, 0x00, 0x00,
}
