// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/base.proto

package base

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusBase int32

const (
	StatusBase_Default StatusBase = 0
	StatusBase_Success StatusBase = 1
	StatusBase_Fail    StatusBase = 2
)

var StatusBase_name = map[int32]string{
	0: "Default",
	1: "Success",
	2: "Fail",
}
var StatusBase_value = map[string]int32{
	"Default": 0,
	"Success": 1,
	"Fail":    2,
}

func (x StatusBase) String() string {
	return proto.EnumName(StatusBase_name, int32(x))
}
func (StatusBase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_base_ea05ecaa03068dd3, []int{0}
}

// -----被调用 rpc 服务 推荐集成 context
type BaseRequest struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ip                   string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Abtest               map[string]string `protobuf:"bytes,3,rep,name=abtest,proto3" json:"abtest,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Debug                bool              `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	Openlog              bool              `protobuf:"varint,5,opt,name=openlog,proto3" json:"openlog,omitempty"`
	Tmax                 int64             `protobuf:"varint,6,opt,name=tmax,proto3" json:"tmax,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ea05ecaa03068dd3, []int{0}
}
func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (dst *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(dst, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseRequest) GetAbtest() map[string]string {
	if m != nil {
		return m.Abtest
	}
	return nil
}

func (m *BaseRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *BaseRequest) GetOpenlog() bool {
	if m != nil {
		return m.Openlog
	}
	return false
}

func (m *BaseRequest) GetTmax() int64 {
	if m != nil {
		return m.Tmax
	}
	return 0
}

// 被调服务 timeout 或其他异常情况，可以选填 部分字段 返回上一层
type BaseResponse struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Status               StatusBase        `protobuf:"varint,2,opt,name=status,proto3,enum=base.StatusBase" json:"status,omitempty"`
	Elapsed              int64             `protobuf:"varint,3,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Abtested             map[string]string `protobuf:"bytes,4,rep,name=abtested,proto3" json:"abtested,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Debugmsg             map[string]string `protobuf:"bytes,5,rep,name=debugmsg,proto3" json:"debugmsg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Errormsg             string            `protobuf:"bytes,6,opt,name=errormsg,proto3" json:"errormsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ea05ecaa03068dd3, []int{1}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseResponse) GetStatus() StatusBase {
	if m != nil {
		return m.Status
	}
	return StatusBase_Default
}

func (m *BaseResponse) GetElapsed() int64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *BaseResponse) GetAbtested() map[string]string {
	if m != nil {
		return m.Abtested
	}
	return nil
}

func (m *BaseResponse) GetDebugmsg() map[string]string {
	if m != nil {
		return m.Debugmsg
	}
	return nil
}

func (m *BaseResponse) GetErrormsg() string {
	if m != nil {
		return m.Errormsg
	}
	return ""
}

// ----- metrics
type BaseMetrics struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subsystem            string   `protobuf:"bytes,4,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMetrics) Reset()         { *m = BaseMetrics{} }
func (m *BaseMetrics) String() string { return proto.CompactTextString(m) }
func (*BaseMetrics) ProtoMessage()    {}
func (*BaseMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ea05ecaa03068dd3, []int{2}
}
func (m *BaseMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMetrics.Unmarshal(m, b)
}
func (m *BaseMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMetrics.Marshal(b, m, deterministic)
}
func (dst *BaseMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMetrics.Merge(dst, src)
}
func (m *BaseMetrics) XXX_Size() int {
	return xxx_messageInfo_BaseMetrics.Size(m)
}
func (m *BaseMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMetrics proto.InternalMessageInfo

func (m *BaseMetrics) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *BaseMetrics) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseMetrics) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *BaseMetrics) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

type BaseConsul struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Interval             int32    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseConsul) Reset()         { *m = BaseConsul{} }
func (m *BaseConsul) String() string { return proto.CompactTextString(m) }
func (*BaseConsul) ProtoMessage()    {}
func (*BaseConsul) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ea05ecaa03068dd3, []int{3}
}
func (m *BaseConsul) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseConsul.Unmarshal(m, b)
}
func (m *BaseConsul) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseConsul.Marshal(b, m, deterministic)
}
func (dst *BaseConsul) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseConsul.Merge(dst, src)
}
func (m *BaseConsul) XXX_Size() int {
	return xxx_messageInfo_BaseConsul.Size(m)
}
func (m *BaseConsul) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseConsul.DiscardUnknown(m)
}

var xxx_messageInfo_BaseConsul proto.InternalMessageInfo

func (m *BaseConsul) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *BaseConsul) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

// ----- feature
type FDeviceIds struct {
	Googleadid           string   `protobuf:"bytes,1,opt,name=googleadid,proto3" json:"googleadid,omitempty"`
	Idfa                 string   `protobuf:"bytes,2,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Googleadidmd5        string   `protobuf:"bytes,3,opt,name=googleadidmd5,proto3" json:"googleadidmd5,omitempty"`
	Googleadidsh1        string   `protobuf:"bytes,4,opt,name=googleadidsh1,proto3" json:"googleadidsh1,omitempty"`
	Imei                 string   `protobuf:"bytes,5,opt,name=imei,proto3" json:"imei,omitempty"`
	Imeimd5              string   `protobuf:"bytes,6,opt,name=imeimd5,proto3" json:"imeimd5,omitempty"`
	Imeisha1             string   `protobuf:"bytes,7,opt,name=imeisha1,proto3" json:"imeisha1,omitempty"`
	Androidid            string   `protobuf:"bytes,8,opt,name=androidid,proto3" json:"androidid,omitempty"`
	Androididmd5         string   `protobuf:"bytes,9,opt,name=androididmd5,proto3" json:"androididmd5,omitempty"`
	Androididsha1        string   `protobuf:"bytes,10,opt,name=androididsha1,proto3" json:"androididsha1,omitempty"`
	Oaid                 string   `protobuf:"bytes,11,opt,name=oaid,proto3" json:"oaid,omitempty"`
	Oaidmd5              string   `protobuf:"bytes,12,opt,name=oaidmd5,proto3" json:"oaidmd5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FDeviceIds) Reset()         { *m = FDeviceIds{} }
func (m *FDeviceIds) String() string { return proto.CompactTextString(m) }
func (*FDeviceIds) ProtoMessage()    {}
func (*FDeviceIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_ea05ecaa03068dd3, []int{4}
}
func (m *FDeviceIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FDeviceIds.Unmarshal(m, b)
}
func (m *FDeviceIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FDeviceIds.Marshal(b, m, deterministic)
}
func (dst *FDeviceIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FDeviceIds.Merge(dst, src)
}
func (m *FDeviceIds) XXX_Size() int {
	return xxx_messageInfo_FDeviceIds.Size(m)
}
func (m *FDeviceIds) XXX_DiscardUnknown() {
	xxx_messageInfo_FDeviceIds.DiscardUnknown(m)
}

var xxx_messageInfo_FDeviceIds proto.InternalMessageInfo

func (m *FDeviceIds) GetGoogleadid() string {
	if m != nil {
		return m.Googleadid
	}
	return ""
}

func (m *FDeviceIds) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *FDeviceIds) GetGoogleadidmd5() string {
	if m != nil {
		return m.Googleadidmd5
	}
	return ""
}

func (m *FDeviceIds) GetGoogleadidsh1() string {
	if m != nil {
		return m.Googleadidsh1
	}
	return ""
}

func (m *FDeviceIds) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *FDeviceIds) GetImeimd5() string {
	if m != nil {
		return m.Imeimd5
	}
	return ""
}

func (m *FDeviceIds) GetImeisha1() string {
	if m != nil {
		return m.Imeisha1
	}
	return ""
}

func (m *FDeviceIds) GetAndroidid() string {
	if m != nil {
		return m.Androidid
	}
	return ""
}

func (m *FDeviceIds) GetAndroididmd5() string {
	if m != nil {
		return m.Androididmd5
	}
	return ""
}

func (m *FDeviceIds) GetAndroididsha1() string {
	if m != nil {
		return m.Androididsha1
	}
	return ""
}

func (m *FDeviceIds) GetOaid() string {
	if m != nil {
		return m.Oaid
	}
	return ""
}

func (m *FDeviceIds) GetOaidmd5() string {
	if m != nil {
		return m.Oaidmd5
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "base.BaseRequest")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseRequest.AbtestEntry")
	proto.RegisterType((*BaseResponse)(nil), "base.BaseResponse")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseResponse.AbtestedEntry")
	proto.RegisterMapType((map[string]string)(nil), "base.BaseResponse.DebugmsgEntry")
	proto.RegisterType((*BaseMetrics)(nil), "base.BaseMetrics")
	proto.RegisterType((*BaseConsul)(nil), "base.BaseConsul")
	proto.RegisterType((*FDeviceIds)(nil), "base.FDeviceIds")
	proto.RegisterEnum("base.StatusBase", StatusBase_name, StatusBase_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BaseServiceClient is the client API for BaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BaseServiceClient interface {
	FindBase(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type baseServiceClient struct {
	cc *grpc.ClientConn
}

func NewBaseServiceClient(cc *grpc.ClientConn) BaseServiceClient {
	return &baseServiceClient{cc}
}

func (c *baseServiceClient) FindBase(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/base.BaseService/FindBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServiceServer is the server API for BaseService service.
type BaseServiceServer interface {
	FindBase(context.Context, *BaseRequest) (*BaseResponse, error)
}

func RegisterBaseServiceServer(s *grpc.Server, srv BaseServiceServer) {
	s.RegisterService(&_BaseService_serviceDesc, srv)
}

func _BaseService_FindBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).FindBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.BaseService/FindBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).FindBase(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.BaseService",
	HandlerType: (*BaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBase",
			Handler:    _BaseService_FindBase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/base.proto",
}

func init() { proto.RegisterFile("base/base.proto", fileDescriptor_base_ea05ecaa03068dd3) }

var fileDescriptor_base_ea05ecaa03068dd3 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0x9a, 0x26, 0x93, 0xb6, 0x84, 0x15, 0x42, 0x56, 0x44, 0x51, 0x14, 0x71, 0x88,
	0x38, 0x14, 0x5a, 0x54, 0x89, 0x8f, 0x1e, 0xf8, 0x28, 0x95, 0x7a, 0xe0, 0xe2, 0xfe, 0x00, 0xb4,
	0xc9, 0x4e, 0xd3, 0x15, 0xfe, 0xea, 0xee, 0xba, 0xa2, 0xff, 0x99, 0x13, 0xe2, 0x07, 0xa0, 0x99,
	0xdd, 0x38, 0xb1, 0x22, 0x0e, 0xbd, 0x24, 0xf3, 0x9e, 0x77, 0x66, 0xde, 0x3c, 0xcf, 0x1a, 0x1e,
	0xcf, 0xa5, 0xc5, 0xd7, 0xf4, 0x73, 0x54, 0x99, 0xd2, 0x95, 0xa2, 0x4b, 0xf1, 0xf4, 0x4f, 0x04,
	0xc3, 0x2f, 0xd2, 0x62, 0x8a, 0xb7, 0x35, 0x5a, 0x27, 0x0e, 0x01, 0x8c, 0x0f, 0x7f, 0x68, 0x95,
	0x44, 0x93, 0x68, 0x36, 0x48, 0x07, 0x81, 0xb9, 0x54, 0xe2, 0x00, 0x62, 0x5d, 0x25, 0x31, 0xd3,
	0xb1, 0xae, 0xc4, 0x29, 0xf4, 0xe4, 0xdc, 0xa1, 0x75, 0x49, 0x67, 0xd2, 0x99, 0x0d, 0x4f, 0x0e,
	0x8f, 0xb8, 0xc3, 0x46, 0xc5, 0xa3, 0xcf, 0xfc, 0xfc, 0x5b, 0xe1, 0xcc, 0x7d, 0x1a, 0x0e, 0x8b,
	0xa7, 0xb0, 0xa3, 0x70, 0x5e, 0x2f, 0x93, 0xee, 0x24, 0x9a, 0xf5, 0x53, 0x0f, 0x44, 0x02, 0xbb,
	0x65, 0x85, 0x45, 0x56, 0x2e, 0x93, 0x1d, 0xe6, 0x57, 0x50, 0x08, 0xe8, 0xba, 0x5c, 0xfe, 0x4a,
	0x7a, 0x93, 0x68, 0xd6, 0x49, 0x39, 0x1e, 0xbf, 0x87, 0xe1, 0x46, 0x69, 0x31, 0x82, 0xce, 0x4f,
	0xbc, 0x0f, 0x8a, 0x29, 0xa4, 0x26, 0x77, 0x32, 0xab, 0x31, 0xc8, 0xf5, 0xe0, 0x43, 0xfc, 0x2e,
	0x9a, 0xfe, 0x8d, 0x61, 0xcf, 0x4b, 0xb4, 0x55, 0x59, 0x58, 0x0c, 0x63, 0x45, 0xcd, 0x58, 0x33,
	0xe8, 0x59, 0x27, 0x5d, 0x6d, 0x39, 0xf7, 0xe0, 0x64, 0xe4, 0xc7, 0xba, 0x62, 0x8e, 0x33, 0xc3,
	0x73, 0xd2, 0x8c, 0x99, 0xac, 0x2c, 0xaa, 0xa4, 0xc3, 0xe2, 0x56, 0x50, 0x9c, 0x41, 0xdf, 0x4f,
	0x8b, 0x2a, 0xe9, 0xb2, 0x39, 0x93, 0x4d, 0x73, 0x7c, 0xe7, 0xe0, 0x0e, 0x2a, 0xef, 0x4f, 0x93,
	0x41, 0xd9, 0x6c, 0x4a, 0x6e, 0xc9, 0x8c, 0xff, 0x65, 0x9f, 0x87, 0x23, 0x21, 0x7b, 0x95, 0x21,
	0xc6, 0xd0, 0x47, 0x63, 0x4a, 0x43, 0xd9, 0x3d, 0x9e, 0xaa, 0xc1, 0xe3, 0x8f, 0xb0, 0xdf, 0x6a,
	0xfa, 0x10, 0xe7, 0x28, 0xb9, 0xd5, 0xf3, 0x41, 0xb6, 0xdf, 0xfa, 0x55, 0xfb, 0x8e, 0xce, 0xe8,
	0x85, 0x15, 0xcf, 0xa0, 0x67, 0x70, 0xa9, 0xcb, 0x22, 0x64, 0x07, 0xb4, 0xb5, 0x63, 0xcf, 0x61,
	0x50, 0xc8, 0x1c, 0x6d, 0x25, 0x17, 0xc8, 0x26, 0x0f, 0xd2, 0x35, 0x41, 0x4f, 0x6d, 0x3d, 0xb7,
	0xf7, 0xd6, 0x61, 0xce, 0xeb, 0x34, 0x48, 0xd7, 0xc4, 0xf4, 0x0c, 0x80, 0x5a, 0x7e, 0x2d, 0x0b,
	0x5b, 0x67, 0xb4, 0x46, 0x52, 0x29, 0x13, 0xfa, 0x71, 0x4c, 0x56, 0xe9, 0xc2, 0xa1, 0xb9, 0x93,
	0x19, 0xf7, 0xdc, 0x49, 0x1b, 0x3c, 0xfd, 0x1d, 0x03, 0x5c, 0x9c, 0xe3, 0x9d, 0x5e, 0xe0, 0xa5,
	0xb2, 0xe2, 0x05, 0xc0, 0xb2, 0x2c, 0x97, 0x19, 0x4a, 0xd5, 0xdc, 0x8d, 0x0d, 0x86, 0xca, 0x6b,
	0x75, 0x2d, 0x83, 0x74, 0x8e, 0xc5, 0x4b, 0xd8, 0x5f, 0x9f, 0xc8, 0xd5, 0x69, 0x18, 0xa0, 0x4d,
	0xb6, 0x4f, 0xd9, 0x9b, 0xe3, 0x30, 0x48, 0x9b, 0xe4, 0xfa, 0x39, 0x6a, 0xbe, 0x1c, 0x54, 0x3f,
	0x47, 0x4d, 0xfb, 0x47, 0xff, 0x54, 0xd9, 0xbf, 0xe8, 0x15, 0xe4, 0xc1, 0x72, 0xd4, 0xf6, 0x46,
	0x1e, 0x27, 0xbb, 0x7e, 0x07, 0x56, 0x98, 0x4c, 0x93, 0x85, 0x32, 0xa5, 0xa6, 0x41, 0xfa, 0xde,
	0xb4, 0x86, 0x10, 0x53, 0xd8, 0x6b, 0x00, 0x15, 0x1e, 0xf0, 0x81, 0x16, 0x47, 0x8a, 0x1b, 0xcc,
	0x2d, 0xc0, 0x2b, 0x6e, 0x91, 0xa4, 0xb8, 0x94, 0x5a, 0x25, 0x43, 0xaf, 0x98, 0x62, 0xbe, 0xe5,
	0xd2, 0x17, 0xde, 0xf3, 0x8a, 0x03, 0x7c, 0xf5, 0x06, 0x60, 0x7d, 0xc3, 0xc4, 0x10, 0x76, 0xcf,
	0xf1, 0x5a, 0xd6, 0x99, 0x1b, 0x3d, 0x22, 0x70, 0x55, 0x2f, 0x16, 0x68, 0xed, 0x28, 0x12, 0x7d,
	0xe8, 0x5e, 0x48, 0x9d, 0x8d, 0xe2, 0x93, 0x4f, 0x7e, 0xa3, 0xae, 0xd0, 0xd0, 0x3b, 0x12, 0xc7,
	0xd0, 0xbf, 0xd0, 0x85, 0xe2, 0xf4, 0x27, 0x5b, 0x5f, 0xa2, 0xb1, 0xd8, 0xbe, 0x41, 0xf3, 0x1e,
	0x7f, 0x0c, 0xdf, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x39, 0x28, 0x38, 0xed, 0x1f, 0x05, 0x00,
	0x00,
}
